swiftlang/swift-llbuild

- docs/buildsystem.rst
- lib/BuildSystem/BuildSystem.cpp
- tests/BuildSystem/Build/archive.llbuild
Constructs an archive from provided inputs, intended for static library archives.
Takes `inputs` and `outputs` only.
Any virtual nodes are ignored when constructing the `ar` instantiation.
I consider this PR incomplete:
So I await some feedback.
> Add “archive” tool

- include/llbuild/Core/BuildDB.h
**Changes made:**
* `s/uniqu/unique/`
* `s/for/from/` in one place because latter makes contextual sense
Should not affect the build.
> [gardening] Fix cosmetic and non-cosmetic typos

- bindings/swift/llbuild.swift
Updates the Swift bindings for `llbuild` to version `2.2`.
To address the following deprecation warnings:
* [_Removing `var` from Function Parameters_](https://github.com/apple/swift-evolution/blob/master/proposals/0003-remove-var-parameters.md)
* [_Remove the `++` and `--` operators_](https://github.com/apple/swift-evolution/blob/master/proposals/0004-remove-pre-post-inc-decrement.md)
None that I can think of!
> Update Swift bindings for llbuild to 2.2

- docs/buildsystem.rst
- include/llbuild/BuildSystem/BuildFile.h
- lib/BuildSystem/BuildFile.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/Commands/BuildSystemCommand.cpp
- tests/BuildSystem/Build/basic.llbuild
Fixes https://bugs.swift.org/browse/SR-1173
> Add support to define a default target in manifest file

- lib/BuildSystem/SwiftTools.cpp
We were saying "Link foo" but "Compiling bar", this makes it "Compile bar", but I am not fussed if you'd rather the other way.
> Consistent tense for Compile/Link

- lib/Core/SQLiteBuildDB.cpp
Bug: https://bugs.swift.org/browse/SR-1140
@ddunbar This is working except that no entry from keys table is deleted right now. 
Can you check if this is right approach.
> Optimize storage of dependency keys

- CMakeLists.txt
- cmake/modules/FindSwiftc.cmake
- cmake/modules/Utility.cmake
- examples/swift-bindings/core/basic.swift
- products/swift-bindings/CMakeLists.txt
- products/swift-bindings/llbuild.swift
- tests/CMakeLists.txt
- tests/Examples/lit.local.cfg
- tests/Examples/swift-bindings/core/basic.txt
- tests/lit.cfg
- tests/lit.site.cfg.in
This PR is an attempt to get the swift bindings integrated into the build.
It generates a dylib for swift bindings. Added a lit test to test the bindings. cmake will try to detect swiftc and build the bindings only if swiftc is available.
> Swift binding integration

- lib/Commands/NinjaBuildCommand.cpp
We have to include cstdarg to avoid build failures relating to va_lists on debian Jessie armv7. I'm surprised it wasn't needed before.
> [76/95] Building CXX object lib/Commands/CMakeFiles/llbuildCommands.dir/NinjaBuildCommand.cpp.o
FAILED: /Spring/Projects/3rdParty/OpenSource/Apple/build/Ninja-ReleaseAssert/llvm-macosx-x86_64/bin/clang++  --target=armv7-linux-gnueabihf --sysroot=/Spring/Projects/3rdParty/OpenSource/Apple/cross-compile/sysroots/sysroot.armhf.debian.jessie   -I/Spring/Projects/3rdParty/OpenSource/Apple/llbuild/include -isystem /Spring/Projects/3rdParty/OpenSource/Apple/cross-compile/sysroots/sysroot.armhf.debian.jessie/usr/include/c++/4.8 -isystem /Spring/Projects/3rdParty/OpenSource/Apple/cross-compile/sysroots/sysroot.armhf.debian.jessie/usr/include/arm-linux-gnueabihf/c+ …
> Fix for building on linux-armv7

- products/swift-bindings/llbuild.swift
[SE-0025](https://github.com/apple/swift-evolution/blob/master/proposals/0025-scoped-access-level.md) makes `private` restrict access to a lexical scope; the Swift 2 behavior is now named `fileprivate`. At the time of this pull request, the compiler treats both `private` and `fileprivate` as having `fileprivate` semantics, but that will soon change.
> Update for SE-0025 ('fileprivate' and 'private')

- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- lib/Commands/NinjaBuildCommand.cpp
Cygwin doesn't have SIGUNUSED.
> Fixed for Cygwin

- utils/Xcode/extract-perf-data
- utils/Xcode/xcs-submit-perf-data.sh
Modified `extract-perf-data` to work with the TestSummaries.plist from result bundle instead of the binary .xcactivitylog
> Improve robustness of `extract-perf-data` script

- CMakeLists.txt
- lib/Basic/CMakeLists.txt
- lib/Ninja/CMakeLists.txt
- lib/llvm/Support/CMakeLists.txt
- lib/llvm/Support/Unix/Process.inc
- unittests/Ninja/CMakeLists.txt
Many of the places in the CMake files that check for Linux really ought to check for *BSD or Linux, but a few of them are FreeBSD-specific (e.g., libexecinfo).
> Add FreeBSD build support.

- cmake/modules/FindFileCheck.cmake
This corresponds to <https://github.com/apple/swift-llbuild/blob/master/utils/Xcode/create-lit-site-cfg.sh#L5-L11>, however I didn't have enough Cmake knowledge to make this work for custom Homebrew paths as well.
> [Cmake] Look for FileCheck in well-known locations

- include/llbuild/BuildSystem/BuildExecutionQueue.h
- include/llbuild/BuildSystem/BuildSystem.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- lib/BuildSystem/SwiftTools.cpp
- lib/Commands/BuildSystemCommand.cpp
- llbuild.xcodeproj/project.pbxproj
- products/libllbuild/BuildSystem-C-API.cpp
- tests/BuildSystem/Build/Inputs/ignore-sigint
- tests/BuildSystem/Build/sigkill-escalation.llbuild
- tests/BuildSystem/Build/signal-handling.llbuild
- unittests/BuildSystem/CMakeLists.txt
- unittests/BuildSystem/LaneBasedExecutionQueueTest.cpp
- unittests/CMakeLists.txt
Right now, cancellation is only supported when using the C API.
Missing:
I opted to not refactor the ninja stuff for now, which has its own implementation of cancellation. I think that can be done in a separate PR.
> Support for build cancellation

- include/llbuild/BuildSystem/BuildExecutionQueue.h
- include/llbuild/BuildSystem/BuildSystem.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- lib/BuildSystem/SwiftTools.cpp
- lib/Commands/BuildSystemCommand.cpp
- llbuild.xcodeproj/project.pbxproj
- products/libllbuild/BuildSystem-C-API.cpp
- tests/BuildSystem/Build/Inputs/ignore-sigint
- tests/BuildSystem/Build/sigkill-escalation.llbuild
- tests/BuildSystem/Build/signal-handling.llbuild
- tests/Ninja/Build/signal-handling.ninja
- unittests/BuildSystem/CMakeLists.txt
- unittests/BuildSystem/LaneBasedExecutionQueueTest.cpp
- unittests/CMakeLists.txt
- Implement the ability to cancel running builds
- Invoke `cancel()` on `SIGINT` when executing build systems commands via CLI.
- Test for SIGINT handling and for SIGKILL escalation
- Unit test for cancellation in `LaneBasedExecutionQueue`
- Reactivate Ninja cancellation test (issue was sh vs. bash)
Follow up to #42 which fixes test issues on Linux.
> <rdar://problem/28676638> Need BuildSystem support for build cancellation

- examples/c-api/buildsystem/main.c
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/public-api/llbuild/buildsystem.h
- This is used by C API clients supplying custom tools to track when those
tools (which may embed their own state) may need to be rerun, even if other
aspects of the command haven't changed.
> [libllbuild] Allow clients to supply custom command signatures.

- tests/BuildSystem/Build/sigkill-escalation.llbuild
- tests/BuildSystem/Build/signal-handling.llbuild
- tests/Ninja/Build/signal-handling.ninja
Unfortunately, we are still seeing some occassional flakiness of these on CI, so we will disable them for now.
> Disable signal handling tests on Linux

- docs/buildsystem.rst
- lib/BuildSystem/BuildSystem.cpp
- tests/BuildSystem/Build/mkdir.llbuild
- These will be treated as "must follow" inputs, since the commands themselves
do not use them, but this allows clients to control the order in which these
commands are run.
> [BuildSystem] Allow inputs for Mkdir/Symlink.

- include/llbuild/BuildSystem/BuildSystem.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- include/llbuild/BuildSystem/BuildValue.h
- include/llbuild/BuildSystem/ExternalCommand.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/BuildSystem/BuildValue.cpp
- lib/BuildSystem/ExternalCommand.cpp
- llbuild.xcodeproj/project.pbxproj
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/public-api/llbuild/buildsystem.h
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
- unittests/BuildSystem/CMakeLists.txt
This allows a build system delegate to run a subset of the build by explicitly skipping commands yet allowing dependent commands to run.
As a prerequisite, this includes a separate commit to disambiguate BuildValue::SkippedCommand into FailedDependencyCommand and CancelledCommand.
> Command skipping

- CMakeLists.txt
This lets us support platforms that don't natively have sqlite3.lib, such as Windows. The naming convention and structure matches the way LLVM /LLDB/Clang allows you to configure external dependencies
```
mkdir "%swift_source_dir%/build-msvc/Ninja-DebugAssert/llbuild-windows-x86_64/vs"
pushd "%swift_source_dir%/build-msvc/Ninja-DebugAssert/llbuild-windows-x86_64/vs"
cmake -G "Visual Studio 14 2015"^
-DCMAKE_GENERATOR_PLATFORM="x64"^
-DCMAKE_BUILD_TYPE=Debug^
-DLIT_EXECUTABLE="%swift_source_dir%/build-msvc/llvm-windows-x86_64/bin/llvm-lit.py"^
-DFILECHECK_EXECUTABLE="%swift_source_dir%/build-msvc/llvm-windows-x86_64/bin/FileCheck.exe"^
-DLLDB_PATH_TO_SQLITE_SOURCE="%swift_source_dir%/sql"^
-DLLDB_PATH_TO_SQLITE_BUILD="%swift_source_dir%/sqlite3-windows-x86_64"^
"%swift_source_dir%/llbuild" …
```
> Add support for passing sqlite3 library and include directory

- CMakeLists.txt
Firstly, this avoids compiler errors building LLBuild, owing to unknown compiler flags
Secondly, this silences some warnings that we don't want (e.g. unknown pragma), but also ones that LLVMSupport ignores to avoid a cluttered build log and to avoid needing to modify the llvmSupport code
> Fix command line arguments passed to the MSVC compiler invocation

- llbuild.xcodeproj/project.pbxproj
Since this file is imported from LLVM, we do not want to change it in the llbuild codebase. Instead we are selectively disabling the analyzer for this specific file.
Fixes rdar://problem/29870716
> Disable analyzer for `raw_ostream.cpp`

- include/llbuild/BuildSystem/BuildSystem.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- include/llbuild/BuildSystem/BuildValue.h
- include/llbuild/BuildSystem/ExternalCommand.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/BuildSystem/BuildValue.cpp
- lib/BuildSystem/ExternalCommand.cpp
- llbuild.xcodeproj/project.pbxproj
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/public-api/llbuild/buildsystem.h
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
- unittests/BuildSystem/CMakeLists.txt
This allows a build system delegate to run a subset of the build by
explicitly skipping commands yet allowing dependent commands to run.
> Support command skipping with shouldCommandStart.

- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- llbuild.xcodeproj/project.pbxproj
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
- unittests/BuildSystem/CMakeLists.txt
- unittests/BuildSystem/LaneBasedExecutionQueueTest.cpp
- unittests/BuildSystem/TempDir.cpp
- unittests/BuildSystem/TempDir.hpp
- Fix race between signaling the sigkill-escalation thread and actually starting it
- Fix `LaneBasedExecutionQueueTest` so that we wait until the `yes` process has started before trying to kill it
> Fix races in `LaneBasedExecutionQueueTest`

- include/llbuild/Core/BuildDB.h
- include/llbuild/Core/BuildEngine.h
- lib/BuildSystem/BuildSystem.cpp
- lib/Commands/NinjaBuildCommand.cpp
- lib/Core/BuildEngine.cpp
- lib/Core/SQLiteBuildDB.cpp
- llbuild.xcodeproj/project.pbxproj
- products/libllbuild/Core-C-API.cpp
- unittests/Core/BuildEngineTest.cpp
- unittests/Core/DepsBuildEngineTest.cpp
- unittests/Core/SQLiteBuildDBTest.cpp
- Extend DB APIs with out error parameters
- The error message will point users to potentially concurrently running builds if the cause of the error is multiple DB connections
- Handling of errors in `BuildEngine` is pretty basic, but that matches all the current error handling in that class
see rdar://problem/27615139
> Improve error handling in `SQLiteBuildDB`

- lib/BuildSystem/BuildSystem.cpp
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
We've discussed refactoring this common behavior in {Mkdir, Symlink, and
External}Command, but I'm not in a position to do that right now.
> [BuildSystem] Check for SkippedCommand in MkdirCommand and SymlinkCommand.

- lib/Core/BuildEngine.cpp
> 1>C:\Users\hbellamy\Documents\GitHub\my-swift\llbuild\lib\Core\BuildEngine.cpp(974): error C2440: 'initializing': cannot convert from 'initializer list' to '`anonymous-namespace'::BuildEngineImpl::reportCycle::WorkItem'
> 1>  C:\Users\hbellamy\Documents\GitHub\my-swift\llbuild\lib\Core\BuildEngine.cpp(974): note: No constructor could take the source type, or constructor overload resolution was ambiguous
> 1>C:\Users\hbellamy\Documents\GitHub\my-swift\llbuild\lib\Core\BuildEngine.cpp(995): error C2440: 'initializing': cannot convert from 'initializer list' to '`anonymous-namespace'::BuildEngineImpl::reportCycle::WorkItem'
> 1>  C:\Users\hbellamy\Documents\GitHub\my-swift\llbuild\lib\Core\BuildEngine.cpp(995): note: No constructor could take the source type, or constructor overload …
> Port lib/Core to Windows/MSVC

- include/llbuild/BuildSystem/BuildValue.h
- lib/BuildSystem/BuildSystem.cpp
- llbuild.xcodeproj/project.pbxproj
- unittests/BuildSystem/BuildValueTest.cpp
- unittests/BuildSystem/CMakeLists.txt
- The initializer was allowing uninitialized data in the commandSignature for
sentinel values (like virtual inputs).
- The move initialization was failing to initialize some fields (!).
- The serialization was also failing to properly normalize values, so the
serialized value was not properly deterministic.
> [BuildSystem] Fix BuildValue initialization & serialization.

- docs/buildsystem.rst
- include/llbuild/BuildSystem/BuildNode.h
- include/llbuild/Core/BuildEngine.h
- lib/BuildSystem/BuildNode.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/ExternalCommand.cpp
- lib/Core/BuildEngine.cpp
- tests/BuildSystem/Build/command-dependencies.llbuild
- These nodes can be used to build relationships between commands which
effectively cause one command to trigger another to build any time it
updates.
- This can be used as part of a primitive mechanism for supporting commands
which need to mutate the outputs of other commands, by treating the output as
effectively one of the mutating command, and using a trigger relationship
between the producing & mutation commands to cause them to run in concert.
> [BuildSystem] Add support for "command timestamp" nodes.

- include/llbuild/Core/BuildEngine.h
- lib/BuildSystem/BuildSystem.cpp
- lib/Commands/BuildEngineCommand.cpp
- lib/Commands/NinjaBuildCommand.cpp
- lib/Core/BuildEngine.cpp
- perftests/Xcode/PerfTests/CorePerfTests.mm
- products/libllbuild/Core-C-API.cpp
- products/libllbuild/public-api/llbuild/core.h
- unittests/Core/BuildEngineTest.cpp
- unittests/Core/DepsBuildEngineTest.cpp
- Added delegate method for error propagation to `BuildEngineDelegate`
- Added delegate function pointer for error propagation to `llb_buildengine_delegate_t_`
- Adopted delegate implementations and tests accordingly
- `BuildEngine` uses this to report errors instead of aborting
> <rdar://problem/30059364> BuildEngine shouldn't call exit for error handling that isn't necessarily a programmer error

- CMakeLists.txt
- tests/CMakeLists.txt
Python executables have to be executed via `python x.py` on Windows. Keep this on all platforms, to avoid platform specific code.
> Invoke llvm-lit.py with Python

- unittests/Core/DependencyInfoParserTest.cpp
> 6>C:\Users\hughb\Documents\GitHub\swift\llbuild\unittests\Core\DependencyInfoParserTest.cpp(59): error C2143: syntax error: missing ';' before '{'
6>C:\Users\hughb\Documents\GitHub\swift\llbuild\unittests\Core\DependencyInfoParserTest.cpp(59): error C2059: syntax error: ')'
I also ran clang-format on the line
> Fix unit tests build failures with MSVC

- include/llbuild/Basic/Compiler.h
- include/llvm/Config/config.h
- include/llvm/Config/llvm-config.h
- Not all compilers have __has_include and __has_feature
- Windows doesn't have some of these includes and functions
This fixes several hundred build errors compiling LLBuild on Windows.
Note that some othe changed #ifdefs are not used yet, but adding them here to simplify the diff
> Fixup Configuration files for Windows

- products/libllbuild/public-api/llbuild/llbuild.h
Windows requires the use of `__declspec(dllexport)`. This works with MSVC, Clang and GCC. This fixes the exported API on Windows.
However, MSVC doesn't understand `__attribute()` syntax, so this also fixes many build errors.
> Fix LLBUILD_EXPORT for Windows

- tests/Unit/lit.cfg
This fixes lit configuration errors running the unit tests on Windows
> Define config.shlibdir in lit.cfg

- lib/BuildSystem/BuildSystemFrontend.cpp
Use c++ 11's hardware_concurrency:
See http://en.cppreference.com/w/cpp/thread/thread/hardware_concurrency
Also change the error condition: `hardware_concurrency` returns 0 if it fails
> Make detection of number of CPUs platform independent

- lib/Commands/BuildEngineCommand.cpp
> warning C4129: 'e': unrecognized character escape sequence
I'm not sure what the intention here is:
- Accidental inclusion of `\error`: there are other cases in this file of `error` without `\error`
- Use of GCC extension escape sequence `\e`
- Wanting to print `\` to the stream, ie. `\\error`
I went with the first, but let me know
> Fix MSVC warnings for unknown escape character sequence

- lib/Commands/NinjaBuildCommand.cpp
Use the LLVM utility TimeValue - which is implemented in terms of `gettimeofday` on Unix, so no behaviour change there
> Make getTimeInMicroseconds() platform independent

- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- tests/BuildSystem/Build/sigkill-escalation.llbuild
If environment variable `LLBUILD_TEST` is present, the timeout will be shortened.
Fixes <rdar://problem/29678182> sigkill test is taking too long
> Shorten sigkill timeout to 0.1s when testing

- examples/c-api/buildsystem/main.c
- include/llbuild/BuildSystem/BuildExecutionQueue.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- include/llbuild/BuildSystem/CommandResult.h
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- llbuild.xcodeproj/project.pbxproj
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/public-api/llbuild/buildsystem.h
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
- unittests/BuildSystem/LaneBasedExecutionQueueTest.cpp
We need to make sure we don't count cancelled commands as command failures. This is probably the simplest way to do it, but maybe we want to do something more sophisticated?
> Ignore command failures after being cancelled

- examples/c-api/buildsystem/main.c
- include/llbuild/BuildSystem/BuildExecutionQueue.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- include/llbuild/BuildSystem/CommandResult.h
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- llbuild.xcodeproj/project.pbxproj
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/public-api/llbuild/buildsystem.h
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
- unittests/BuildSystem/LaneBasedExecutionQueueTest.cpp
> Cherry pick of "Don't fail `executeProcess()` if SIGINT or SIGKILL" to Swift 3.1 branch

- lib/Commands/NinjaBuildCommand.cpp
`vsnprintf(NULL, ...)` returns the length of the output string.
Therefore, use this before calling `vsnprintf` again, to figure out the correct length of the string.
Discussion:
`  if (::vsnprintf(buf, sizeof(buf), fmt, ap) < 0) {` can't really fail, as we're guaranteed to have the correct length.
Should we use an assertion here, instead of an if?
> Add implementation of vasprintf on Windows

- docs/buildsystem.rst
- include/llbuild/BuildSystem/BuildNode.h
- lib/BuildSystem/BuildNode.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/ExternalCommand.cpp
- tests/BuildSystem/Build/mutable-outputs.llbuild
- This can be used to indicate a file which is mutated by subsequent commands,
and cannot have its stat information (other than existence) meaningfully
checked. This can be used as with command timestamp nodes as part of a
primitive mechanism for supporting commands which mutate their inputs.
> [BuildSystem] Add support for an 'is-mutated' node flag.

- lib/BuildSystem/BuildSystem.cpp
- tests/BuildSystem/Build/mkdir.llbuild
- The most important impact of this is that it allows this command to use all
of the general purpose machinery from the ExternalCommand w.r.t. input and
output handling. In particular, MkdirCommand's can now drive virtual output
nodes.
> [BuildSystem] Switch MkdirCommand to be be an ExternalCommand.

- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- lib/Commands/NinjaBuildCommand.cpp
On Windows/MSVC, environ is not an` extern "C"` field in the global namespace.
Instead, it's a macro that returns a pointer.
Therefore, we get errors trying to declare `extern char **environ`, and we also get errors trying to refer to `::environ`. The fix is to remove `::`, which we can also do on non-Windows/MSVC platforms.
> warning C4273: '__p__environ': inconsistent dll linkage
> error C2589: '(': illegal token on right side of '::'
> error C2059: syntax error: '::' 
I have introduced `#ifdefs` around the `extern "C"` declaration of `environ` to fix the first issue mentioned. Can move them to a platform specific file if you'd like.
> Fix environ uses on Windows/MSVC

- lib/Commands/NinjaBuildCommand.cpp
I missed this in #82 as I hadn't got lib/Commands building at that point
> Fix another use of `sysconf` instead of platform independent c++ 11

- lib/Commands/NinjaBuildCommand.cpp
> [9/16] Building CXX object lib/Commands/CMakeFiles/llbuildCommands.dir/NinjaBuildCommand.cpp.o
> /mnt/c/Users/hughb/Documents/GitHub/swift-linux/swift-llbuild/lib/Commands/NinjaBuildCommand.cpp:979:25: warning: format specifies type 'unsigned long long' but the argument has type 'uint64_t' (aka 'unsigned long') [-Wformat]
>                        startTime);
>                       ^~~~~~~~~
> /mnt/c/Users/hughb/Documents/GitHub/swift-linux/swift-llbuild/lib/Commands/NinjaBuildCommand.cpp:993:25: warning: format specifies type 'unsigned long long' but the argument has type 'uint64_t' (aka 'unsigned long') [-Wformat]
>                       endTime);
>                       ^~~~~~~
> 2 warnings generated.
This is because `startTime` and `endTime` are `uint64_t`. On Windows x64, it's …
> Fix format specifier warnings compiling NinjaBuildCommand.cpp

- lib/Commands/BuildSystemCommand.cpp
- lib/Commands/NinjaBuildCommand.cpp
- Implicit conversion of NULL to char
- unknown escape '\e' that I missed in #83
> Fixup some MSVC warnings

- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- unittests/BuildSystem/LaneBasedExecutionQueueTest.cpp
Before this, we were bailing early and not running tasks anymore after cancellation. This can be very problematic, because it can mean llbuild would wait indefinitely for tasks to complete. This change ensures that the queue will be exhausted after cancellation.
Note: this also fixes an issue where calling `cancelAllJobs()` multiple times would crash.
> Exhaust queue after build cancellation

- lib/BuildSystem/LaneBasedExecutionQueue.cpp
After the changes in #104, we should make sure to not spawn any new processes after cancellation in order to ensure a timely end of the build after cancelling it.
> Do not execute new processes anymore after cancel

- docs/buildsystem.rst
- include/llbuild/BuildSystem/BuildExecutionQueue.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/public-api/llbuild/buildsystem.h
- products/libllbuild/public-api/llbuild/llbuild.h
- tests/BuildSystem/Build/basic.llbuild
- unittests/BuildSystem/LaneBasedExecutionQueueTest.cpp
- This allows clients to have exact control over the environment used when
launching subprocesses, as well as individual control on a per-task basis
over whether or not that environment should be inherited or replaced by an
individual task.
> [BuildSystem] Add support for a base environment.

- include/llbuild/Basic/FileInfo.h
- include/llbuild/BuildSystem/BuildValue.h
- lib/BuildSystem/BuildSystem.cpp
- unittests/BuildSystem/BuildValueTest.cpp
- This cleans up some gross code which was trying to use type punning but then
having to mask off the non-deterministic values
- Instead, now we just properly encode only the data we wish to, which reduces
the encoded size of BuildValues significantly in some cases.
- On average, this reduces the encoded BuildValue size by 50% for all encodings
done on our test suite.
> [BuildSystem] Switch BuildValue to use BinaryCoding.

- include/llbuild/BuildSystem/BuildDescription.h
- include/llbuild/BuildSystem/BuildSystem.h
- lib/BuildSystem/BuildSystem.cpp
- llbuild.xcodeproj/project.pbxproj
- unittests/BuildSystem/BuildSystemTaskTests.cpp
- unittests/BuildSystem/CMakeLists.txt
- unittests/BuildSystem/MockBuildSystemDelegate.cpp
- unittests/BuildSystem/MockBuildSystemDelegate.h
- unittests/BuildSystem/TempDir.cpp
- This exposes a new internal API from the BuildSystem which lets clients
request the results for arbitrary BuildKeys, which in turn lets us unit test
specific tasks much more effectively, when combined with the previous work to
allow us to manually build up an in memory build description.
> [BuildSystem] Add support for task-level build system tests.

- include/llbuild/Basic/BinaryCoding.h
- include/llbuild/BuildSystem/BuildValue.h
- unittests/BuildSystem/BuildValueTest.cpp
- We don't generally use this, but it is convenient to support empty values as
a valid sentinel.
> [BuildSystem] Don't crash decoding empty values.

- include/llbuild/Basic/BinaryCoding.h
- include/llbuild/BuildSystem/BuildKey.h
- include/llbuild/BuildSystem/BuildValue.h
- lib/BuildSystem/BuildKey.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildValue.cpp
- lib/Core/BuildEngine.cpp
- unittests/Basic/BinaryCodingTests.cpp
- unittests/BuildSystem/BuildSystemTaskTests.cpp
- unittests/BuildSystem/BuildValueTest.cpp
- This is another new task type which computes a recursive signature of
a complete directory tree.
- This isn't yet as efficient as it absolutely could be, because it
ends up using both a node and directory contents input which
duplicate some data, but this is expected to be a fairly heavyweight
task now anyway.
- This does not yet properly handle symbolic links, and still isn't
used by anything real yet...
- The signature is intentionally constructed so that it will always end up
accumulating dependency edges on any nodes in the graph which produce the
contents of the directory, for files which exist. It does *not* attempt to
scan the entire dependency graph to accumulate edges on nodes which are not
produced, thus clients are currently required to explicitly ensure some other
ordering …
> [BuildSystem] Add support for directory signatures.

- docs/buildsystem.rst
- include/llbuild/BuildSystem/BuildNode.h
- lib/BuildSystem/BuildNode.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/ExternalCommand.cpp
- tests/Examples/buildsystem-capi.llbuild
- This adapts the directory tree signature so that it can finally be used in a
build file to express dependencies for commands which consider their input
paths recursively.
- <rdar://problem/22640399> [llbuild] Add support for dependencies on directory contents
> [BuildSystem] Add support for directory nodes.

- docs/buildsystem.rst
- lib/BuildSystem/BuildSystem.cpp
- tests/BuildSystem/Build/directory-tree-signatures.llbuild
- This was an oversight -- normally this isn't required because the values for
each recursively requested node end up serving as a signature for the
top-level directory. However, when the top-level item *isn't* a directory,
but is a missing directory or a file, then this fails.
- <rdar://problem/30638878> Directory based dependencies need to be behave properly when tracking non-directories
> [BuildSystem] Directory tree signatures must include path value.

- lib/BuildSystem/BuildSystem.cpp
- tests/BuildSystem/Build/directory-tree-signatures.llbuild
- Although the value itself isn't currently used, this is important for
ensuring a dependency edge between a possible producer of the directory.
> [BuildSystem] Directory contents should depend on the input dir node.

- examples/c-api/buildsystem/main.c
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- lib/BuildSystem/BuildSystemFrontend.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/public-api/llbuild/buildsystem.h
- tests/Examples/buildsystem-capi.llbuild
- This adds llb_buildsystem_initialize() so that the initialize is clearly
separated from the build and to make it explicit the system can be reused for
multiple builds.
> [libllbuild] Add support for build system reuse.

- lib/BuildSystem/BuildSystemFrontend.cpp
Calling `cancel()` on already cancelled builds should be a nop. Also guard against the underlying `system` being deallocated.
> Increase cancellation robustness

- include/llbuild/Basic/FileSystem.h
- lib/Basic/FileSystem.cpp
- lib/BuildSystem/BuildSystem.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/public-api/llbuild/buildsystem.h
- tests/BuildSystem/Build/Inputs/get-file-permissions
- tests/BuildSystem/Build/mkdir.llbuild
- This also fixes a problem with the prior use of the LLVM APIs, which don't
properly delegate to the umask to set the permissions.
> [Basic] Introduce a FS method for creating directories.

- include/llbuild/Basic/FileSystem.h
- lib/Basic/FileSystem.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/ExternalCommand.cpp
- lib/BuildSystem/SwiftTools.cpp
- tests/BuildSystem/Build/output-dir-creation.llbuild
- Several callsites were left out of previous refactor to use the new
FileSystem interface, which meant we were only doing this sometimes. This
fixes all callsites to use the new interface, and also adds test coverage of
symlink needing to create directories recursively.
> [BuildSystem] Ensure we create directories recursively.

- include/llbuild/Core/BuildDB.h
- lib/Core/BuildEngine.cpp
- lib/Core/SQLiteBuildDB.cpp
- unittests/Core/BuildEngineTest.cpp
- unittests/Core/SQLiteBuildDBTest.cpp
Use exclusive locking for transactions when writing to the build database. Since we use a single transaction for the build, this effectively prohibits a second build from using the same database.
> <rdar://problem/25014088> [XCBuild] Cross process locking for shared build state files

- include/llbuild/Basic/PlatformUtility.h
- lib/Basic/FileSystem.cpp
- lib/Basic/PlatformUtility.cpp
Windows has no equivilent of `S_IRWXU | S_IRWXG |  S_IRWXO`
However, it exposes `_mkdir(1)` in` <direct.h>`: https://msdn.microsoft.com/en-us/library/2fkk4dzw.aspx
> Fix mkdir usage on Windows

- lib/BuildSystem/BuildSystem.cpp
- tests/BuildSystem/Build/directory-contents.llbuild
- unittests/BuildSystem/BuildSystemTaskTests.cpp
- Reapplied with a fix for the directory signature test to esnure that the
directory is actually modified (as reported by stat()) before the check which
requires that.
- This exposes some infragility in caching the directory contents, at least on
some systems (this test failed regularly on Ubuntu 16.05), but at least for
now we still rely on that ability for better or worse.
- <rdar://problem/30640443> Directory contents nodes are always
rebuilding
> [BuildSystem] Fix bug where directory contents were always recomputed.

- tests/BuildSystem/Build/mkdir.llbuild
- tests/lit.cfg
```
hughbe@DESKTOP-187M57Q:/mnt/c/Users/hughb/Documents/GitHub-WSL/build$ ninja test
[1/1] Running llbuild tests...
-- Testing: 146 tests, 4 threads --
Testing: 0 .. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90..
Testing Time: 21.24s
Expected Passes    : 138
Expected Failures  : 1
Unsupported Tests  : 7
```
https://github.com/Microsoft/BashOnWindows/issues/1801
> Add expected failures for mkdir.llbuild on WSL

- lib/Core/BuildEngine.cpp
- This was just an inefficient oversigh, the discovered dependencies should
always be appended to the result deps list.
- <rdar://problem/31537299> Discovered dependencies aren't in the appropriate order
> [Core] Insert discovered deps at the appropriate point.

- include/llbuild/Core/BuildDB.h
- lib/Core/SQLiteBuildDB.cpp
- tests/BuildSystem/Build/dep-scan-order.llbuild
- tests/Ninja/Build/tracing-scanning.ninja
- As currently modeled, the engine only scans dependencies in serial order
because we cannot yet handle the situation where a dependency has been
inferred to be out-of-date, but it isn't yet at the head of the queue of
things to actually begin to run in order to bring another node up-to-date.
- Given that, it is very important that we do the scanning of dependencies in
the order that they were declared, since there may be an implicit ordering
relationship between the impact of evaluating those nodes. See the test case
for an example (which also serves as a test case for the previous commit).
- <rdar://problem/31490515> Serial dependency scanning is out-of-order
> [Core] Ensure database maintains the relative order of dependencies.

- lib/BuildSystem/BuildFile.cpp
- tests/BuildSystem/Parser/errors.llbuild
- <rdar://problem/31215991> llbuild manifest containing two equal commands results in a crashes
> [BuildSystem] Diagnose duplicate command names.

- examples/c-api/buildsystem/main.c
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/Commands/BuildSystemCommand.cpp
- tests/Examples/buildsystem-capi.llbuild
- This frontend API shouldn't be responsible for synthesizing summary error
messages, individual clients can do that.
- <rdar://problem/31633275> Eliminate "build had N command failures" log message
> [BuildSystem] Lift errors out of frontend API.

- lib/BuildSystem/BuildSystem.cpp
- tests/BuildSystem/Build/multiple-outputs-error.llbuild
- <rdar://problem/31629500> Build doesn't abort after "unable to build node" error
> [BuildSystem] Ensure unproducable nodes cause the build to halt.

- include/llbuild/BuildSystem/BuildSystemFrontend.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/Commands/BuildSystemCommand.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/public-api/llbuild/buildsystem.h
- products/swift-build-tool/swift-build-tool.cpp
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
This allows the clients of llbuild to decide how to present cycle diagnostics instead of doing this internally. When using the llbuild CLI, the previous way of reporting cycles is retained.
> Make cycle information available to the client

- lib/BuildSystem/BuildSystemFrontend.cpp
I would like to do a rigorous study of this eventually, but for now the
following logic suggests we should default to numLanes == numCPUs:
1. We should *always* be willing to max out the CPU count if we have enough
work. As currently implemented, this means we must have numLanes >= numCPUs
(since we always block a lane once a subprocess is executing).
2. There will always be cache contention from having an overly loaded CPU ready
set. If we overcommit the CPUs, we are forcing the OS to deal with this load
in an unblocked build. The benefit we get from that is that the overcommitted
CPU can mean we recapture latency when one lane has no work.
3. However, we also have to worry about the Core engine which is executing
outside of the lanes. It is critical that it isn't starved, in order to …
> [BuildSystem] Don't overcommit CPUs in execution queue.

- include/llbuild/BuildSystem/BuildFile.h
- lib/BuildSystem/BuildSystem.cpp
- lib/Commands/BuildSystemCommand.cpp
- It is common to have many duplicated strings in a loaded build description
file (typically from command line arguments), so this patch optimizes the
memory use of the build description by interning these strings while loading.
- While we pay some cost for the interning itself, on the other hand this
allows avoiding what would otherwise be additional allocations in many cases,
so the interning ends up paying for itself while reducing memory footprint &
improving cache locality. On the balance my tests indicate this is a wash to
small improvement in terms of CPU use.
- <rdar://problem/32128433> Intern build description strings
> Intern build description strings.

- llbuild.xcodeproj/xcshareddata/xcschemes/llbuild.xcscheme
Seems like this is fallout from 41b66df0dc875cd2b530d25fb47a1fafe4dda40b, the scheme will be automatically changed to this after running the tests in Xcode.
> [Xcode] Update llbuild scheme.

- include/llbuild/Core/BuildDB.h
- include/llbuild/Core/BuildEngine.h
- lib/Core/BuildEngine.cpp
- lib/Core/SQLiteBuildDB.cpp
- unittests/Core/BuildEngineTest.cpp
- This changes the BuildEngine <-> DB interaction to rely on first getting a
unique (interned, effectively) ID for all keys.
- That change allows us to then change the BuildEngine-level result to store
dependencies in terms of key IDs, instead of expanded rules. This results in
dramatically reduced memory usage, but also since this matches the underlying
database schema it allows for much more efficient loading of the result
dependencies.
- In particular, this eliminates several joins from the database
implementation.
- There is potentially more we could do here to eliminate the ancillary key
table entirely and simply make the results themselves serve as the canonical
identifier for a rule, but that requires a little more work.
- This is good for a 35% speedup on null builds of large …
> Change DB API to find constant key IDs.

- docs/buildsystem.rst
- include/llbuild/Basic/FileSystem.h
- include/llbuild/Basic/PlatformUtility.h
- include/llbuild/BuildSystem/BuildValue.h
- lib/Basic/FileSystem.cpp
- lib/Basic/PlatformUtility.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildValue.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/public-api/llbuild/buildsystem.h
- tests/BuildSystem/Build/stale-file-removal.llbuild
- unittests/BuildSystem/BuildSystemTaskTests.cpp
- unittests/BuildSystem/BuildValueTest.cpp
Implement stale file removal and related tests.
Two things I'm not sure about:
- Should failures removing stale files actually fail the build or should they rather be warnings?
- Is it worth implementing a virtual `FileSystem` for the tests or is it good enough that we check for the error?
> <rdar://problem/30961839> Implement support for stale file removal

- lib/BuildSystem/BuildFile.cpp
- <rdar://problem/32179388> Crash with no root document
> [BuildSystem] Error if there is no root document.

- unittests/BuildSystem/BuildSystemTaskTests.cpp
> [BuildSystem] Disable cancelAllInQueue test pending investigation

- lib/BuildSystem/BuildSystem.cpp
- unittests/BuildSystem/BuildSystemTaskTests.cpp
Turns out that `std::set_difference` does not work with unordered sets, but this didn't become apparent with the smaller sets we are using in the unit tests.
> The elements in the ranges shall already be ordered according to this same criterion
> Use `set` instead of `unordered_set`

- unittests/BuildSystem/BuildSystemTaskTests.cpp
This one needed to be updated after changes to `MockBuildSystemDelegate`.
> Fix `BuildSystemTaskTests`

- lib/BuildSystem/ExternalCommand.cpp
I hit this when integrating with clients, not entirely sure why, but it seems correct, since directory tree signatures are also allowed here.
> Allow stale file removal build values

- include/llbuild/BuildSystem/BuildSystem.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- unittests/BuildSystem/BuildSystemTaskTests.cpp
- unittests/BuildSystem/MockBuildSystemDelegate.h
Commands can now report additional errors, notes and warnings, not tied to a command process as before. This is used by the `StaleFileRemoval` command to report deleted files and demotes all its errors to warnings.
See <https://github.com/apple/swift-llbuild/pull/147#discussion_r116107807>
> Add delegate support for command reporting

- include/llbuild/BuildSystem/BuildSystem.h
- lib/BuildSystem/BuildSystem.cpp
- unittests/BuildSystem/BuildSystemTaskTests.cpp
We were incrementing the pointer with the first `res.second++`, so the next part of the if statement would see the character after that.
> Fix the `isLocatedUnderRootPath` check

- include/llbuild/BuildSystem/BuildSystem.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/BuildSystem/ExternalCommand.cpp
- unittests/BuildSystem/BuildSystemTaskTests.cpp
- unittests/BuildSystem/MockBuildSystemDelegate.h
These are cherry-picked commits from `master` for stale file removal fixes we want to take for Swift 4.0.
The changes are from the following PRs: #158, #167, #169, #170 and #175.
> Stale file removal fixes for Swift 4.0

- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/public-api/llbuild/buildsystem.h
- products/libllbuild/public-api/llbuild/llbuild.h
This is a follow-up to #158 to add the newly added delegate methods to llbuild's C API.
> Add command reporting delegate methods to C API

- include/llbuild/BuildSystem/BuildExecutionQueue.h
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- The lower level shouldn't buffer the output, because clients might want to
see the streaming output from commands as soon as it comes over the pipe.
- <rdar://problem/32233420> llbuild shouldn't buffer subprocess output before sending to delegate
> [BuildSystem] Buffer command output at frontend level.

- lib/Basic/PlatformUtility.cpp
`_symlink` doesn't actually exist on Windows, so this fails compilation
Also, we need to pass a different flag for files vs directories
@neonichu
> Fix Windows implementation of symlink

- lib/Commands/NinjaBuildCommand.cpp
#98 refactors the common code between `NinjaBuildCommand.cpp` and `LaneBasedExecutionQueue.cpp` for creating, piping, waiting and killing processes.
The code in LaneBasedExecutionQueue is a bit more clean, and the ordering is different. I've extracted these changes from #98 as it is independent from #89 so won't cause merge conflicts. #98 needs a rethink in approach so might take some time. This is not affected
LaneBasedExecutionQueue has subtle differences such as using `llvm::SmallString` and counting both `SIGKILL` and `SIGINT` as cancellation signals
> Consolidate common code between NinjaBuildCommand.cpp and LaneBasedExecutionQueue.cpp

- lib/llvm/import-llvm
Windows requires certain files from LLVM that are unimported. Add them.
This meant updating the import-llvm python script to support the new inclusions and changes in the LLVM project layout.
I'm gonna start submitting some PRs soon that improve Windows support - e.g. fix uses of POSIX apis, fix the build system to support MSVC, and general porting goodness.
@ddunbar
> Update import-llvm to support Windows

- Xcode/Configs/Common.xcconfig
- llbuild.xcodeproj/project.pbxproj
- This isn't actually on, but it makes it easy to turn on via a simple change
to the xcconfig file.
> [Xcode] Add an easy way to enable code signing.

- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- lib/BuildSystem/POSIXEnvironment.h
- llbuild.xcodeproj/project.pbxproj
- tests/BuildSystem/Build/basic.llbuild
- unittests/BuildSystem/CMakeLists.txt
- unittests/BuildSystem/POSIXEnvironmentTest.cpp
[BuildSystem] Export LLBUILD_TASK_ID to subprocesses.
- This will eventually be used to propagate a unique ID which subprocesses can
use for reassociation, but for now it is just the lane ID to use for tracing
purposes.
- <rdar://problem/35179142> Pass LLBUILD_TASK_ID environment variable to Clang for tracing purposes
> Export LLBUILD_TASK_ID to subprocesses.

- lib/BuildSystem/BuildSystem.cpp
- lib/Core/BuildEngine.cpp
- This also renames the cancellation method to be more obvious about
when it is used.
- When task cancellation was done as part of an error handling path,
there was a potential race with any outstanding work being completed.
We solve this by forcing (engine-level) cancellation to wait for any
outstanding work before completing (to avoid needing to introduce
any additional synchronization logic).
- This is currently very improbable, since errors aren’t ever expected,
but that will change once we expose engine cancellation to clients.
> [Core] Fix a race condition in task cancellation.

- lib/Core/BuildEngine.cpp
[Core] Fix a corner case in cancellation logic.
- Cancellation was marking tasks as complete, which could result in subsequent
builds failing to update them.
- This basically never actually happens in practice, since that write only
effected the in-memory representation not what was persisted in the database,
and most significant clients do not yet rely on the in-memory representation.
> [Core] Fix a corner case in cancellation logic.

- lib/BuildSystem/BuildSystem.cpp
- tests/BuildSystem/Build/downstream-errors.llbuild
- When using phony commands to enforce ordering constraints, the cancelled
state would incorrectly propagate through the phony command, thus causing
unnecessary rebuilds of all downstream tasks. Instead, we
- A more fundamental solution to this problem will be to adopt support for
engine cancellation, and to ultimately allow individual commands to fail
without reporting a result value (and then triggering engine termination).
- <rdar://problem/35319783> Unnecessary rebuilds after an error
> [BuildSystem] Don't propagate cancel state through phony commands.

- lib/BuildSystem/BuildSystem.cpp
- This shouldn't normally be possible, since the command would have failed, but
it can happen in corner cases when trying to use a simulated filesystem.
- <rdar://problem/35403456> Crash in llbuild::buildsystem::BuildValue::makeExistingInput()
> [BuildSystem] Fix symlink output value if the output is ever missing.

- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- lib/Commands/NinjaBuildCommand.cpp
- SIGUNUSED is removed in newer versions of glibc.
- https://bugs.swift.org/browse/SR-6409
> [Linux] Use SIGSYS over SIGUNUSED.

- lib/Basic/ShellUtility.cpp
- lib/Ninja/ManifestLoader.cpp
- tests/Ninja/Loader/builds.ninja
- unittests/Basic/ShellUtilityTest.cpp
According to the Ninja Manual, the $in and $out variables should be shell-quoted (if needed) if they appear in the commands. See https://ninja-build.org/manual.html#ref_log.
> [Ninja] Shell-quote $in and $out

- include/llbuild/BuildSystem/BuildSystemFrontend.h
- products/libllbuild/BuildSystem-C-API.cpp
Pass calls to `BuildSystemFrontendDelegate::error()` on to the C API delegate via `handle_diagnostic`.
> <rdar://problem/34873210> When the new build system  fails with build system errors, they are not surfaced in the issue navigator

- include/llbuild/Core/BuildEngine.h
- perftests/Xcode/PerfTests/CorePerfTests.mm
- This also fixes a bug in the performance tests in which the engine *was*
being copied, which lead to a use after free.
- <rdar://problem/35571840> 3 test assertions in -[CorePerfTests testBuildEngineDependencyScanningOn2DMatrix]
> [Core] BuildEngine should not be copyable.

- include/llbuild/Core/BuildDB.h
- lib/Core/BuildEngine.cpp
- lib/Core/SQLiteBuildDB.cpp
- unittests/Core/BuildEngineTest.cpp
See <rdar://problem/33897555>
I don't have a good idea on how to test this as we would need to lock the database at exactly the right time to hit this. We have some existing tests for similar errors already, though, so I think this should be fine.
> Do not crash if we get any sqlite errors in getKeyID().

- tests/Ninja/Loader/builds.ninja
The correct check for the "depfile" line should only contain single quotes
around the variable portion. I.e., 'target12 foo'.d not 'target12 foo.d'. To
avoid future fragility, change the `CHECK-NOT` to an explicit `CHECK`.
Sorry for the noise!
> [tests/Ninja/Loader] Make shell-quote test more robust

- lib/BuildSystem/BuildSystem.cpp
- unittests/BuildSystem/BuildSystemTaskTests.cpp
- unittests/BuildSystem/MockBuildSystemDelegate.cpp
- unittests/BuildSystem/MockBuildSystemDelegate.h
Do not warn if a stale file has already been deleted.
This also changes the unit tests, so that they use a custom FS implementation which keeps track of deletion attempts, because we were relying on those warnings before for the test assertions.
See <rdar://problem/35913100>
> warning: cannot remove stale file '...': No such file or directory

- docs/buildsystem.rst
- include/llbuild/BuildSystem/BuildKey.h
- include/llbuild/BuildSystem/BuildNode.h
- include/llbuild/BuildSystem/BuildValue.h
- lib/BuildSystem/BuildKey.cpp
- lib/BuildSystem/BuildNode.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/ExternalCommand.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- tests/BuildSystem/Build/directory-tree-structure-signatures.llbuild
- This is like the existing node which tracks a directory (recursively), but it
only considers the structural elements of the directory (the files and their
modes).
> [BuildSystem] Add support for a directory structure tracking node.

- lib/BuildSystem/BuildSystem.cpp
- tests/BuildSystem/Build/directory-tree-structure-signatures.llbuild
- This wasn't properly restricting itself to ignoring the non-relevant mode
information on the scanning of the directory contents.
- <rdar://problem/36358682> llbuild reruns directory structure commands on file mutation
> [BuildSystem] Fix bug in directory structure node spuriously rebuilding.

- lib/BuildSystem/BuildSystem.cpp
- tests/BuildSystem/Build/missing-target.llbuild
<rdar://problem/31675430> swift-build-tool crashes when wrong target name is passed
> [BuildSystem] Validate target name before building it

- lib/Core/MakefileDepsParser.cpp
- unittests/Core/MakefileDepsParserTest.cpp
All of these are actually valid characters in filenames, so we should allow them to appear in `.d` files.
<rdar://problem/32670559> Failure building '=>.swift' (error reading dependency file: unexpected character in prerequisites)
> Fix parsing of some special characters in .d files

- CMakeLists.txt
- products/CMakeLists.txt
- products/llbuildSwift/CMakeLists.txt
In order to use llbuild's Swift API in SwiftPM, we need to build the
bindings as part of Swift's build script. This is the first step in that
direction.
> [Swift Bindings] Re-add CMake support for building Swift bindings.

- products/llbuildSwift/CMakeLists.txt
Including the x86_64-apple-macosx10.10 target causes a build failure on Linux. I added a guard around the line so it only gets included when building on an Apple (i.e. macOS) platform.
> Added guard so including macOS target is limited to an Apple platform

- include/llbuild/Basic/FileSystem.h
- lib/Basic/FileSystem.cpp
- llbuild.xcodeproj/xcshareddata/xcschemes/llbuild (external tests).xcscheme
- llbuild.xcodeproj/xcshareddata/xcschemes/llbuild.xcscheme
- unittests/Basic/FileSystemTest.cpp
Clears all device and inode numbers of FileInfo objects return by the
underlying FileSystem object.
> Add DeviceAgnosticFileSystem wrapper class

- include/llbuild/BuildSystem/BuildSystem.h
- include/llbuild/BuildSystem/BuildSystemCommandInterface.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/BuildSystem/ExternalCommand.cpp
- lib/BuildSystem/SwiftTools.cpp
- lib/Commands/BuildSystemCommand.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/swift-build-tool/main.cpp
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
- unittests/BuildSystem/BuildSystemTaskTests.cpp
- unittests/BuildSystem/MockBuildSystemDelegate.cpp
- unittests/BuildSystem/MockBuildSystemDelegate.h
This will allow a single place for file system configuration to be
applied (i.e. wrapping with a device/inode agnostic variant).
> Move ownership of the FileSystem into BuildSystem

- docs/buildsystem.rst
- lib/BuildSystem/BuildSystem.cpp
- tests/BuildSystem/Build/file-system-opts-errors.llbuild
- tests/BuildSystem/Build/file-system-opts.llbuild
Allows setting 'device-agnostic' file system in the build file
rdar://problem/37445150
> Add file-system client config attribute support

- lib/Core/BuildEngine.cpp
- tests/BuildSystem/Build/discovered-dependency-cycle.llbuild
Sort files which are less likely to be authored at the end, in order to find cycles based on authored files first
See <rdar://problem/37768597>
> Sort discovered dependency files

- cmake/modules/Utility.cmake
Looks like release mode is broken in the Swift support, we need to
re-land it with a proper fix.
> [CMake] Disable release mode for Swift

- CMakeLists.txt
This adds an option to enable assertions when building in release mode,
example invocation:
```
cmake -G Ninja -DCMAKE_BUILD_TYPE:=Release -DLLBUILD_ENABLE_ASSERTIONS:=YES ..
```
> [CMake] Add option to enable assertion in release mode

- Xcode/Configs/Version.xcconfig
- examples/c-api/buildsystem/main.c
- include/llbuild/BuildSystem/BuildExecutionQueue.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- include/llbuild/BuildSystem/CommandResult.h
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- llbuild.xcodeproj/project.pbxproj
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/libllbuild/include/llbuild/llbuild.h
- products/llbuildSwift/BuildSystemBindings.swift
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
- unittests/BuildSystem/LaneBasedExecutionQueueTest.cpp
- unittests/BuildSystem/MockBuildSystemDelegate.h
Collect user/system time and max RSS values for subprocesses and report
them via a new CommamdExtendedResults struct in the
commandProcessFinished callback.
rdar://problem/37889042
> Report extended results in commandProcessFinished

- llbuild.xcodeproj/project.pbxproj
Fix a typo in the output file declaration, add descriptive comment, and
have the script reference input/output file declarations directly.
> Cleanup up generate version.h build phase

- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/llbuildSwift/BuildSystemBindings.swift
Can someone help me understand how to build `llbuildSwift` with CMake? I know I can built `llbuildSwift` with SwiftPM, but it isn't working currently because of the recent changes to version.h
> Make Command::shouldShowStatus available in C and Swift

- CMakeLists.txt
- cmake/modules/Utility.cmake
As soon as this is merged, I have a PR ready against `swift`'s `build-script` to provide the correct `SWIFTC_EXECUTABLE` path.
> Support custom swiftc through cmake

- products/libllbuild/include/llbuild/version.h
- utils/generate-version-h.sh
The generate-version-h.sh script was writing a new version.h file (thus
updating the timestamp, thus triggering a change detection by the build
system) every time it was run, regardless of whether the content had
actually changed. Only update the file if doing so will actually change
the content, in order to make null builds actually work again.
> Prevent spurious rebuilds with SwiftPM builds of llbuild

- lib/Commands/CommandUtil.cpp
- lib/Commands/NinjaBuildCommand.cpp
- lib/Core/SQLiteBuildDB.cpp
- unittests/Core/SQLiteBuildDBTest.cpp
Inspired by https://github.com/apple/swift-llbuild/pull/255#discussion_r177496068 I went ahead and replaced existing uses, some of which I previously introduced unnoticed.
> Replace existing uses of `stringstream`

- lib/BuildSystem/BuildSystem.cpp
The path to compiler wasn't shell escaped and this lead to some output
on stderr if there was a space (or other unescaped char) in the Swift
compiler path. The printed output is relatively "harmless" and doesn't
actually contribute to a build failure.
- https://bugs.swift.org/browse/SR-7323
- <rdar://problem/39076084> [SR-7323]: SPM can't handle spaces in path to Xcode
> [BuildSystem] Shell escape Swift executable for version cmd

- llbuild.xcodeproj/project.pbxproj
llbuild uses LLVM coding conventions, so make it convenient to actually
edit the source code within Xcode. An attempt has been made to set tab
widths "intelligently" based on group contents in order to minimize the
resulting diff.
> Set tab width to 2 for C/C++ files in llbuild's Xcode project

- lib/Core/BuildEngine.cpp
- tests/BuildSystem/Build/discovered-compiler-deps.llbuild
- I forgot that we actually used the StringMap entry identity elsewhere, and we
had no unit test for this (fixed).
- This would cause the engine to crash when discovered dependencies were used
in an engine with no database attached.
- <rdar://problem/39148068> Crash when database is missing
> [Core] Fix a crash introduced by key ID cache.

- include/llbuild/BuildSystem/ExternalCommand.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/ExternalCommand.cpp
- tests/BuildSystem/Build/missing-inputs.llbuild
- tests/BuildSystem/Build/missing-node.llbuild
This should make it easier for users to see which missing inputs belong to which task.
See rdar://problem/35260583
Right now we log two messages:
- missing input ‘…’ and no rule to build it
- cannot build '...' due to missing input
This PR merges them into one:
- cannot build '...' due to missing inputs: ...
I am not entirely sure if this the implementation we want for this. Should we keep the early message that mentions the missing input in addition to adding it to the second error message? Should we fail the build early and put the merged message where the first one is currently?
> Merge "missing inputs" error messages

- include/llbuild/Core/BuildEngine.h
- lib/Core/BuildEngine.cpp
- llbuild.xcodeproj/project.pbxproj
- unittests/Core/BuildEngineCancellationTest.cpp
- unittests/Core/CMakeLists.txt
This PR moves llbuild to use a proper cancellation model that actually cancels outstanding tasks, versus simply causing them to return "cancelled" build results. This fixes some serious issues with cancellation causing unnecessary rebuilds.
> Improved build cancellation

- docs/buildsystem.rst
- include/llbuild/BuildSystem/BuildExecutionQueue.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- This adds support for a new field in the manifest which allows a client to
disable use of SIGINT when cancelling certain tasks.
- Some tools which run during a build, like `codesign`, can leave stray
temporary files which will inhibit correct operation on the next build. Since
the build system doesn't know about these files, it is useful to try and
avoid interrupting the tool in the hopes that it will finish before our
SIGKILL timeout expires and we force the tool to cancel.
- <rdar://problem/38773503> Support for not killing codesign with SIGINT (llbuild work)
> [BuildSystem] Support disabling SIGINT on cancellation.

- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/ExternalCommand.cpp
This switches applicable calls to `error()` over to the `commandHadError()` delegate method in order to provide more contextual information about errors to clients.
rdar://problem/39126321
> llbuild error/warning delegate method should include the build key

- include/llbuild/BuildSystem/BuildValue.h
Although doing this is technically legal, as the C++ Standard states: "The effect of dereferencing a pointer returned as a request for zero size is undefined."
So it's not very useful. And the static analyzer doesn't like it anyways. So always allocate at least one byte and null-terminate the entire thing. I specifically didn't just set p/contents to nullptr if size == 0 because that would simply introduce a different analyzer warning.
> Fix static analyzer warnings about zero-allocations

- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- On Apple platforms, we want to default everything to running in the "utility"
QOS class.
- <rdar://problem/24986348> [llbuild] Set QOS on spawned tasks
> [BuildSystem] Set QOS on launched processes.

- include/llbuild/Basic/BinaryCoding.h
- include/llbuild/Core/BuildDB.h
- lib/Core/BuildDB.cpp
- lib/Core/BuildEngine.cpp
- lib/Core/SQLiteBuildDB.cpp
- unittests/Core/BuildEngineTest.cpp
- Separate database key IDs from engine keys to reduce database queries
while holding the engine key table lock
- Add support for directly accessing the byte array of BinaryEncoding
> Refactor Engine/DB Key/KeyID handling

- CMakeLists.txt
- products/libllbuild/CMakeLists.txt
CMake cache variables need to be changed manually in CMakeCache.txt,
which is annoying at best. Instead, default to LIB_SUFFIX, which is
commonly used in many other projects and in Linux packaging macros.
> Adhere to CMake LIB_SUFFIX if set

- include/llbuild/Core/BuildDB.h
- lib/Core/SQLiteBuildDB.cpp
- This yields a 75% increase in performance for testPseudoLLVMNullBuild
rdar://problem/39697555
> Add a cache for DB <-> Engine key ID mapping in the db layer

- lib/Core/SQLiteBuildDB.cpp
- llbuild.xcodeproj/project.pbxproj
This does not seem to make much of a performance improvement for the perf tests (~1-2% reduction), but may help more real world situations.  Maximizes our chances of caching IDs and simplifies the query code for storing results.
> Refactor setRuleResult to use cache and update with single query

- docs/buildsystem.rst
The documentation was not clear on how directory tree "structure" nodes
differed from normal directory tree nodes.
> Further explain what is-directory-structure does

- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- This turns out to have a pretty substantial impact on some build scenarios,
so I am going to reland this but exposed as an API so that clients can try to
choose more intelligently what class is appropriate.
- <rdar://problem/39825229> llbuild should use default QOS class for subprocess, by default
> [BuildSystem] Disable defaulting to UTILITY QOS for tasks.

- lib/BuildSystem/BuildSystem.cpp
- This turned out to not be completely safe yet... reveritng for now.
This reverts commit 265448e02eed33b9e92b006bc1d29800430de58d.
> Revert "[BuildSystem] Enable fast cancellation."

- products/llbuildSwift/BuildSystemBindings.swift
- products/llbuildSwift/CMakeLists.txt
To support building the Swift bindings on Linux, `BuildSystemBindings.swift` had to updated to use `stat.st_mtim` on Linux as `stat.s.st_mtimespec` is not available, and CMake was modified to use custom foundation and dispatch libraries on Linux (for building through CI).
> Support swift bindings on Linux

- docs/buildsystem.rst
- lib/BuildSystem/BuildSystem.cpp
- tests/BuildSystem/Build/changed-output-agnostic-commands.llbuild
Instead of adding a domain-specific "args-for-signature" property, we
instead now have "additional-signature-data" which allows to add
arbitrary string data that will contribute to the task signature, and
ignore-args-in-signature, that will allow to remove existing args data
from the task signature. This is a more flexible design and also allows
us to ADD arbitrary data to the signature as well.
> <rdar://35326105> Rethink the args-for-signature manifest property

- include/llbuild/BuildSystem/BuildSystem.h
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- tests/BuildSystem/Build/missing-inputs.llbuild
- Add methods for changing the scheduler algorithm. Supports:
-- commandNamePriority: priority queue ordered by command name [default]
-- fifo: first in/first out queue - previous behavior
- Add methods for setting the lane width of the scheduler
- Add command line option for llbuild debug tool for selecting the scheduler
> Add support for configuring the build system scheduler

- include/llbuild/Basic/CrossPlatformCompatibility.h
- include/llbuild/BuildSystem/CommandResult.h
- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- lib/Commands/NinjaBuildCommand.cpp
- llbuild.xcodeproj/project.pbxproj
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/llbuildSwift/BuildSystemBindings.swift
The command extended result struct contains information about the spawned subprocesses. It should also contain the process identifier of the spawned child process.
I chose to take int32 as the type and use -1 for the case that the process creation has failed.
rdar://39798231
> Added process identifier to command_extended_result

- CMakeLists.txt
- Xcode/Configs/Common.xcconfig
- lib/llvm/Support/Path.cpp
- lib/llvm/Support/YAMLParser.cpp
- lib/llvm/Support/raw_ostream.cpp
- Explicitly not used in llvmSupport, which has intentional use of
implicit fallthrough
> Add -Wimplicit-fallthrough to most C++ targets

- tests/BuildSystem/Build/phony.llbuild
This test is sensitive to scheduler ordering due to the way
lit/FileCheck tests work. This changes the test back to using the
fifo scheduler for greater consistency in CI (same was done for the
missing-inputs.llbuild test previously)
rdar://problem/40387374
> Fix flaky phony.llbuild test

- lib/BuildSystem/BuildSystem.cpp
- unittests/BuildSystem/BuildSystemTaskTests.cpp
In situations where a node was previously a missing input, that fact may
be recorded in the build database. If subsequent builds add a rule that
may now produce that node, the system could get into a situation such
that 'missing input' errors are triggered even though we can
successfully build it. This changes produced nodes to cause their rule
to be built.
rdar://problem/40376404
> [BuildSystem] Produced nodes should build when prior value was missing

- include/llbuild/Basic/Tracing.h
- include/llbuild/BuildSystem/BuildDescription.h
- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- lib/Core/BuildEngine.cpp
This commit introduces the usage of os_signpost and os_log to implement tracing in llbuild. os_signpost is part of macOS 10.14 and gives the ability to add more and structured information to tracing intervals.
We adopt this in llbuild to get a better understanding about the build system if tracing as a feature has been enabled. If tracing is disabled this should result in no-ops to not influence the performance of the system.
rdar://problem/40310911
> [Tracing] Introduce os_signpost/os_log

- include/llbuild/Basic/Tracing.h
llbuild is a generic low level build system and should therefore not be specific about any clients.
> Use a better fitting name for the log subsystem

- include/llbuild/Basic/BinaryCoding.h
- include/llbuild/Basic/StringList.h
- include/llbuild/BuildSystem/BuildKey.h
- include/llbuild/BuildSystem/BuildNode.h
- include/llbuild/BuildSystem/BuildValue.h
- lib/BuildSystem/BuildKey.cpp
- lib/BuildSystem/BuildNode.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/Core/BuildEngineTrace.cpp
- llbuild.xcodeproj/project.pbxproj
- products/libllbuild/BuildSystem-C-API.cpp
- tests/BuildSystem/Build/directory-contents-filtered-produced.llbuild
- tests/BuildSystem/Build/directory-contents-filtered.llbuild
- unittests/BuildSystem/BuildSystemTaskTests.cpp
- Moves BuildValue string list into a reusable data structure 
- Adds support for 'content-exclusion-patterns' in the manifest for directory nodes
- Filters exclude items from consideration when calculating directory signatures
- Implements generic binary coding support for BuildKeys
> [BuildSystem] Add support for content exclusion patterns

- lib/BuildSystem/BuildSystem.cpp
- lib/Core/MakefileDepsParser.cpp
- unittests/Core/MakefileDepsParserTest.cpp
Filenames may contain ':'. The deps file 'format' does minimal escaping,
thus may contain such characters unescaped past the rule name. Fix this
by continuing lexing for colons in post rule paths.
rdar://problem/40827063
> [Core] Fix MakeFileDepsParser handling of filenames with ':'

- lib/BuildSystem/BuildSystem.cpp
This PR causes tasks to execute in the wrong order under certain
circumstances. Revert the offending code until we have a proper fix.
> <rdar://41142590> Temporarily revert part of PR #320

- llbuild.xcodeproj/project.pbxproj
This is necessary in order for them to find the C API headers, in order to be able to run the unit tests from the Xcode project.
> [UnitTests] Add the libllbuild header search path to the new target for C API unit tests

- llbuild.xcodeproj/project.pbxproj
- products/libllbuild/BuildSystem-C-API.cpp
- unittests/CAPI/BuildSystem-C-API.cpp
- unittests/CAPI/CMakeLists.txt
Adds support for specifying a dependency-info-style discovered-dependencies file in a `deps` attribute on external C API commands.  This allows external commands to emit discovered-dependency information in the same way that shell commands can.
This also adds the first unit test for the BuildSystem C API.
In a future enhancement it would be useful to extend the C API to let the external command add discovered dependencies directly, without having to go through a separate file.
> [BuildSystem] Add discovered-dependencies-file support to CAPIExternalCommand

- lib/BuildSystem/BuildSystem.cpp
- tests/SwiftBuildTool/swift-compiler.swift-build
<rdar://problem/40178238> llbuild should not pass -num-threads to swiftc for non-wmo invocations
> [BuildSystem] Don't pass -num-threads for non-wmo invocations

- lib/BuildSystem/BuildSystemFrontend.cpp
Otherwise we may get a rather cryptic "unable to enable tracing" error.
> Create directory hierarchy before attempting to write trace file

- include/llbuild/BuildSystem/BuildDescription.h
- lib/BuildSystem/LaneBasedExecutionQueue.cpp
llvm::SmallString's str() method returns an llvm::StringRef, which does
not copy the string data. When getShortDescription/getVerboseDescription
return, the SmallString is deallocated and the underlying memory freed,
causing the returned StringRef to be pointing to deallocated memory.
Remove these functions and require the caller to provide their own
string data instance, which the Command can then populate with data.
> Fix use-after-free in some helper methods

- lib/BuildSystem/BuildSystem.cpp
- tests/BuildSystem/Build/directory-contents-filtered.llbuild
- tests/BuildSystem/Build/directory-contents-ordering.llbuild
- tests/BuildSystem/Build/directory-contents.llbuild
Reverting directory contents behavior broke tests expecting the new
behavior. This change adds a test that directly exposes the bug that was
fixed in #328, and fixes the tests that were XFAIL'd in #329. It also
adds commentary explaining the problem in BuildSystem.cpp, as the
full solution is non-trivial.
rdar://problem/41182818
> [BuildSystem] Fix tests and comments due to #328 and #329

- Xcode/Configs/Common.xcconfig
- include/llbuild/Basic/StringList.h
- Also, enable -Wall in Xcode so that this warning is triggered there
> Fix initializer order warning

- tests/BuildSystem/Build/directory-contents.llbuild
The second modification test failed in internal CI. The likely
explanation I can think of is that the system must still be HFS, thus
two close together touch commands did not alter the stat info. Change to
a file content change instead.
rdar://problem/41352819
> Alter directory-contents test to be more reliable in CI

- llbuild.xcodeproj/project.pbxproj
- llbuild.xcodeproj/xcshareddata/xcschemes/llbuild.xcscheme
Downstream swift clients may now use the bindings in the framework
directly, thus do not need to rely on build system trickery to set the
version information.
> [Xcode] Stop shipping Version.xcconfig with the framework

- cmake/modules/Utility.cmake
- products/llbuildSwift/CMakeLists.txt
Needed for the https://github.com/apple/swift/pull/17829 PR so that we don't install headers in the toolchain.
> Don’t install headers for llbuildSwift

- cmake/modules/Utility.cmake
- products/llbuildSwift/CMakeLists.txt
libllbuildSwift only contains the Swift bindings, so we need to install
libllbuild as well. It would be nice if libllbuildSwift contained the
entire thing but this should be ok as well.
> Install libllbuild next to libllbuildSwift

- cmake/modules/Utility.cmake
- products/llbuildSwift/CMakeLists.txt
Reverts apple/swift-llbuild#344
This broke for some reason:
https://ci.swift.org/job/swift-PR-Linux-smoke-test/8139/console
```
18:55:46 -- Install configuration: "Release"
18:55:46 CMake Error at cmake_install.cmake:36 (file):
18:55:46   file INSTALL cannot find
18:55:46   "/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/llbuild-linux-x86_64/./lib/libllbuildSwift.so;/home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/llbuild-linux-x86_64/./lib/libllbuild.so".
18:55:46 Call Stack (most recent call first):
18:55:46   /home/buildnode/jenkins/workspace/swift-PR-Linux-smoke-test/branch-master/buildbot_linux/llbuild-linux-x86_64/products/cmake_install.cmake:40 (include)
18:55:46 …
```
> Revert "Install libllbuild next to libllbuildSwift"

- products/llbuildSwift/CoreBindings.swift
This is rarely actually needed.
> [llbuildSwift] Add default value for forceChange

- products/llbuildSwift/BuildSystemBindings.swift
This is necessary for the SwiftPM PR to use the llbuild library for building: https://github.com/apple/swift-package-manager/pull/1537
> Add a build overload to Swift bindings for targets

- lib/BuildSystem/BuildSystem.cpp
- tests/SwiftBuildTool/swift-compiler.swift-build
This is important for performing correct builds when there are two source files
with the same name in a Swift target.
<rdar://problem/41060279> Nest all swift auxiliary files similar to the object files
> [BuildSystem] Move Swift compiler's aux files next to the object file

- products/llbuildSwift/BuildSystemBindings.swift
Making it available through CustomDebugStringConvertible’s debugDescription
> Make a command’s verbose description available

- lib/Core/SQLiteBuildDB.cpp
This adds a timeout for sqlite to wait before giving up because the
database is already busy. This happens if you have 2 concurrent builds
happening at once. Previously it would error out immediately, now it
will wait for up to 20 seconds before erroring out.
> [Core] Set a busy timeout on the database

- utils/unittest/googletest/src/gtest-all.cc
- utils/unittest/googletest/src/gtest-death-test.cc
- utils/unittest/googletest/src/gtest-port.cc
- utils/unittest/googletest/src/gtest-test-part.cc
- utils/unittest/googletest/src/gtest.cc
- This eliminates the reliance on custom include paths.
> [gtest] Simplify include structure for gtest.

- include/llvm/Support/COFF.h
- include/llvm/Support/Debug.h
This avoids the conflict between the DEBUG macro added by SwiftPM and
the other "DEBUG" define in the file.
> [llvmSupport] Undefine the DEBUG macro added by SwiftPM

- include/llbuild/BuildSystem/BuildKey.h
- include/llbuild/BuildSystem/BuildNode.h
- include/llbuild/BuildSystem/BuildValue.h
- lib/BuildSystem/BuildKey.cpp
- lib/BuildSystem/BuildNode.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/BuildSystem/BuildValue.cpp
- lib/BuildSystem/ExternalCommand.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- tests/BuildSystem/Build/directory-contents-filtered-produced.llbuild
- tests/BuildSystem/Build/directory-contents-filtered.llbuild
- unittests/BuildSystem/BuildSystemTaskTests.cpp
This change moves filtered directory support into a parallel tree of
nodes. It also introduces a new 'stat' node that produces the stat
information for a file system object.  The combination of these changes
allows filtered directories to work as intended, depending upon the
filter contents only, and not the stat info of the containing directory.
Supports rdar://problem/30640904
> [BuildSystem] Split out filtered directory nodes

- README.md
- docs/buildsystem.rst
- include/llbuild/Basic/Tracing.h
- include/llbuild/BuildSystem/BuildDescription.h
- include/llbuild/BuildSystem/BuildExecutionQueue.h
- include/llbuild/BuildSystem/CommandResult.h
- include/llbuild/BuildSystem/ExternalCommand.h
- include/llvm/ADT/Optional.h
- lib/BuildSystem/BuildExecutionQueue.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/ExternalCommand.cpp
- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- lib/Commands/BuildSystemCommand.cpp
- llbuild.xcodeproj/xcshareddata/xcschemes/BuildSystemTests.xcscheme
- llbuild.xcodeproj/xcshareddata/xcschemes/llbuild.xcscheme
- products/libllbuild/BuildSystem-C-API.cpp
- tests/BuildSystem/Build/basic.llbuild
- tests/BuildSystem/Build/command-dependencies.llbuild
- tests/BuildSystem/Build/file-system-opts.llbuild
- tests/BuildSystem/Build/lane-release.llbuild
- tests/BuildSystem/Build/missing-inputs.llbuild
- tests/Examples/buildsystem-capi.llbuild
- unittests/BuildSystem/LaneBasedExecutionQueueTest.cpp
The general approach here is that LaneBasedExecutionQueue::executeProcess()
exposes a pipe file descriptor to the launched process. If that process
sends the value of LLBUILD_TASK_ID over that pipe, the process will
release the lane on which it is executing and asynchronously wait for
completion.
This initial implementation spawns a new thread for each process that
triggers the release. Longer term, more sophisticated handling of async
IO and process wait may be preferred.
Since any process may opt in to use this functionality, the chain of
methods that lead into the executeProcess call have all been modified
to take completion/result reporting callbacks.
rdar://problem/44683736
> [BuildSystem] Allow processes to release lanes

- cmake/modules/FindFileCheck.cmake
- include/llbuild/Basic/Tracing.h
- llbuild.xcodeproj/project.pbxproj
- utils/build-and-test
- utils/check-all
- utils/docker/Dockerfile-14.04
- utils/docker/Dockerfile-16.04
- utils/docker/Dockerfile-18.04
- utils/docker/docker-utils
Expands docker-utils image support to all three Ubuntu versions on which
Swift is built. Adds a check-all script that uses docker to build and
test llbuild in all supported images.
> [Utils] Expand docker images, add check-all

- products/libllbuild/Core-C-API.cpp
- products/libllbuild/include/llbuild/core.h
- products/libllbuild/include/llbuild/llbuild.h
- products/llbuildSwift/CoreBindings.swift
Add a destroy_context callback to the C API's task delegate, which, like the build engine's delegate, is called from the destructor. Add the appropriate implementation in the Swift core bindings to release the TaskWrapper associated with the C API's task delegate so it no longer leaks.
> [llbuildSwift] Fix TaskWrapper Memory Leak

- lib/Basic/Subprocess.cpp
When a complete control message arrives in one read, the poll loop
early exits. As such, lane release may not happen until a subsequent
read occurs on the console pipe. Move the check out of the loop so that
we properly release after the current reads have been finished.
> [Basic] Move control release check outside poll loop

- lib/BuildSystem/BuildSystem.cpp
I'm not really sure how to construct a test for this, but I think it makes sense to handle failed inputs here. The current behaviour is a runtime assertion if failed inputs are encountered by `DirectoryContentsTask`.
> Handle failed inputs in `DirectoryContentsTask`

- products/llbuildSwift/BuildSystemBindings.swift
This reverts commit 3b7df215161607ecf9dddda9322654edfc6b4a1b.
- This is causing crashes in llbuild when used in some cases, so we apparently
have some missing test coverage. Will further investigate to find the actual
bug...
> Revert "Avoid escaping array-to-pointer conversions"

- products/llbuildSwift/CMakeLists.txt
The build layout for the CMake based build of Foundation is slightly different
(and more uniform with XCTest and libdispatch).  This updates the search paths
to allow us to switch to the CMake based build of Foundation.
> build: update for the Foundation CMake based build layout

- include/llbuild/Basic/ExecutionQueue.h
- include/llbuild/Basic/Subprocess.h
- lib/Basic/ExecutionQueue.cpp
- lib/Basic/LaneBasedExecutionQueue.cpp
- lib/Basic/Subprocess.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/Commands/NinjaBuildCommand.cpp
- perftests/Xcode/PerfTests/BuildSystemPerfTests.mm
- tests/BuildSystem/Build/working-directory.llbuild
- unittests/Basic/LaneBasedExecutionQueueTest.cpp
This currently is limited to Darwin platforms, as it is implemented via a
non-portable pthread API.
rdar://problem/39941219
> [BuildSystem] Add support for setting external process working directory

- products/libllbuild/include/llbuild/buildsystem.h
- products/libllbuild/include/llbuild/core.h
- products/libllbuild/include/llbuild/llbuild.h
- products/llbuildSwift/BuildSystemBindings.swift
- products/llbuildSwift/CoreBindings.swift
This obviates the need to duplicate every llbuild enum in the Swift
bindings, where we may forget to update the mapping. It also provides
the Swift compiler with a real enumeration instead of a series of
integers, which allows it to emit diagnostics in cases where a switch
does not cover all enum cases, for example.
rdar://problem/46476230
> Use Clang attributes to import llbuild enumerations more nicely in Swift

- lib/BuildSystem/BuildSystem.cpp
- tests/SwiftBuildTool/swift-compiler-whole-module-optimization.swift-build
- tests/SwiftBuildTool/swift-compiler.swift-build
Fix the tense in the Swift compilation tool description. A SwiftPM PR needs to be merged first or this change will break it: https://github.com/apple/swift-package-manager/pull/1877
> Rename Compile to Compiling to fix the tense

- include/llbuild/Basic/PlatformUtility.h
- lib/Basic/PlatformUtility.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/Commands/NinjaBuildCommand.cpp
- Adds raiseOpenFileLimit to PlatformUtility
- Raises open file limit before constructing execution queue in
BuildSystem
- Raises open file limit at the start of Ninja builds
rdar://problem/46823730
> Raise open file limit before building

- lib/BuildSystem/BuildSystem.cpp
- tests/BuildSystem/Build/discovered-makefile-deps-relative.llbuild
Under some situations clang will emit relative paths for included
dependencies. This changes 'shell' commands that use makefile-style
deps files to attempt to make dependecy paths absolute before generating
the node key.
rdar://problem/44463222
> [BuildSystem] Handle relative paths in 'shell' makefile-style dependencies

- include/llbuild/Basic/Subprocess.h
- lib/Basic/Subprocess.cpp
- lib/BuildSystem/BuildSystem.cpp
[Glibc 2.29](https://sourceware.org/git/?p=glibc.git;a=commit;h=4a938cb273e164a475dc123cc80ea6354d7248d4) will add posix_spawn_file_actions_addchdir_np. A method with
the same signature also exists on [Solaris](https://docs.oracle.com/cd/E86824_01/html/E54766/posix-spawn-file-actions-addchdir-np-3c.html), and there is currently a
[proposal](http://austingroupbugs.net/view.php?id=1208) to add a "posix_spawn_file_actions_addchdir" to POSIX, so
proactively re-structure the code to prefer using a
posix_spawn_file_actions_addchdir[_np] style function to set the working
directory.
We fall back to an alternate mechanism where available, or continue to
assert as before.
rdar://46069443
> Add support for setting the working directory of tasks on Linux

- products/llbuildSwift/BuildSystemBindings.swift
- products/llbuildSwift/CoreBindings.swift
Resolves a FIX to use a real hash function.
> Reimplement Hashable with hash(into:)

- Package.swift
- products/libllbuild/include/module.modulemap
This allows us to use the latest build settings API for linking the
required libraries.
> Update manifest version to 5.0

- tests/Ninja/Build/nonexistent-subdir.ninja
This is an attempt to add a test for [SR-9735](https://bugs.swift.org/browse/SR-9735), until the bug is fixed it is supposed to fail with llbuild but succeed with the "real" Ninja.
I could not figure out how to actually run these tests so I just tried to deduce how to write these tests by looking at the existing tests.
> [tests] Add ninja test that outputs to nonexistent subdir

- utils/Xcode/create-lit-site-cfg.sh
...by falling back to adding the default Homebrew install path as a
search path. Xcode won't see /usr/local/bin when added to PATH via
.profile.
> Make it a little easier to find FileCheck via Homebrew

- products/llbuildSwift/BuildSystemBindings.swift
Fixes the deprecation warning and this change is source compatible with Swift 4.2
> [llbuildSwift] Replace hashValue with hash(into:)

- docs/buildsystem.rst
- include/llbuild/Basic/PlatformUtility.h
- lib/Basic/FileSystem.cpp
- lib/Basic/PlatformUtility.cpp
- lib/Basic/Subprocess.cpp
- lib/BuildSystem/BuildSystem.cpp
- unittests/Basic/FileSystemTest.cpp
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
- unittests/BuildSystem/BuildSystemTaskTests.cpp
- unittests/BuildSystem/TempDir.cpp
- unittests/CAPI/BuildSystem-C-API.cpp
Reverts apple/swift-llbuild#422
Broke Swift-CI:
`
11:08:12 /usr/bin/clang++    -I/home/buildnode/jenkins/workspace/oss-swift-5.0-incremental-RA-linux-ubuntu-14_04-long-test/llbuild/include -std=c++14 -fno-rtti -fno-exceptions -Wmost -Wdocumentation  -Woverloaded-virtual -Wparentheses -Wswitch -Wunused-function -Wunused-variable -Wunused-value -Wempty-body -Wuninitialized -Wconstant-conversion -Wint-conversion -Wbool-conversion -Wenum-conversion -Wsign-compare -Wnewline-eof -Wdeprecated-declarations -Winvalid-offsetof -Wnon-virtual-dtor -Wimplicit-fallthrough -fPIC -include "/home/buildnode/jenkins/workspace/oss-swift-5.0-incremental-RA-linux-ubuntu-14_04-long-test/llbuild/include/libstdc++14-workaround.h" -Wdocumentation -Wimplicit-fallthrough -Wunreachable-code -Woverloaded-virtual -O3 …
> Revert "Fixed the Unit Tests on Windows"

- examples/c-api/buildsystem/main.c
- lib/Basic/Subprocess.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- tests/Examples/buildsystem-capi.llbuild
- unittests/CAPI/BuildSystem-C-API.cpp
Freeing across modules [can cause issues in Windows](https://docs.microsoft.com/en-us/cpp/c-runtime-library/potential-errors-passing-crt-objects-across-dll-boundaries?view=vs-2017) which llbuild currently does when [getting file contents](https://github.com/apple/swift-llbuild/blob/master/products/libllbuild/include/llbuild/buildsystem.h#L260) using a delegate. This adds a fs_free field which can be used to call the correct free in the library.
However, [there's a comment](https://github.com/apple/swift-llbuild/blob/master/products/libllbuild/include/llbuild/buildsystem.h#L272):   
```
// FIXME: Design clean data types for clients to return unowned/unowned
// memory.
```
which seems like a better idea than adding the fs_free field which would be highly prone to error. Are there existing …
> Handling Memory Across the API Boundary

- products/libllbuild/CMakeLists.txt
- tests/Examples/buildsystem-capi.llbuild
- tests/lit.cfg
Cl by default produces .pdb and .ilk files by simply substituting the
extension of the desired target. This produces conflicts between the
debug files for llbuild.exe and llbuild.dll. This changes llbuild.dll to
be libllbuild.dll to avoid the problem.
> Rename llbuild.dll to libllbuild.dll on Windows

- lib/Basic/ShellUtility.cpp
- lib/Basic/Subprocess.cpp
- unittests/Basic/ShellUtilityTest.cpp
- CreateProcessW Command args _should_ include the executable name as
argv[0]
- cmd doesn't know what single quotes are, use double quotes instead on
Windows
> Fix some process spawning issues on Windows

- lib/Basic/Subprocess.cpp
Previously, the naive command line construction failed if an argument
contained a space.
Now that the hard work is done, this is an easy fix!
> Properly Form the Command string on Windows

- lib/Core/MakefileDepsParser.cpp
The deps lexer didn't consider '\r' a non word character, so it would
look for a file "filename.txt\r" on Windows and fail to find it.
> Handle Carriage Return in MakeFileDepsParser

- tests/SwiftBuildTool/changed-commands.swift-build
- tests/SwiftBuildTool/dependencies.swift-build
- tests/SwiftBuildTool/swift-compiler-whole-module-optimization.swift-build
- tests/SwiftBuildTool/swift-compiler.swift-build
- tests/SwiftBuildTool/swift-version.swift-build
Windows doesn't do shebangs and working around this is pretty messy for
really not a lot of gain. (See also
https://github.com/apple/swift-llbuild/pull/434 for alternatively fixing
them.)
> Disable SwiftBuildTool tests on Windows

- lib/Core/SQLiteBuildDB.cpp
Some (error) paths in `SQLiteBuildDB.cpp` failed to finalize temporary statements, possibly causing leaks if the resultant errors were handled gracefully further up the stack (i.e. by not quitting immediately). Seemed like a potential issue that'd be easy to clear up—in case some future changes don't treat the resulting errors as fatal (since that doesn't seem to be delineated anywhere).
> Add some missing sqlite3_finalize() statements.

- lib/Commands/BuildSystemCommand.cpp
Linux and macOS differ in what they consider uint64_t to be (%lu vs.
%llu, respectively).
> [Commands] Fix printf formatting warning

- include/llbuild/BuildSystem/BuildDescription.h
- include/llbuild/BuildSystem/BuildNode.h
- include/llbuild/BuildSystem/BuildValue.h
- include/llbuild/BuildSystem/ExternalCommand.h
- include/llbuild/BuildSystem/ShellCommand.h
- include/llbuild/Core/BuildEngine.h
- lib/BuildSystem/BuildDescription.cpp
- lib/BuildSystem/BuildNode.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildValue.cpp
- lib/BuildSystem/ExternalCommand.cpp
- lib/BuildSystem/ShellCommand.cpp
- lib/Commands/BuildEngineCommand.cpp
- lib/Commands/NinjaBuildCommand.cpp
- lib/Core/BuildEngine.cpp
- lib/Core/BuildEngineTrace.cpp
- lib/Core/BuildEngineTrace.h
- lib/Core/SQLiteBuildDB.cpp
- perftests/Xcode/PerfTests/CorePerfTests.mm
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/Core-C-API.cpp
- tests/BuildSystem/Build/missing-command-rule.llbuild
- tests/BuildSystem/Build/now-produced-rule.llbuild
- unittests/BuildSystem/BuildValueTest.cpp
- unittests/Core/BuildEngineCancellationTest.cpp
- unittests/Core/BuildEngineTest.cpp
- unittests/Core/DepsBuildEngineTest.cpp
Promotes signatures to a first class feature of rules in the engine and
db. Signatures are supplied during rule construction and validated
against the last signature used to build the prior result during
scanning.
Command signatures have been moved out of the build value and into rule
signatures. Nodes now make use of signatures as track changes in the
build graph.
rdar://problem/48578317
> [BuildSystem] Track and validate rule signatures

- products/libllbuild/include/llbuild/buildsystem.h
Importing non lean and mean Windows.h conflicts with the lean and mean
Windows imported by (Core)Foundation
> Use Windows Lean and Mean

- tests/BuildSystem/Build/missing-command-rule.llbuild
- tests/BuildSystem/Build/now-produced-rule.llbuild
'touch' can be insufficient to change stat info on low resolution file
systems.
rdar://problem/48946422
> [tests] Make tests less dependent on fs time resolution

- lib/Core/MakefileDepsParser.cpp
Consider colons followed by a slash as part of a path rather than as a
word separator.
> Handle : in FileNames on Windows Makefiles

- include/llbuild/Basic/POSIXEnvironment.h
- lib/Basic/Subprocess.cpp
- tests/BuildSystem/Build/basic.llbuild
- tests/BuildSystem/Build/file-system-opts.llbuild
- tests/BuildSystem/Build/no-control-fd-tool-level.llbuild
- tests/BuildSystem/Build/no-control-fd.llbuild
- tests/lit.cfg
- unittests/Basic/POSIXEnvironmentTest.cpp
- Properly set up the environment on Windows
- Fix tests which invoke `/usr/bin/env`
- Properly set up the thread array when using WFMO
> Windows: Pass the Environment to Subprocesses

- docs/buildsystem-extensions.md
- include/llbuild/BuildSystem/BuildSystemCommandInterface.h
- include/llbuild/BuildSystem/BuildSystemExtensions.h
- include/llbuild/BuildSystem/BuildSystemHandlers.h
- include/llbuild/BuildSystem/ShellCommand.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/ShellCommand.cpp
- llbuild.xcodeproj/project.pbxproj
- This is more efficient, while also allowing extensions to easily tie their
lifetime to the lifetime of the build.
- This also allows the buildsystem to avoid a lock on the common lookup path.
> [plugins] Allocate shell handlers once per build.

- lib/BuildSystem/BuildSystem.cpp
Unlike UNIX systems, Windows does not have an archiver.  Traditionally,
this role has been fulfilled by `link`.  Since we already need `clang`
and `LLVM`, let us just switch to `llvm-ar` which can support BSD style
archives (Darwin), GNU style archives (Linux), and SysV archives
(Windows).
> BuildSystem: use `llvm-ar` rather than `ar`

- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
Re-enable use of engine support for fast cancellation. This time,
updating BuildSystemFrontend to mark the build as unsuccessful when
cancelled.
rdar://problem/31792710
> [BuildSystem] Enable fast cancellation

- include/llvm/Support/Error.h
- lib/Basic/Subprocess.cpp
- lib/Ninja/Manifest.cpp
- lib/llvm/Demangle/MicrosoftDemangle.cpp
- lib/llvm/Support/APFloat.cpp
- lib/llvm/Support/Mutex.cpp
- llbuild.xcodeproj/project.pbxproj
This does not attempt to address all of the warnings, as we really want
to just import llvm's support code.  However, we also want to quell the
bots' ire.
rdar://problem/48374266
> [llvm] Fix or silence analyzer warnings

- lib/Commands/NinjaCommand.cpp
- perftests/Xcode/PerfTests/BuildSystemPerfTests.mm
Spawning processes with a working directory may leave the thread working
directory set.  Clean up by resetting it to the process level working
dir.
rdar://problem/48978131
> [perftests] Clean up after testSupprocessSpawnWorkingDirectory

- Package@swift-4.2.swift
This updates the manifest to tools version 5 so we can use the new API
for setting linker flags. There is also a version-specific manifest for
older Swift 4.2 clients.
> Update manifest to tools version 5

- products/llbuildSwift/CMakeLists.txt
Moving CoreFoundation into the root is needed to actually get the proper
dependency tracking for Foundation builds. This adjusts the use of it
in llbuild.
> build: adjust for new build layout

- include/llbuild/Basic/ShellUtility.h
- lib/Basic/ShellUtility.cpp
- lib/Basic/Subprocess.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/ShellCommand.cpp
- tests/BuildSystem/Build/windows-shell-parsing.llbuild
If the comments are too much/over the top, I can remove/reduce them. They were mostly there for my own benefit, but I left them in because exactly what it's doing is a bit cryptic otherwise.
> Do Proper Shell Escaping on Windows

- lib/BuildSystem/BuildSystem.cpp
`ArchiveShellCommand::getVerboseDescription()` had wasn't correctly using the `bool first` variable it created. It was set to `true`,  but the loop only ever checked if it was `false` and, if so, it would insert a space and set it to false. Since it never was false, the verbose description would never contain spaces between arguments.
This change makes this code do what I imagine was the intent: insert a space _before_ all arguments except the first.
> Fix ArchiveShellCommand's verbose description output.

- CMakeLists.txt
- cmake/modules/Utility.cmake
- products/llbuildSwift/CMakeLists.txt
- utils/write-swift-version
Reverts apple/swift-llbuild#453
Version check is failing to catch changes in Swift-CI, thus not rebuilding the module and causing import failures in SPM.  See apple/swift#24079
> Revert "build: adjust for Windows"

- products/libllbuild/BuildSystem-C-API.cpp
Very simple change to respect `schedulerLanes` when using the C API.
> Respect schedulerLanes when using the C API.

- CMakeLists.txt
- lib/Basic/CMakeLists.txt
- lib/BuildSystem/CMakeLists.txt
- lib/Commands/CMakeLists.txt
- lib/Core/CMakeLists.txt
- lib/Ninja/CMakeLists.txt
- lib/llvm/Demangle/CMakeLists.txt
- lib/llvm/Support/CMakeLists.txt
- utils/unittest/CMakeLists.txt
- utils/unittest/UnitTestMain/CMakeLists.txt
- Explicitly list out the libraries to link the target against
- Explicitly declare that we're linking static
This allows us to set BUILD_SHARED_LIBS to build shared swift libraries for Windows.
> Explicitly declare static linking dependencies

- include/llbuild/Core/BuildDB.h
- lib/Commands/BuildSystemCommand.cpp
- lib/Core/BuildEngine.cpp
KeyID used in the methods for BuildDBDelegates should be const.
> Made KeyID usages in BuildDBDelegate const

- lib/Core/SQLiteBuildDB.cpp
Used the correct number of expected columns for those SQL statements.
> Fixed assertion checks in SQLiteBuildDB

- lib/Basic/Subprocess.cpp
Availability macros are not properly guarding use on 10.14 hosts.
rdar://problem/51793107
> Revert macOS posix_spawn_fileaction_chdir_np() adoption

- unittests/CAPI/CMakeLists.txt
This fixes building CAPITests on Windows.  Unlike Unix, Windows does not
permit undefined references to symbols at link time.  Add the missing
link dependencies to ensure that we can resolve all symbols.  This
permits building CAPITests on Windows.
> build: add missing dependencies

- products/libllbuild/include/module.modulemap
This workaround was to force clients to link against the libraries.
This is no longer required.  Removing these enables building libllbuild
on Windows where ncurses is not available.
> build: remove a hack which is no longer needed

- CMakeLists.txt
Swift-CI broke with these changes.  Seems the verison check is not being
re-run after the initial configure step.
rdar://problem/52198587
> Revert swift version changes

- lib/BuildSystem/BuildSystem.cpp
- unittests/BuildSystem/BuildSystemTaskTests.cpp
Under some cancellation conditions, the directory value observed by
DirectoryContentsTask may be a SkippedCommand. Prior to this change, the
provideInput() handler was assuming that such values had output info and
would read a garbage value and crash (in release mode).
rdar://problem/50380532
> Handle SkippedCommand values in DirectoryContents

- lib/BuildSystem/BuildSystem.cpp
- unittests/BuildSystem/BuildSystemTaskTests.cpp
Under some cancellation conditions, the directory value observed by
DirectoryContentsTask may be a SkippedCommand. Prior to this change, the
provideInput() handler was assuming that such values had output info and
would read a garbage value and crash (in release mode).
rdar://problem/50380532
> Cherry-pick 'Handle SkippedCommand values in DirectoryContents'

- include/llbuild/Core/BuildDB.h
- lib/BuildSystem/BuildSystem.cpp
- lib/Commands/BuildSystemCommand.cpp
- lib/Commands/NinjaBuildCommand.cpp
- lib/Core/BuildEngine.cpp
- lib/Core/SQLiteBuildDB.cpp
- llbuild.xcodeproj/project.pbxproj
- products/libllbuild/BuildDB-C-API.cpp
- products/libllbuild/Core-C-API.cpp
- products/libllbuild/include/llbuild/db.h
- products/libllbuild/include/llbuild/llbuild.h
- unittests/Core/BuildEngineTest.cpp
- unittests/Core/DepsBuildEngineTest.cpp
- unittests/Core/SQLiteBuildDBTest.cpp
Those are the changes related to the C interface of the previously open PR [here](https://github.com/apple/swift-llbuild/pull/484).
It will be used to build a Swift interface on top in a different PR.
rdar://50298712
> Basic C interface for build database

- Package.swift
- docs/development.rst
- llbuild.xcodeproj/project.pbxproj
- llbuild.xcodeproj/xcshareddata/xcschemes/llbuild.xcscheme
- products/llbuildSwift/CoreBindings.swift
- unittests/Swift/BuildSystemBindingsTests.swift
- unittests/Swift/Info.plist
- utils/build-and-test
This adds a unit test target to the Xcode project and the Swift package.
It can be used for unit tests of the Swift layer and contains some basic
tests of the Swift interface already.
rdar://52447946
I added some rudimentary tests for the Swift interface and want to use that target to write tests for the Swift interface of the build database (instead of having an example target).
**Question**: Should we add `swift test` to the `utils/build-and-test` script?
> Added unit test target for Swift layer

- lib/llvm/Support/Debug.cpp
- lib/llvm/Support/Signals.cpp
- This library injects static constructors which are unsuitable for use in
library code, and in particular are causing the CAPI unit tests to fail at
runtime (because of multiple definitions).
- <rdar://problem/52894543> llbuild CAPI tests aren't running (the google test binary fails with LLVM command line errors)
> [LLVM] Disable use of LLVM's CommandLine library in shared code.

- llbuild.xcodeproj/project.pbxproj
- products/libllbuild/BuildDB-C-API.cpp
- products/llbuildSwift/BuildDBBindings.swift
- products/llbuildSwift/BuildSystemBindings.swift
- unittests/Swift/BuildDBBindingsTests.swift
This adds a Swift interface to build on top of the added C interface.
It is not used at the moment but can be used for data fetching about builds that ran before.
rdar://50298712
> Created Swift interface for build database

- unittests/BuildSystem/BuildSystemTaskTests.cpp
This was failing to compile on Windows for some reason:
```
[1/2] Building CXX object unittests\BuildSystem\CMakeFiles\BuildSystemTests.dir\BuildSystemTaskTests.cpp.obj
FAILED: unittests/BuildSystem/CMakeFiles/BuildSystemTests.dir/BuildSystemTaskTests.cpp.obj
C:\PROGRA~2\MICROS~1\2019\COMMUN~1\VC\Tools\MSVC\1421~1.277\bin\Hostx64\x64\cl.exe  /nologo /TP  -IZ:\llbuild\include -IZ:\llbuild\utils\unittest\googletest\include -IS:\sqlite-amalgamation-3270200 /DWIN32 /D_WINDOWS /W3 /GR /EHsc -DLLVM_ON_WIN32 /MD /Zi /O2 /Ob1 /DNDEBUG   -wd4068 -wd4141 -wd4146 -wd4244 -wd4267 -wd4291 -wd4800 -wd4996 -std:c++14 /showIncludes /Founittests\BuildSystem\CMakeFiles\BuildSystemTests.dir\BuildSystemTaskTests.cpp.obj /Fdunittests\BuildSystem\CMakeFiles\BuildSystemTests.dir\ /FS -c …
```
> [Windows] Fix a compilation error

- CMakeLists.txt
- utils/write-swift-version
This is more portable than a bash script.
> [Windows] Use Python for computing Swift compiler version

- docs/buildsystem.rst
- lib/BuildSystem/BuildSystem.cpp
- tests/SwiftBuildTool/Inputs/pseudo-swiftc
- tests/SwiftBuildTool/swift-shared-library.swift-build
Added a tool to link and produce .dll/.so outputs.
I'm planning on using this in SwiftPM for linking Windows Swift code since Windows Swift currently doesn't support static linking. It currently works for that purpose and produces .dlls and import libs on Windows which I've used to (partially) compile SwiftPM.
> Add Shared Library Tool

- lib/Core/BuildEngine.cpp
If a failure occurs updating the build DB during finished task
processing, we trigger synchronous cancellation of the build. This
currently triggers a deadlock, waiting for the task that failed to be
marked as finished. This change prevents that deadlock by decrementing
the outstanding task count prior to such cancellation.
rdar://problem/50203529
> [BuildEngine] Fix potential deadlock during cancel

- lib/Basic/LaneBasedExecutionQueue.cpp
- Various testing seems to indicate the relative cost of burning backgrounds
threads isn't that high, it seems safe to go somewhat higher. We do still put
a max cap on things, though.
> [Basic] Increase background task max.

- include/llbuild/Basic/Clock.h
- include/llbuild/Core/BuildDB.h
- include/llbuild/Core/BuildEngine.h
- lib/BuildSystem/ExternalCommand.cpp
- lib/Core/BuildEngine.cpp
- lib/Core/SQLiteBuildDB.cpp
- llbuild.xcodeproj/project.pbxproj
- unittests/Core/BuildEngineTest.cpp
- unittests/Core/SQLiteBuildDBTest.cpp
- unittests/Swift/BuildDBBindingsTests.swift
This renames existing timestamp properties and functions to epoch
to better differentiate between the new timestamp types.
A new Clock class gives access to static methods for getting global
timestamps in s.
The timing information is stored in the SQLite database in the rule
results table. That defines a new schema version.
rdar://52892354
> Added timing information to the build database

- include/llbuild/Basic/Clock.h
The API returns the rounded number in the requested unit. Requesting seconds as double still returns the rounded number casted to a double.
To get more accurate information, we'll request a smaller unit - microseconds - and calculate that back to seconds before returning.
rdar://54207984
> Ask for microseconds and calculate seconds

- CMakeLists.txt
- cmake/modules/Utility.cmake
- products/libllbuild/CMakeLists.txt
- products/llbuild/CMakeLists.txt
- products/llbuildSwift/CMakeLists.txt
- tests/Examples/buildsystem-capi.llbuild
- tests/lit.cfg
- Properly link against msvcrt by not overriding the /MD in
CMAKE_CXX_FLAGS_RELWITHDEBINFO
- Rename libllbuild.lib back to llbuild.lib
- Rename libllbuildSwift.lib back to llbuildSwift.lib
- Disable incremental linking so llbuild.ilk's don't conflict
> Fix Build Warnings on Windows

- products/llbuildSwift/BuildKey.swift
CAPIRulesVector's only purpose is to provide a C friendly interface to its vector. The llb_build_key_t ** interface does move the responsibility of destroying the keys after usage but the class does destroy them itself in its destructor.
This change removes the destructor and adds a comment about the usage of the data() getter.
rdar://54298130
> Make CAPIRulesVector move the repsonsibility of destroying keys

- products/llbuildSwift/BuildKey.swift
The state of having a weak pointer in BuildKey was previously added but the check before destroying wasn't included.
rdar://54298130
I don't know how that slipped through, that's the essential part of the change in https://github.com/apple/swift-llbuild/pull/522.
> Don't destroy a weak pointer

- lib/Basic/Subprocess.cpp
Adjust the reported error to use the first string in the command line.
This is needed to ensure that we use the correct value on Windows.  THis
allows the Windows build to get further.
> Basic: adjust the reported subprocess id

- products/libllbuild/BuildValue-C-API.cpp
Windows does not support VLAs.  The current pattern would fail to build
with a failure to construct the local array as the size was not
constant.  Switch to a reserved vector which avoids the growth but
ensures that we can allocate a variable sized array.  This repairs the
Windows build.
> libllbuild: make build succeed on Windows x86_64

- products/llbuildSwift/CMakeLists.txt
The output name of `libllbuild` is `llbuild` which causes the install to
fail on Windows due to an `-ENOENT`.  Adjust the rules accordingly.
> libllbuildSwift: repair install rules for Windows

- products/libllbuild/CMakeLists.txt
Install libllbuild as part of the llbuild build at a second location on
non-Windows targets: `lib/swift/pm/llbuild`.  This is needed for the
proper execution on Linux platforms.
> build: re-install libllbuild.so on Linux

- CMakeLists.txt
- cmake/modules/Utility.cmake
The processor count is used by the Swift build function.  Locate it near
it.  This will eventually go away as CMake 3.15 supports Swift
natively.
> build: sink processor checks into Utility

- lib/Basic/CMakeLists.txt
This corrects the link dependencies for Windows.  llbuildBasic is always
built as a static library.  This requires that the dependencies be
linked PUBLIC so that users of the library are able to have the
dependencies fulfilled.  llbuild now properly links in ShLwApi (the
dependency was previously silently fulfilled by the implicitly linked
libraries from CMake).
> Basic: correct dependencies for linking on Windows

- products/libllbuild/include/llbuild/llbuild.h
The Windows build requires more careful handling of the exports macro.
WHen building the library as a static library, no dll storage should be
specified.  When building the library dynamic, DLL storage must be
applied.  This corrects the exported interfaces from the executable
(`llbuild`) exporting the interfaces for `libllbuild`.  Unix would
prevent the exporting of the symbols as `-rdynamic` is not the default.
> libllbuild: fix definition of `LLBUILD_EXPORT`

- products/llbuildSwift/BuildDBBindings.swift
- products/llbuildSwift/BuildKey.swift
- products/llbuildSwift/BuildValue.swift
- products/llbuildSwift/Internals.swift
Xcode 10 ships with Swift 5.0 and doesn't know about implicit return or using Self in class context. The changes before required people to use Xcode 11 which isn't the officially released version.
I think we can revert this commit eventually to switch back using the cool 5.1 features once there's an official version available.
> Create compatibility to Xcode 10

- products/libllbuild/BuildDB-C-API.cpp
- products/llbuildSwift/BuildDBBindings.swift
- unittests/Swift/BuildDBBindingsTests.swift
Make RuleResult conform to Equatable.
Destroy owned build keys when destroying rule result.
rdar://50298961
This is some independent pre-work done for https://github.com/apple/swift-llbuild/pull/525
> Add convenience initializer for RuleResult

- products/llbuildSwift/BuildDBBindings.swift
Just as it says, I recall seeing a similar fix a couple of days ago 🤷🏻‍♂️
> Add missing `return` for compat with Swift 5.0

- include/llbuild/Basic/PlatformUtility.h
- lib/Basic/Subprocess.cpp
clang objects to the ordered comparison between `HANDLE` and `int`.
Provide a trait based validation check for the FD.  Windows
traditionally uses `INVALID_HANDLE_VALUE` to indicate an invalid handle.
> Basic: correct fd check as identified by clang

- Package.swift
- include/llbuild/Basic/Tracing.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- include/llvm/Config/config.h
- lib/Basic/Subprocess.cpp
- llbuild.podspec
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/libllbuild/include/llbuild/llbuild.h
- products/llbuildSwift/BuildDBBindings.swift
- products/llbuildSwift/BuildKey.swift
- products/llbuildSwift/BuildSystemBindings.swift
- products/llbuildSwift/BuildValue.swift
- products/llbuildSwift/Internals.swift
- utils/push-podspec
This PR makes small adjustments so that swift-llbuild can be embedded in iOS applications and other projects targeting Apple systems.
Changes:
* Add a dylib-only target, because currently, that's the only way to make Xcode link the library dynamically.
* Add missing import.
* Invert several platform conditionals so that they're targeting all Apple systems and not only `#if os(macOS)`.
* Add minimum versions to `Package.swift`.
> Allow building iOS + CocoaPods

- include/llbuild/Core/BuildDB.h
- lib/Core/SQLiteBuildDB.cpp
- products/libllbuild/BuildDB-C-API.cpp
- products/libllbuild/BuildKey-C-API-Private.h
- products/libllbuild/BuildKey-C-API.cpp
- products/libllbuild/include/llbuild/buildkey.h
- products/libllbuild/include/llbuild/db.h
- products/llbuildSwift/BuildDBBindings.swift
- products/llbuildSwift/BuildKey.swift
- products/llbuildSwift/BuildValue.swift
- unittests/Core/BuildEngineTest.cpp
- unittests/Swift/BuildDBBindingsTests.swift
Add new method to build database to fetch all keys *and* results.
- makes fetching of all results much faster
Change ownership model of build keys.
- all that are handed out by the database are owned by the database
- manually constructed are owned by the creator (BuildKey.swift)
Move equal and hash implementation to C++ layer
- makes use of new unique identifier which gets provided by the build database (if owned by it)
rdar://54701714
> Make huge performance improvements in build database Swift layer

- CMakeLists.txt
xcrun doesn't exist on non Darwin, so we should skip the execute_process
that calls it on non Darwin.
> Avoid xcrun Call on Non Darwin

- Xcode/Configs/Common.xcconfig
- perftests/Xcode/PerfTests/BinaryCodingPerfTests.mm
- products/libllbuild/BuildDB-C-API.cpp
The warning for sign compare is already turned on in CMake but not in the Xcode configuration.
That way a comparison with a signed and unsigned number slipped through which is fixed as well.
> Add warning for sign-compare when building in Xcode

- include/llbuild/Basic/ExecutionQueue.h
- include/llvm/Config/config.h
- lib/Basic/ExecutionQueue.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/ShellCommand.cpp
- lib/Commands/NinjaBuildCommand.cpp
- tests/BuildSystem/Build/exit-status.llbuild
- tests/Ninja/Build/cycle-detection.ninja
- tests/Ninja/Build/exit-status.ninja
- tests/Ninja/Build/inherited-file-descriptors.ninja
- tests/Ninja/Build/missing-inputs.ninja
- tests/Ninja/Build/targets-tool.ninja
- tests/lit.cfg
- unittests/Basic/LaneBasedExecutionQueueTest.cpp
Using this pull and a couple other small tweaks ([like this one](https://github.com/termux/termux-packages/blob/master/packages/llbuild/lib-Basic-PlatformUtility.cpp.patch)), I got all but one of the tests (BuildSystemCAPI.CustomToolWithDiscoveredDependencies) to pass when building llbuild and running it natively on Android in [the Termux app](https://github.com/termux/termux-app).
Abstracting out the shell path is particularly useful on Android as the system shell is in /system/bin/sh and the local shell at /data/data/com.termux/files/usr/bin/sh, so setting the path in only two places like this makes it much easier to patch.
> Abstract out default shell path and add Android LLVM config

- lib/Core/SQLiteBuildDB.cpp
- unittests/Core/SQLiteBuildDBTest.cpp
Without finalizing the sqlite database doesn't get closed accordingly.
rdar://55274300
> Finalize all sql statements when database gets closed

- lib/Core/SQLiteBuildDB.cpp
This otherwise triggers a warning of an unused variable that gets written to.
rdar://55447092
> Use local variable if we're building without asserts

- include/llbuild/Ninja/Manifest.h
- include/llbuild/Ninja/ManifestLoader.h
- lib/Commands/NinjaBuildCommand.cpp
- lib/Commands/NinjaCommand.cpp
- lib/Ninja/Manifest.cpp
- lib/Ninja/ManifestLoader.cpp
- tests/Ninja/Build/absolute-dependencies.ninja
- tests/Ninja/Build/cycle-detection.ninja
- tests/Ninja/Build/graphviz-output.ninja
- tests/Ninja/Build/tracing-scanning.ninja
- tests/Ninja/Build/tracing.ninja
The `clang` generates either absolute or relative dependencies (in `.d` files) depending on its flags. This makes `llbuild ninja build` miss dependencies sometimes since from `llbuild ninja`'s standpoint the relative path name is different from absolute (this matches OS `ninja` behavior).
This patch resolves this edge case by absolutizing the node names (dependencies and rules).
An unfortunate consequence of this patch is that the debug output from the `llbuild ninja build` tool may sometimes differ: the absolute pathnames could be displayed instead of relative ones.
rdar://55235219
> Absolutize node names

- lib/Commands/NinjaCommand.cpp
- tests/Ninja/Loader/dependency-format.ninja
* Fix `order-only` dependency printout. Should be `||`, was `|`.
> Fix load-manifest dependency printout

- products/llbuildSwift/CMakeLists.txt
Stage the path structure to match the output of Foundation's results
after the migration to 3.15.1.  This is migration work, with the
canonical layout changing over to this layout.  This will be cleaned up
in a subsequent PR.
> build: prepare for Foundation conversion to CMake 3.15

- lib/Commands/NinjaBuildCommand.cpp
- tests/Ninja/Build/t-clean.ninja
There's a belief that it is quite hard (if not impossible) to make a _correct_ `-t clean` simulation. The next best thing to at least avoid breaking scripts that request `ninja -t clean` is to remove the build database. That's what we do in this patch.
rdar://20224847
> Simulate ninja -t clean by removing the database.

- include/llbuild/Basic/BinaryCoding.h
- products/libllbuild/BuildDB-C-API.cpp
- products/libllbuild/BuildKey-C-API.cpp
- products/libllbuild/include/llbuild/db.h
* Remove superfluous const qualifier warning.
* Almost allows running with `-W -Wall -Werror` error-free.
> Remove "'const' type qualifier on return type has no effect" warning (-W, -Wall)

- tests/Ninja/Build/absolute-dependencies.ninja
- tests/Ninja/Build/modify-retaining-timestamp.ninja
- tests/Ninja/Build/order-only-skip.ninja
- tests/Ninja/Build/rebuild-manifest.ninja
1. Linux might have 1-ms FS object timestamp resolution which is not enough
if we're checking the timestamps too quickly.
2. macOS with HFS has 1-second FS timestamp resolution, yielding the same problems.
rdar://23239574
rdar://56090104
> Fix timestamp-related non-determinism on old FSs

- tests/Ninja/Build/order-only-skip.ninja
* Problem: the CI tests running on HFS or (some) Linux FSs would fail.
* Reason: The logic for fixing FS timestamp resolution sensitivity in PR #579 was wrong for the type of test performed.
* This re-fixes the time sensitivity fix for the timestamp resolution problem, although the test is no longer run on Linux due to differences in tooling available.
> Fix sensitivity to FS timestamp resolution

- lib/Commands/NinjaBuildCommand.cpp
* Just silences the warning which pops up in Xcode.
> Fix xcode warning about use of a potentially uninitialized variable

- CMakeLists.txt
This value is entirely under the control of the user.  Use
`add_compile_options` with generator expressions to apply custom flags
to the build.
> build: avoid modifying `CMAKE_CXX_FLAGS`

- tests/CMakeLists.txt
* Tests are invoked by `ninja test`, skipping the default build. The `adjust-times` utility has to be a dependency of the test target.
> Add adjust-times as a test target dependency

- include/llbuild/Basic/ExecutionQueue.h
- include/llbuild/Basic/Subprocess.h
- lib/Basic/ExecutionQueue.cpp
- lib/Basic/LaneBasedExecutionQueue.cpp
- lib/Basic/Subprocess.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/ShellCommand.cpp
- lib/Commands/NinjaBuildCommand.cpp
- tests/Ninja/Build/console-pool-input.ninja
- tests/Ninja/Build/console-pool.ninja
- unittests/Basic/LaneBasedExecutionQueueTest.cpp
* Console pools allow to serialize jobs and connect jobs directly to console input and output.
* The right solution is to create stackable queues with independently controlled parralelism, as well as reimplementation of the executor queue on top of one of them by pipmpl or subclassing. This PR implements the quick solution.
rdar://47093734
> Implement console pool semantics

- lib/Ninja/Manifest.cpp
Absolute paths on Windows do not begin with a leading slash. Defer to
llvm's is_absolute instead which handles cross platform paths.
> Fix Path Normalization on Windows

- include/llbuild/Basic/PlatformUtility.h
- lib/Basic/Subprocess.cpp
* Leak of the output pipe file descriptors if control pipe can't be opened.
* Leak of posix file actions memory if the control pipes can't be created.
* Descriptors leak of unrelated tasks into spawned task (linux, win).
* Windows code improperly inheriting the control file descriptors.
* Windows code not checking results of the system calls.
* A race condition in the control channel parsing on windows resulting in  a potential double-close() (which can close someone else's handle).
rdar://56800263
> Streamline file descriptor handling during spawning

- tests/Ninja/Build/max-commands-progress.ninja
* The test flakiness was likely related to FS timestamp resolution.
rdar://23089862
> Re-enable max-commands-progress

- CMakeLists.txt
This adjusts the application of the flags to just the C++ parts of the code,
enabling moving to CMake 3.15.
> build: limit clang flags to C++ (NFC)

- llbuild.xcodeproj/project.pbxproj
- tests/Ninja/Build/absolute-dependencies.ninja
- tests/Ninja/Build/max-commands-progress.ninja
- tests/Ninja/Build/order-only-skip.ninja
- utils/adjust-times/CMakeLists.txt
- utils/adjust-times/adjust-times.cpp
From @gmittert (https://github.com/apple/swift-llbuild/pull/594)
Switch out getopt for llvm's Commandline API which is cross platform,
and define various constants which aren't normally defined on Windows.
This allows the Windows build to compile again.
> Port adjust-times to Windows

- lib/Basic/Version.cpp
- lib/Commands/NinjaBuildCommand.cpp
* Bump up versions exposed by `llbuild --version` and `llbuild ninja build --version` to coincide with the Swift releases.
* rdar://57024160
> Bump up exposed versions

- cmake/modules/Utility.cmake
This was used for the parallel compilation of Swift code which has since
been migrated to CMake.  Remove the vestigial code to clean up the
module.
> build: clean up some vestigial support code (NFC)

- CMakeLists.txt
The evaluation of CMAKE_OSX_SYSROOT needs to be done very early,
otherwise CMake will not adjust its variable to consider the SDK
correctly and may pick up headers in incorrect locations.
Addresses rdar://problem/57300418
> [build] move evaluation of CMAKE_OSX_SYSROOT

- products/llbuildSwift/CMakeLists.txt
Linking against libraries from the system was broken on Windows with
CMake 3.15.  It would require explicitly adding the `-l` prefix which is
less than ideal.  This workaround allows building without a dispatch or
Foundation build tree available for Windows.
> build: add another workaround for CMake <3.16

- CMakeLists.txt
The import library is being emitted into the wrong location on CMake
3.15.1.  Add a workaround to enable use of LLBuild for building s-p-m on
Windows.
> build: add a workaround for CMake <3.16 on Windows

- products/llbuildSwift/CMakeLists.txt
This is so that export targets can work properly for
swift-package-manager.  llbuildSwift should bring along the include
paths to libllbuild which it exposes.
> build: llbuildSwift requires libllbuild

- bindings/python/llbuild.py
- include/llbuild/Core/BuildEngine.h
- lib/BuildSystem/BuildSystem.cpp
- lib/Commands/BuildEngineCommand.cpp
- lib/Commands/NinjaBuildCommand.cpp
- lib/Core/BuildEngine.cpp
- perftests/Xcode/PerfTests/CorePerfTests.mm
- products/libllbuild/Core-C-API.cpp
- products/libllbuild/include/llbuild/core.h
- products/llbuildSwift/CoreBindings.swift
- unittests/Core/BuildEngineCancellationTest.cpp
- unittests/Core/BuildEngineTest.cpp
- unittests/Core/DepsBuildEngineTest.cpp
Removes registerTask() method, takes ownership directly during the
rule action call.
> [Core] Simplify task registration

- include/llbuild/Core/BuildEngine.h
- lib/BuildSystem/BuildSystem.cpp
- lib/Commands/BuildEngineCommand.cpp
- lib/Commands/NinjaBuildCommand.cpp
- lib/Core/BuildEngine.cpp
- llbuild.xcodeproj/project.pbxproj
- perftests/Xcode/PerfTests/CorePerfTests.mm
- products/libllbuild/Core-C-API.cpp
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
- unittests/Core/BuildEngineCancellationTest.cpp
- unittests/Core/BuildEngineTest.cpp
- unittests/Core/DepsBuildEngineTest.cpp
In this change, BuildSystem, et al. still use std::function objects.
However, this change lays the foundation for eliminating those.
> Refactor Rule to be a virtual base class

- lib/Basic/PlatformUtility.cpp
- tests/BuildSystem/Build/dep-scan-order.llbuild
- tests/lit.cfg
Used to build and test llbuild and SPM natively on Android in [the Termux app](https://termux.com/). I can modify lit.cfg to only check the `PREFIX` env var on Android if there's any worry that it might be spuriously set on other platforms.
`makeTmpDir` is only checked by the unit tests, which I noticed are not run by the CI anymore, maybe because those llbuild test binaries were moved around? I see the following warning on both the linux and mac CI for recent pulls:
```
lit.py: /home/buildnode/jenkins/workspace/swift-llbuild-PR-Linux-smoke-test/llvm-project/llvm/utils/lit/lit/discovery.py:210: warning: test suite 'llbuild-unit' contained no tests
```
Running them manually shows that no tests fail after this pull on Android.
> Fix remaining tests for Android

- products/llbuild-analyze/Sources/CriticalPathTool.swift
- products/llbuild-analyze/Sources/GraphViz.swift
This changes the `critical-path` to to include more meaningful information in the vertices instead of just the BuildKey ID from the database.
It also adds the option to only include the critical build path or the entire graph.
https://bugs.swift.org/browse/SR-11730
> SR-11730 Improved GraphViz output

- lib/Core/BuildEngine.cpp
- unittests/Core/BuildEngineTest.cpp
Duplicate rule registration could trigger nullptr dereference now that
rules are passed as unique_ptr.
rdar://problem/58566350
> [Core] Fix potential nullptr dereference in addRule

- include/llbuild/BuildSystem/BuildKey.h
- include/llbuild/Core/BuildEngine.h
- lib/Commands/BuildEngineCommand.cpp
- lib/Commands/BuildSystemCommand.cpp
- lib/Commands/NinjaBuildCommand.cpp
- lib/Core/BuildEngine.cpp
- lib/Core/BuildEngineTrace.cpp
- products/libllbuild/BuildDB-C-API.cpp
- products/libllbuild/BuildKey-C-API-Private.h
- products/libllbuild/BuildKey-C-API.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/Core-C-API.cpp
- unittests/Core/BuildEngineTest.cpp
- unittests/Core/DepsBuildEngineTest.cpp
Key remains a std::string under the covers, but clients must now be
explicit when they wish to use it as such.
> [Core] Refactor key into an encapsulated type

- include/llbuild/Basic/Tracing.h
- lib/Basic/Tracing.cpp
TracingEnabled was not thread safe. Though not intended to be toggled
from multiple threads, this should appease the sanitizer.
rdar://problem/58939168
> Fix tracing TSAN warning

- llbuild.xcodeproj/project.pbxproj
The adjust-times target was setting different levels of warnings, thus
triggering unexpected variation from the rest of the project.
rdar://problem/57171721&57171722&57171723
> Unify adjust-times warnings with top level

- examples/c-api/buildsystem/main.c
- include/llbuild/BuildSystem/ExternalCommand.h
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/BuildValue-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/libllbuild/include/llbuild/buildvalue.h
- products/llbuildSwift/BuildSystemBindings.swift
- products/llbuildSwift/BuildValue.swift
- unittests/CAPI/BuildSystem-C-API.cpp
- unittests/Swift/BuildSystemEngineTests.swift
Adds support returning custom build values from external commands
provided by BuildSystem Swift/C-API clients.
rdar://problem/58553449
> [Swift/C-API] Enable commands to return values

- tests/lit.cfg
Rather than attempting to implement the utility finding by hand, which
does not account for builtin utilities, use `lit` properly.
> test: use `lit` to provide `which`

- tests/lit.cfg
Use the more traditional `if` condition checks for the flag computation.
This will become more useful as more platforms are added.
> test: use idiomatic python for conditional evaluation

- tests/Examples/buildsystem-capi.llbuild
- tests/lit.cfg
On Windows, the default compiler is spelt `cl` as MSVC is the proffered
compiler in that environment.  `cc` is a unicism for the C compiler.
Explicitly use `clang` as the compiler as the test uses GNU command line
options.
This replicates the `swiftInferBinary` function from Swift to replicate
the environment handling and logging.
> tests: do not assume `cc` is valid

- tests/lit.cfg
Not all platforms have a full featured shell or a UNIX shell.  Enable
the use of the lit interpreter instead as a shell.
> test: enable using lit's internal shell parser

- examples/c-api/buildsystem/main.c
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/BuildValue-C-API-Private.h
- products/libllbuild/BuildValue-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/llbuildSwift/BuildSystemBindings.swift
- unittests/CAPI/BuildSystem-C-API.cpp
Allow tasks to defer to llbuild to get file info, specifically for use
in generating custom build values.
rdar://problem/59433735
> [Swift/C-API] Add getFileInfo support

- tests/Ninja/Build/strip-colors.ninja
On most systems echo will not interpret backslash escapes unless called with -e
> Call echo with -e in strip-colors.ninja

- Package.swift
- llbuild.xcodeproj/project.pbxproj
- llbuild.xcodeproj/xcshareddata/xcschemes/llbuild.xcscheme
- products/swift-Ninja/NinjaManifest.swift
- products/swift-Ninja/README.md
- unittests/Swift/BuildSystemEngineTests.swift
- unittests/TestSupport/Info.plist
- unittests/TestSupport/XCTestCase+Extensions.swift
- unittests/swift-Ninja/Info.plist
- unittests/swift-Ninja/SwiftNinjaTests.swift
- This is not an elegant implementation (it leverages the JSON support rather
than bridging to all the C++ APIs), but it is useful for bootstrapping
experiments with working with Ninja manifests in Swift.
> [SwiftNinja] Add a simple API for accessing Ninja manifests from Swift.

- Package.swift
- In some cases, the LLVM support library ends up needing to be linked against
libm.
> [Package] Add a potentially necessary linked library on Linux.

- lib/Ninja/Parser.cpp
- tests/Ninja/Parser/basic.ninja
- In certain cases, the lexer wouldn't be properly taken out of the customized
lexing mode for particular errors.
> [Ninja] Fix a crash in the parser.

- tests/Ninja/Build/strip-colors.ninja
On most systems echo will not interpret backslash escapes unless called with -e
> Backport: Call echo with -e in strip-colors.ninja

- include/llbuild/Ninja/Manifest.h
- lib/Commands/NinjaBuildCommand.cpp
- lib/Ninja/ManifestLoader.cpp
- tests/Ninja/Build/response-files.ninja
This PR adds support for `@response` files for llbuild ninja.
Changes:
* `rspfile` and `rspfile_content` rule attributes support
* `${in_newline}` parameter support
* simple test for response file deletion when a rule succeeded and response file content
> Ninja response files

- tests/Unit/lit.cfg
- It turns out that #532 refactored the output location of unit tests binaries,
which broke the lit integration with googletest. Thus, all our unit tests
haven't been running for a couple months 🤦‍♂️.
> [Unittests] Fix lit integration of googletest.

- products/llbuildSwift/CMakeLists.txt
Remove the absolute path to the host toolchain's stdlib from libllbuildSwift.so.
Otherwise, you see the following in the latest official 5.3 snapshot release for linux:
```
> readelf -d swift-5.3-DEVELOPMENT-SNAPSHOT-2020-05-04-a-ubuntu18.04/usr/lib/swift/pm/llbuild/libllbuildSwift.so | ag runpath
0x000000000000001d (RUNPATH)            Library runpath: [/home/buildnode/jenkins/workspace/oss-swift-5.3-package-linux-ubuntu-18_04/build/buildbot_linux/swift-linux-x86_64/lib/swift/linux:$ORIGIN:$ORIGIN/../../linux]
```
> [CMake][llbuildSwift] fix runpath for ELF platforms

- examples/c-api/buildsystem/main.c
- include/llbuild/BuildSystem/BuildSystemHandlers.h
- include/llbuild/BuildSystem/Command.h
- include/llbuild/BuildSystem/ExternalCommand.h
- include/llbuild/BuildSystem/ShellCommand.h
- include/llbuild/Core/BuildEngine.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/ExternalCommand.cpp
- lib/BuildSystem/ShellCommand.cpp
- lib/Commands/BuildEngineCommand.cpp
- lib/Commands/BuildSystemCommand.cpp
- lib/Commands/NinjaBuildCommand.cpp
- lib/Evo/EvoEngine.cpp
- perftests/Xcode/PerfTests/CorePerfTests.mm
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/Core-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/libllbuild/include/llbuild/core.h
- products/libllbuild/include/llbuild/llbuild.h
- products/llbuildSwift/BuildSystemBindings.swift
- products/llbuildSwift/CoreBindings.swift
- unittests/CAPI/BuildSystem-C-API.cpp
- unittests/Core/BuildEngineCancellationTest.cpp
- unittests/Core/BuildEngineTest.cpp
- unittests/Core/DepsBuildEngineTest.cpp
Passing a reference to a stack allocated TaskInterface object complicated safe usage of it in clients.  In particular, the Swift/C-API interface made it unsafe to perform work on another thread. This changes to pass-by-value semantics for the small, two pointer class/struct, enabling simpler/safer use of it on other threads.
> Adjust TaskInferface passing for easier use

- perftests/Xcode/PerfTests/CMakeLists.txt
There are two reason to use plutil
* `defaults` will no longer support this in the future, as per man page
> WARNING: The defaults command will be changed in an upcoming major
release to only operate on preferences domains. General plist
manipulation utilities will be folded into a different command-line
program.
* `plutil` prints more meaningful errors that help in troubleshooting CI issues
Indeed this switch helped uncover an issue with the logic inferring the path of `XcodePerfTests.xctest`.
Addresses rdar://63984731
> Enhance fixup target to use plutil and get correct xctest path

- perftests/Xcode/PerfTests/CMakeLists.txt
There are two reason to use plutil
* defaults will no longer support this in the future, as per man page
> WARNING: The defaults command will be changed in an upcoming major
release to only operate on preferences domains. General plist
manipulation utilities will be folded into a different command-line
program.
* plutil prints more meaningful errors that help in troubleshooting CI
issues
Indeed this switch helped uncover an issue with the logic inferring the
path of XcodePerfTests.xctest.
Addresses rdar://63984731
(cherry picked from commit 145c113cde37318f3cef38843f9ce6a678aaa4fd,  #673)
> [5.3] Enhance fixup target to use plutil and get correct xctest path

- include/llbuild/Core/BuildEngine.h
- lib/Core/BuildEngine.cpp
- tests/BuildSystem/Build/basic.llbuild
- tests/BuildSystem/Build/file-system-opts.llbuild
- tests/Ninja/Build/graphviz-output.ninja
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
- unittests/Core/BuildEngineTest.cpp
This changes the core engine processing order to preserve the order in which tasks/the client have requested input dependencies. This ensures that subsequent builds scan those dependencies in a similar ordering.
> [Core] Record dependencies in order requested

- products/llbuildSwift/BuildSystemBindings.swift
The memory allocation for the data here is done via copying the data
from the bytes in the string.  This allocation is done by
`UnsafeMutableBufferPointer.allocate`.  Map the release for that data to
`UnsafeMutableBufferPointer.deallocate`.
This presented itself as a heap buffer corruption on Windows when
building swift-package-manager with swift-package-manager in release
mode on Windows.
> llbuildSwift: correct a memory corruption issue

- include/llbuild/Basic/ExecutionQueue.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- lib/Basic/LaneBasedExecutionQueue.cpp
- lib/Basic/Subprocess.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/Commands/NinjaBuildCommand.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/libllbuild/include/llbuild/llbuild.h
- products/llbuildSwift/BuildSystemBindings.swift
- unittests/Basic/LaneBasedExecutionQueueTest.cpp
- unittests/BuildSystem/MockBuildSystemDelegate.h
This allows controlling the QoS execution per BuildSystem instance.
Part of rdar://63197398
> Add QoS parameter for a build invocation

- Package.swift
llbuild depends on LLVMSupport and LLVMDemangle.  These libraries
require that `LLVM_ON_WIN32` is defined when building them on Windows
(and technically `LLVM_ON_UNIX` on Unicies).  This is required when
building llbuild with swift-package-manager on Windows.
> build: define `LLVM_ON_WIN32` when building LLVM on Windows

- Package.swift
This is required to decorate the public symbols with
`__declspec(dllexport)` as we do not currently support static linking on
Windows with SwiftPM.
> build: define `libllbuild_EXPORTS` on Windows

- Package.swift
The original alteration would not compile since the anonymous binding
for the outer closure was lost.  This should hopefully repair the build.
> build: repair the windows build after #683

- llbuild.xcodeproj/project.pbxproj
This is to simplify some other build configuration elsewhere.
Related: rdar://67568955
> Base the install paths of targets on DEVELOPER_INSTALL_DIR

- Package.swift
I've been [using this patch for Android](https://github.com/termux/termux-packages/commit/5e6418f935dff04592ac046fa76b24d52c974933#diff-3e4d7e12295ed3c5dd4a544329edc3a5R16) since last year, but couldn't upstream it till the `swift-tools-version` was bumped to 5.2, which finally happened with 1f45b1106 a couple weeks ago. This is needed because [I didn't add Android to SPM as a platform till before the 5.2 branch](https://github.com/apple/swift-package-manager/pull/2396/files#diff-b1cc9168051b688bafb8ae050c4f6c7bR42).
> [Package] add ncurses dependency for Android

- products/libllbuild/BuildDB-C-API.cpp
This was found by running tests under ASAN.
> [BuildDB-C-API] Fix buffer read overflow

- products/llbuildSwift/BuildKey.swift
Inside the `BuildKey.construct(data:)` function, `llb_build_key_make` allocates a new `CAPIBuildKey` object which gets leaked because of `weakPointer` set to true.
> [llbuildSwift/BuildKey] Fix memory leak coming from `BuildKey.construct(data:)`

- products/llbuildSwift/CMakeLists.txt
Remove the absolute path to the host toolchain's stdlib from libllbuildSwift.so.
It has been suggested to me by some Swift devs that this would be good to get in before the 5.3 release, a cherry-pick from #670.
This should be completely safe for the 5.3 branch, as it's just removing the build toolchain's stdlib rpath, which should be unused by this library.
> [5.3][CMake][llbuildSwift] fix runpath for ELF platforms

- examples/simple-make/count-lines-1
- examples/simple-make/count-lines-2
- examples/simple-make/count-lines-3
- examples/simple-make/count-lines-4
- examples/simple-make/simple-make
- tests/BuildSystem/Build/Inputs/get-file-permissions
- tests/Ninja/Build/Inputs/check-open-fds
- tests/Ninja/Build/Inputs/split-numbers
- tests/SwiftBuildTool/Inputs/pseudo-swiftc
- utils/create-dummy-ninja-from-DB.py
- utils/docker/docker-utils
- utils/import-llvm/import-llvm
- utils/manifest-generator/generate-llbuild-manifest
Most of the changes here just convert `print` statements (which are no longer supported in Python3) to `print()` function calls (which exists in both Python 2 and 3).
The only other change of note is to strip the `o` character from the output of `oct()`.  In Python 3, `oct()` outputs octal values with a leading `0o` as 0o123 and these scripts expect C-style octal format `0123` instead.
> [Python3] Update scripts to support Python3

- include/llvm/Config/abi-breaking.h
These are ABI incompatible changes requiring that the build to be
consistent in configuration across all products.  This prevents the
build of SourceKit-LSP on Windows due to the mismatch when building
using swift-package-manager in a debug configuration without local
dependencies.
> LLVMSupport: disable ABI breaking checks

- products/llbuildSwift/CMakeLists.txt
Master PR - https://github.com/apple/swift-llbuild/pull/682
> [5.3] Adjust swift target based on CMAKE_OSX_ARCHITECTURE

- lib/Basic/Subprocess.cpp
Currently SwiftPM ignores Ctrl-C on Windows, this change makes it stop the build process when Ctrl-C is pressed
> Handle interrupts properly on Windows

- products/libllbuild/BuildSystem-C-API.cpp
- products/llbuildSwift/BuildSystemBindings.swift
- products/llbuildSwift/Internals.swift
This reverts part of the previous commit and adjusts the allocation to
explicitly use `malloc`.  This matches the requirement in
`get_signature` (buildsystem.h:609):
```
/// The contents *MUST* be returned in a new buffer allocated with \see
/// malloc().
```
This also repairs a followup heap corruption detected on Windows when
working on `swift test` in release mode for building
swift-package-manager.
> llbuildSwift: follow up to 6c9097625d46

- lib/llvm/Support/Windows/Signals.inc
When building SourceKit-LSP on Windows with swift-package-manager, we
end up with multiple definitions of `HandleAbort` due to multiple copies
of `LLVMSupport` being used due to the shared linking model of
swift-package-manager.  Declare the function as static to make it be
COMDATed.
> LLVMSupport: make `HandleAbort` static

- lib/llvm/Support/CMakeLists.txt
llbuild ninja test binary needs to link against ncurses:
https://github.com/apple/swift-llbuild/blob/a9f4b75cf7288156ed1880f98cebe17da1543a38/Package.swift#L207
> llbuild ninja test binary links against ncurses

- products/llbuildSwift/BuildDBBindings.swift
- products/llbuildSwift/BuildKey.swift
- products/llbuildSwift/BuildSystemBindings.swift
- products/llbuildSwift/BuildValue.swift
- products/llbuildSwift/Internals.swift
Replace the use of `MSVCRT` with `ucrt` as only the standard C
interfaces are needed.  This is in preparation to move away from
`MSVCRT`.
> llbuildSwift: replace unnecessary import of `MSVCRT`

- lib/Basic/FileInfo.cpp
This is currently the only warning when building swift-package-manager using its bootstrap script.
Since this is a declaration in a source file and not a header, it seemed reasonable to just remove it.  The include/llbuild/Basic/FileInfo.h header already has the proper comments.
> Fix a warning that occurs when building with -Wdocumentation

- tests/Ninja/Build/max-commands-progress.ninja
While most of the times `output-2` is copied before `output-1`, in some
rare cases the opposite can happen (which seems reasonable since there
is no ordering requirement between the two).
Addresses rdar://72898516
> [Test] Relax ordering assumption in max-commands-progress.ninja

- tests/Examples/buildsystem-capi.llbuild
- tests/Ninja/Build/incremental.ninja
- unittests/Swift/BuildDBBindingsTests.swift
BuildDBBindingsTests: Swift variables are not guaranteed to live to the
end of their declarating scope; extend the lifetime of the database
object in a couple of the test methods to ensure they are not
prematurely deallocated.
buildsystem-capi.llbuild: macOS uses DYLD_LIBRARY_PATH,
not LD_LIBRARY_PATH. Pass the proper environment variable to the test
so that libllbuild.dylib can be found. This only manifested locally, not
on the CI, for some reason.
incremental.ninja: relax the ordering assumption. This is the same fix
done for the similar max-commands-progress.ninja test case back in
f339c9e115816b72bafad1b8a2927a6eccca66b5.
> Fix the llbuild tests that are broken/flaky and blocking CI

- lib/BuildSystem/BuildSystem.cpp
Since this is using `popen`, we were capturing stdout, but stderr could still end up on the terminal. In particular, the Swift driver version could be intermingled with other output in tools using llbuild such as SwiftPM, because it is being printed to stderr: https://github.com/apple/swift-driver/blob/main/Sources/SwiftDriver/Driver/Driver.swift#L989
> Redirect stderr when calling `swift -version`

- include/llbuild/Basic/CrossPlatformCompatibility.h
- include/llvm/Config/config.h
- lib/llvm/Demangle/Utility.h
- products/libllbuild/include/llbuild/core.h
- utils/adjust-times/adjust-times.cpp
OpenBSD doesn't have backtrace in the base system, and requires these
headers for calling utime(3). While we can install libexecinfo on this
platform to get backtraces and that this platform has obsoleted utime(3)
for utimes(2), make llbuild compile on this platform as-is first.
Some of these other includes are also required to satisfy missing type
declarations only visible once bootstrapped and modules used.
> Add support for OpenBSD.

- products/llbuildSwift/BuildSystemBindings.swift
We see a compiler error due to rdar://71269128 in several host
builders.
> Add a work-around for rdar://71269128

- products/libllbuild/include/llbuild/llbuild.h
This was changed in #538 without a clear reason, and it breaks
framework-style includes in some cases. Return to the original style.
> Fix the llbuild umbrella header

- lib/BuildSystem/BuildSystem.cpp
> DirectoryContentsTask::inputsAvailable may assert due to missing output

- examples/GameOfLife/Package.swift
`swift run` no longer successfully run the example because the `master` branch renamed into `main`.  This is a tiny fix to simply correct the branch name for example.
> [FIX] Update Game of Life example for master branch renaming

- products/llbuild-analyze/Package.resolved
- products/llbuild-analyze/Package.swift
- products/llbuild-analyze/Sources/CriticalPathTool.swift
This PR aims to restore compatibility of `llbuild-analyze` with newer versions of Swift by updating its package dependencies.
* Bumped `swift-argument-parser` to version `0.4.3`
* This version required syntax changes in `CriticalPathTool.swift` as the property wrapper initializers for `@Option` and `@Flag` have changed.
* Changed the branch of `swift-tools-support-core` as `master` has been renamed to  `main`
* With the revision previously defined in `Package.resolved`, the package would now fail to build with Swift 5.5 as `TSCBasic` defined a function named `await` which is now a reserved keyword in Swift. This has already been addressed in the swift-tools-support-core repository (https://github.com/apple/swift-tools-support-core/pull/164) and will be included with this update.
> [llbuild-analyze] Update dependencies to be compatible with Swift 5.5

- include/llbuild/BuildSystem/BuildSystem.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/llbuildSwift/BuildSystemBindings.swift
- unittests/BuildSystem/MockBuildSystemDelegate.h
For certain kinds of build operations, it is useful to be able to continue even after errors are occurring.
For the case of a node having multiple producers, give the option to the client delegate to choose the most appropriate command,
and allow the build to continue.
Part of rdar://80341017
> [BuildSystemDelegate] Introduce `BuildSystemDelegate::chooseCommandFromMultipleProducers()`

- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/ExternalCommand.cpp
Before this change, subclasses of ExternalCommand were only invoked if the build value has been produced by a command (success or failure). With this change, the subclass gets invoked for all build values to keep track of its dependencies. It can still distinguish between the different inputs by looking for the requested inputID.
rdar://57125025
> Invoke subclasses of ExternalCommand unfiltered

- lib/BuildSystem/BuildSystem.cpp
- products/libllbuild/include/llbuild/llbuild-defines.h
Also make 'Checking Swift Compiler Version' not show its status (SwiftPM expects it that way).
rdar://82651879
> Implement update status for rules representing custom tasks

- lib/BuildSystem/BuildFile.cpp
- products/llbuildSwift/BuildSystemBindings.swift
- unittests/Swift/BuildSystemEngineTests.swift
Some clients may not be able to create commands on-demand and may look
them up in an existing store when requested, which may not have said
command.
rdar://55989748
> Allow clients to indicate that createCommand has failed

- lib/BuildSystem/BuildSystem.cpp
This fixes a nagging bug on Windows; the persistent error message generated whenever swift-build runs:
'The system cannot find the path specified.'
(Coincidentally, it was also creating a file called "null" in my "C:/dev" directory.)
> On Windows, use 2>NUL to ignore stderr output

- include/llbuild/Basic/Subprocess.h
- include/llbuild/Core/BuildEngine.h
- lib/Basic/Subprocess.cpp
- lib/BuildSystem/BuildSystemExtensionManager.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/Commands/BuildEngineCommand.cpp
- lib/Commands/NinjaBuildCommand.cpp
- lib/Core/BuildEngine.cpp
- lib/Evo/EvoEngine.cpp
- perftests/Xcode/PerfTests/BuildSystemPerfTests.mm
- perftests/Xcode/PerfTests/CorePerfTests.mm
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/Core-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/llbuildSwift/BuildSystemBindings.swift
- products/llbuildSwift/Internals.swift
- unittests/Basic/LaneBasedExecutionQueueTest.cpp
- unittests/BuildSystem/MockBuildSystemDelegate.h
- unittests/Core/BuildEngineCancellationTest.cpp
- unittests/Core/BuildEngineTest.cpp
- unittests/Core/DepsBuildEngineTest.cpp
- unittests/Evo/EvoEngineTest.cpp
TaskInterface offers an API to spawn sub-processes for ExternalCommands' executeExternalCommand method. This API was not exposed to Swift clients before. With this change, Swift (and C) clients can spawn sub-processes from within the ExternalCommand context enabling custom commands with custom dependency and lifecycle logic while still using llbuild for the execution of processes.
rdar://58130781
> Expose TaskInterface's spawn API to clients

- products/llbuildSwift/BuildSystemBindings.swift
This is needed because Windows models llbuild_pid_t as a HANDLE, which is an implicitly unwrapped pointer, so the value can be nil, INVALID_HANDLE_VALUE, or a valid HANDLE value.
> [Windows Build] Change processStarted(pid:) to use llbuild_pid_t?

- examples/c-api/buildsystem/main.c
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/llbuildSwift/BuildSystemBindings.swift
- unittests/CAPI/BuildSystem-C-API.cpp
ExternalCommands mimic a process that runs in-process but could express their result only as a bool before.
With this change, an ExternalCommand can also set itself as cancelled or skipped on their own logic.
That allows clients to cancel commands if their dependencies exit with an unwanted BuildValue.
rdar://87451647
> Add API to return CommandResult for ExternalCommands

- lib/BuildSystem/ExternalCommand.cpp
- products/llbuildSwift/Internals.swift
For very large inputs the recursive implemenation might hit a stack overflow.
rdar://88132779
> Implement `withCArrayOfStrings` non-recursive

- lib/BuildSystem/BuildSystem.cpp
> Add new 'module-alias' attribute handling in llbuild

- Package.swift
This extends some of the special handling for Windows to allow building
the full llbuild package currently on Windows with SPM.  With this set
of changes and one workaround, it is possible to build all of llbuild
with SPM:
~~~
swift build -Xcc -IS:\Library\sqlite-3.36.0\usr\include -Xlinker -LS:\Library\sqlite-3.36.0\usr\lib -Xswiftc -use-ld=lld %DEVELOPER_DIR%\Platforms\Windows.platform\Developer\SDKs\Windows.sdk\usr\lib\swift\windows\x86_64\swiftCore.lib
~~~
> build: adjust Package.swift for Windows builds

- include/llbuild/Core/BuildEngine.h
- include/llbuild/Core/DependencyKeyIDs.h
- lib/Core/BuildEngine.cpp
- lib/Core/SQLiteBuildDB.cpp
- llbuild.xcodeproj/project.pbxproj
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/llbuildSwift/BuildSystemBindings.swift
A dependency marked as singleUse will only be added to the dependencies of the requesting task for the current build iteration.
This allows tasks to request other tasks for running once and not get invalidated for following incremental builds.
rdar://91494744
> Add option to mark dependencies as single use

- unittests/Swift/BuildDBBindingsTests.swift
> Fix BuildDBBindingsTests.testCouldNotOpenDatabaseErrors

- include/llvm/Support/Chrono.h
`Chrono.h` uses `std::ratio`, but was relying on a transitive include
from `<chrono>`. Include `<ratio>` directly.
> [next] Add missing include for ratio

- include/llbuild/BuildSystem/BuildSystem.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- include/llbuild/Core/BuildEngine.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/Core/BuildEngine.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/libllbuild/include/llbuild/llbuild-defines.h
- products/llbuildSwift/BuildSystemBindings.swift
- unittests/BuildSystem/MockBuildSystemDelegate.h
…, and why
For example, because it has never been built, or because one of its inputs was rebuilt
rdar://95208406
> Add an API to notify the BuildEngine/BuildSystem delegate when it is determined that a rule needs to run

- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/ShellCommand.cpp
This ensures dependency file parsing runs as soon as possible after a task finishes, in FIFO order when using the LaneBasedExecutionQueue. Previously, it could run significantly later when many tasks were enqueued, delaying "task finished" callbacks despite the fact that very little work remained to be done.
rdar://96151636
> Run ShellCommand dependency parsing at high priority

- products/llbuildSwift/BuildSystemBindings.swift
There's no guarantee that a read from a child process' stdout will yield valid UTF-8, even if the entirety of the output would be a valid UTF-8 string. Instead of attempting to decode process output in the Swift bindings, forward the raw bytes so clients can handle it appropriately for their use case. This is consistent with the similar `commandProcessHadOutput` delegate method.
rdar://97019909
> Change ProcessDelegate.processHadOutput(output:) argument from String to [UInt8]

- products/llbuildSwift/BuildSystemBindings.swift
- unittests/Swift/BuildSystemEngineTests.swift
We don't need these anymore.
rdar://99288001
> Remove deprecated protocol requirements from Tool

- products/libllbuild/BuildSystem-C-API.cpp
- products/llbuildSwift/BuildSystemBindings.swift
Some external commands shell out to tools which may produce dependency files. Configuring them with a working directory allows relative paths which may appear in these files to be resolved correctly. The resolution logic added here is identical to ShellCommands'
rdar://99284779
> Allow configuring the working directory of C-API external commands

- README.md
The link to Jira is outdated and leads to the main `swift` repository. This is incorrect, since `swift-llbuild` repository has its own issue tracker on GitHub.
> README.md: link to GitHub Issues instead of Jira

- products/libllbuild/BuildKey-C-API.cpp
It fixes this warning:
```
/llbuild/products/libllbuild/BuildKey-C-API.cpp:182:11: warning: variable 'index' set but not used [-Wunused-but-set-variable]
int32_t index = 0;
```
> [NFC] libllbuild/BuildKey-C-API.cpp: remove unused variable

- products/libllbuild/include/llbuild/llbuild-defines.h
`_DLL` indicates that the MSVCRT version is the shared form rather than static.  This corresponds to `/MD` (and the lack to `/MT`).  `_WINDLL` is used to indicate that we are building statically or dynamically. This change is required to experiment with static builds of libllbuild with CMake.
> libllbuild: correct the macro usage for DLL builds

- include/llbuild/Core/DependencyKeyIDs.h
- include/llbuild/Core/KeyID.h
- lib/Commands/BuildSystemCommand.cpp
- lib/Core/BuildEngine.cpp
- lib/Core/SQLiteBuildDB.cpp
- products/libllbuild/BuildDB-C-API.cpp
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
- unittests/Core/BuildEngineTest.cpp
- unittests/Core/SQLiteBuildDBTest.cpp
- unittests/Swift/BuildDBBindingsTests.swift
This is my try at solving FB8394316 that I reported. I found no good way to know when it's safe to scan dependencies in parallel. If you scan all of them at once you end up with incorrect scan results. I ended up solving this with barriers between batches of dependencies. This passes all the tests and seems to work ok in Xcode. The barriers are created when a result is reported to a task as that should prevent calculations on stale values.
rdar://20248283
> Parallel  Incremental Builds

- products/libllbuild/CMakeLists.txt
We currently do not build `libllbuild` statically (though we could). Indicate that we are building it dynamically on Windows via `_WINDLL`.
> build: correct indicator that we are building in shared mode

- include/llbuild/BuildSystem/ExternalCommand.h
- lib/BuildSystem/ExternalCommand.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/llbuildSwift/BuildSystemBindings.swift
Currently, we don't have the necessary information to report which input is missing, but higher-level build systems can use other delegate callbacks to reconstruct that information. If no missing input is reported at all, we can easily end up in a situation where tasks are unexpectedly and silently cancelled, making debugging these sorts of issues difficult.
rdar://58130864
> Report when a task has a missing dynamically-requested input

- include/llbuild/BuildSystem/BuildFile.h
- include/llbuild/BuildSystem/BuildNode.h
- include/llbuild/BuildSystem/Command.h
- include/llbuild/BuildSystem/ExternalCommand.h
- lib/BuildSystem/BuildFile.cpp
- lib/BuildSystem/BuildNode.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/ExternalCommand.cpp
- lib/Commands/BuildSystemCommand.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- tests/BuildSystem/Build/directory-input-and-output.llbuild
- tests/BuildSystem/Build/directory-input-basic.llbuild
- tests/BuildSystem/Build/directory-input-must-scan-after-paths-error.llbuild
- tests/BuildSystem/Build/directory-input-must-scan-after-paths.llbuild
Follow up to `[1]` which was reverted in `[2]` because it broke downstream.
This PR
* turns ownership analysis off-by-default to avoid various bootstrapping issues
* implements a mechanism to opt-out certain tasks from ownership analysis
* broadens the scope of analysis so we can have ownership information for mkdir, symlink and custom commands (not just external command)
`[1]`: https://github.com/apple/swift-llbuild/pull/849
`[2]`: https://github.com/apple/swift-llbuild/pull/854
> rdar://104245531 (ProducedDirectory outputs in llbuild and opt-in ownership analysis)

- include/llbuild/Basic/FileInfo.h
- include/llbuild/Basic/FileSystem.h
- lib/Basic/FileInfo.cpp
- lib/Basic/FileSystem.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/Commands/NinjaBuildCommand.cpp
- lib/Core/SQLiteBuildDB.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- tests/BuildSystem/Build/file-system-checksum-only-symlinks.llbuild
- tests/BuildSystem/Build/file-system-checksum-only.llbuild
- unittests/Basic/FileSystemTest.cpp
- unittests/BuildSystem/BuildSystemTaskTests.cpp
This PR lands an opt-in support for content checksum comparison in FileInfo.
Normally a rule is marked for `NeedsToRun` if the timestamp of its input is different from the result from previous build.
In contrast to how llbuild currently works, using `ChecksumOnlyFileSystem` should cause llbuild to not mark a rule as `NeedsToRun` when modification time of input is different but checksum of the contents of the path that FileInfo is referring to matches the checksum from previous build.
> rdar://99877341 (Check contents instead of modTime to determine if rule needs rerun)

- lib/Core/BuildEngine.cpp
~~~
D:\a\swift-build\swift-build\SourceCache\swift-llbuild\lib\Core\BuildEngine.cpp(138): error C2397: conversion from 'int' to 'unsigned int' requires a narrowing conversion ~~~
~~~
This repairs a build error when building with `cl`.
> Core: await narrowing cast warning

- include/llbuild/Basic/Stat.h
The value itself is the result of the macro, which was not parenthesized which made the usage of it incorrect in a few places where the negation was being checked and that bound more tightly than the equality check.
> llbuild: add missing parenthesis to macros

- tests/BuildSystem/Build/file-system-checksum-only-symlinks.llbuild
- tests/BuildSystem/Build/file-system-checksum-only.llbuild
For `configuration: [main] OSS - Swift Package - Amazon Linux 2 (aarch64)` we get
```
/home/build-user/llbuild/tests/BuildSystem/Build/file-system-checksum-only.llbuild:48:31: error: CHECK-REBUILD-MODIFIED-NOT: excluded string found in input
^
/home/build-user/build/buildbot_linux/llbuild-linux-aarch64/tests/BuildSystem/Build/Output/file-system-checksum-only.llbuild.tmp3.out:3:1: note: found here
Capitalize first word
```
Didn't observe locally nor in smoke tests.. trying to investigate via Docker.
Meanwhile let's mark them as expected failure to unblock Swift CI.
> Mark checksumOnly tests as expected failure to unblock Swift CI

- unittests/Swift/BuildDBBindingsTests.swift
Apparently we don't run tests for Swift bindings when we smoke test (smoke tests only run lit tests) and I forgot to run Swift binding tests before merging.
> rdar://105261237 (llbuild test failure in BuildDBBindingsTests.testCouldNotOpenDatabaseErrors)

- include/llbuild/Core/DependencyKeyIDs.h
- include/llbuild/Core/KeyID.h
- lib/Commands/BuildSystemCommand.cpp
- lib/Core/BuildEngine.cpp
- lib/Core/SQLiteBuildDB.cpp
- products/libllbuild/BuildDB-C-API.cpp
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
- unittests/Core/BuildEngineTest.cpp
- unittests/Core/SQLiteBuildDBTest.cpp
- unittests/Swift/BuildDBBindingsTests.swift
This temporarily reverts https://github.com/apple/swift-llbuild/pull/832 and https://github.com/apple/swift-llbuild/pull/863 due to downstream test failures.
> Revert "Allow concurrent scanning of dependencies for incremental builds"

- products/libllbuild/BuildSystem-C-API.cpp
> Crash in commandCannotBuildOutputDueToMissingInputs reported by ubsan

- include/llbuild/BuildSystem/Command.h
- lib/BuildSystem/BuildFile.cpp
- lib/BuildSystem/BuildNode.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/ExternalCommand.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- tests/BuildSystem/Build/directory-input-and-output.llbuild
- tests/BuildSystem/Build/directory-input-must-scan-after-paths-error.llbuild
- tests/BuildSystem/Build/directory-input-must-scan-after-paths.llbuild
Minor refinement to the inclusion/exclusion mechanism. We need this before we can land a downstream PR.
> A1 rdar://105156287 ([ownership-analysis] Restrict mustScanAfterPaths to user scripts)

- CMakeLists.txt
- products/libllbuild/CMakeLists.txt
- products/llbuildSwift/CMakeLists.txt
Now that `libllbuildSwift` is statically linked against `libllbuild` with #852, remove the runpath and don't install it. Also, the Android build started failing, so set the appropriate flag for it to work again.
Previously, we installed `libllbuild.so` in the Swift toolchain alongside `libllbuildSwift.so` and set the ELF runpath so it knew it was in the same directory:
```
> ls swift-5.7.3-RELEASE-ubuntu20.04/usr/lib/swift/pm/llbuild/
libllbuild.so  libllbuildSwift.so
> readelf -d swift-5.7.3-RELEASE-ubuntu20.04/usr/lib/swift/pm/llbuild/libllbuildSwift.so |ag runpath
0x000000000000001d (RUNPATH)            Library runpath: [$ORIGIN:$ORIGIN/../../linux]
```
Now that @compnerd made it link statically, we're wrongly shipping the static libllbuild and still have the now unneeded runpath:
``` …
```
> [CMake] Don't install libllbuild in the Swift toolchain now that it's statically linked

- products/libllbuild/BuildSystem-C-API.cpp
Fix a memory leak in this delegate method of one of the build key wrappers
> Fix leak in CAPIBuildSystemFrontendDelegate::determinedRuleNeedsToRun

- Package.swift
Update the build for Windows to get SPM based builds working better.  This should make it easier to work with llbuild and SPM when developing with SPM.
> Various set of SPM based build updates for Windows

- Package.swift
This should be rebased upon #873.  It simultaneously requires apple/swift-package-manager#6345 to get the fix for the `..` header search path handling corrected.  Update the build rules for GTest to avoid duplicate definitions, add build rules for GMock, update the tests to use GMock as a dependency.  This set of updates enables building llbuild with SPM on Windows (with some minor hand holding for SQLite and overlinking of swiftrt.obj).
> Various build fixes to get llbuild to build with SPM on Windows

- lib/Basic/Subprocess.cpp
- lib/BuildSystem/ShellCommand.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- tests/BuildSystem/Build/discovered-makefile-deps-relative.llbuild
The deployment target issues which lead to the initial revert several years back are no longer a concern. Reapply these changes, so that when spawning tasks we're making less use of global state.
> Reapply changes to use posix_spawn_file_actions_addchdir_np on macOS

- tests/SwiftBuildTool/swift-compiler-whole-module-optimization.swift-build
The Apple Silicon bot appears to use a newer version of Python, so outputs a deprecation warning for `pipes.quote`. For now, update the `CHECK` line to handle this. rdar://109671403 is tracking the replacement of `pipes.quote` with `shlex.quote`.
rdar://109833753
> Fix test for Apple Silicon bot

- tests/SwiftBuildTool/swift-compiler-whole-module-optimization.swift-build
*5.8 cherry-pick of https://github.com/apple/swift-llbuild/pull/878*
The Apple Silicon bot appears to use a newer version of Python, so outputs a deprecation warning for `pipes.quote`. For now, update the `CHECK` line to handle this.
rdar://109833753
> [5.8] Fix test for Apple Silicon bot

- tests/SwiftBuildTool/swift-compiler-whole-module-optimization.swift-build
*5.9 cherry-pick of https://github.com/apple/swift-llbuild/pull/878*
The Apple Silicon bot appears to use a newer version of Python, so outputs a deprecation warning for `pipes.quote`. For now, update the `CHECK` line to handle this.
rdar://109833753
> [5.9] Fix test for Apple Silicon bot

- include/llbuild/Basic/CrossPlatformCompatibility.h
- include/llvm/Config/config.h
- products/llbuildSwift/BuildDBBindings.swift
- products/llbuildSwift/BuildKey.swift
- products/llbuildSwift/BuildSystemBindings.swift
- products/llbuildSwift/BuildValue.swift
- products/llbuildSwift/Internals.swift
Since Musl is sufficiently different from Glibc (see https://wiki.musl-libc.org/functional-differences-from-glibc.html), it requires a different import, which now should be applied to files that have `import Glibc` in them.
> Add support for Musl libc

- include/llbuild/Basic/Tracing.h
This code being previously allowed was a bug in Clang addressed in https://github.com/llvm/llvm-project/issues/38717.
Resolves rdar://111400323
> Fixup use of invalid implicit cast of strongly-typed enum to underlying type.

- include/llvm/Config/config.h
Bionic added execinfo.h last year, but [only made the backtrace APIs available
for Android API 33 or later](https://android.googlesource.com/platform/bionic/+/refs/heads/main/libc/include/execinfo.h#48).
@3405691582, #881 also removed your OpenBSD check, but I see that OpenBSD recently added this header, mesonbuild/meson#11151, so the header check should suffice there?
@al45tair, you suggested this change, please review.
[Here is the error message showing this failing on my Android CI](https://github.com/finagolfin/swift-android-sdk/actions/runs/5484702470/jobs/9992614257#step:6:5839), and the subsequent pull adding this change to my Android CI that fixed it, finagolfin/swift-android-sdk#112.
> Fix recent build regression on Android

- examples/c-api/buildsystem/main.c
- include/llbuild/BuildSystem/BuildSystem.h
- include/llbuild/BuildSystem/Command.h
- include/llbuild/Core/BuildEngine.h
- lib/BuildSystem/BuildSystem.cpp
- lib/Core/BuildEngine.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/llbuildSwift/BuildSystemBindings.swift
- unittests/CAPI/BuildSystem-C-API.cpp
- unittests/Swift/BuildSystemEngineTests.swift
These are commands that run without blocking the execution lanes or being constrained by them (the number of execution lanes does not restrict how many 'detached' commands can run in parallel).
It is up to the client to decide whether a 'detached' command is appropriate for its purposes, but a good use case for executing commands outside the execution lanes is when the work involves the network; in such case it is beneficial to avoid blocking execution lanes while waiting for network queries, while also being able to initiate more parallel network queries than the number of CPU cores.
> Introduce the concept of "detached" external commands for the C/Swift API

- lib/BuildSystem/BuildSystem.cpp
- tests/SwiftBuildTool/swift-compiler-whole-module-optimization.swift-build
- tests/SwiftBuildTool/swift-compiler.swift-build
Passing both results in noisy remarks when building from the command line like:
```
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
```
https://forums.swift.org/t/incremental-compilation-has-been-disabled-it-is-not-compatible-with-whole-module-optimization/66092
> Remove -incremental when using -whole-module-optimization

- lib/BuildSystem/BuildSystem.cpp
- tests/SwiftBuildTool/swift-compiler-whole-module-optimization.swift-build
- tests/SwiftBuildTool/swift-compiler.swift-build
Passing both results in noisy remarks when building from the command line like:
```
remark: Incremental compilation has been disabled: it is not compatible with whole module optimization
```
https://forums.swift.org/t/incremental-compilation-has-been-disabled-it-is-not-compatible-with-whole-module-optimization/66092
(cherry picked from commit 0c2e0dd9967c7121d07fac42f69bb015a9e033d3 / https://github.com/apple/swift-llbuild/pull/884)
> [5.9] Remove -incremental when using -whole-module-optimization

- Xcode/Configs/Common.xcconfig
- products/libllbuild/BuildKey-C-API.cpp
- products/libllbuild/include/llbuild/buildkey.h
- products/libllbuild/include/llbuild/llbuild-defines.h
- products/llbuildSwift/BuildKey.swift
Custom task data is often unstructured, and won't be valid UTF-8. Exposing API that works with data instead of strings avoids the need for hacks like base-64 encoding when creating them using the Swift API, and makes it easier to avoid UTF8 encoding overhead.
Also, adopt the use of a Swift user module version in llbuild, allowing clients to more easily stage in use of new API
rdar://112936539
> Add new Swift API for creating CustomTasks from byte arrays instead of strings

- Xcode/Configs/Common.xcconfig
- llbuild.xcodeproj/project.pbxproj
Add a convenient override point to skip building the CLI tools in some contexts.
> Add user-defined SKIP_INSTALL_CLI_TOOLS setting to the Xcode build

- Package.swift
The llbuild executable is not a dependency of these two libraries.
Note that apple/swift-package-manager#6909 will have to be merged first, else reverting this will break the SwiftPM build.
> Revert 'Add missing dependencies (#888)'

- unittests/BuildSystem/BuildSystemFrontendTest.cpp
The number of paralell jobs can be lower than 2 if the host hardware has a lower number of cores.
The ci job running on a machine with 2 cores is failing due to these assertions (the job recently started testing llbuild)
```
/home/buildbot/jenkins/workspace/oss-swift-RA-linux-ubuntu-20.04-webassembly/llbuild/unittests/BuildSystem/BuildSystemFrontendTest.cpp:404: Failure
Expected equality of these values:
delegate.maxTaskParallism()
Which is: 2
3
/home/buildbot/jenkins/workspace/oss-swift-RA-linux-ubuntu-20.04-webassembly/llbuild/unittests/BuildSystem/BuildSystemFrontendTest.cpp:404
Expected equality of these values:
delegate.maxTaskParallism()
Which is: 2
3
```
https://ci-external.swift.org/job/oss-swift-RA-linux-ubuntu-20.04-webassembly/1641/console
> Fix parallelism check failures with few cores

- Package.swift
Cherrypick of #891
__Explanation:__ The llbuild executable is not a dependency of these two libraries.
__Scope:__ Only affects SwiftPM build of this repo
__Issue:__ None
__Risk:__ low, as less code is built after this
__Testing:__ Passed all CI on trunk
__Reviewer:__ @neonichu
> [5.10] Revert 'Add missing dependencies (#888)'

- llbuild.xcodeproj/project.pbxproj
This is more correct when building llbuild as part of a larger workspace in Xcode
> Use PROJECT_DIR-relative paths instead of SRCROOT in xcode project

- CMakeLists.txt
This enables the use of swift-llbuild with CMake in a larger project with CMake. In particular, this enables the use of swift-llbuild with FetchContent to enable integration with other projects for vendoring.
> build: support using llbuild in larger projects

- CMakeLists.txt
This allows us to build fewer build targets unless the tests are intended to be run.
> build: allow optionally building tests

- include/llbuild/Basic/Subprocess.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- products/libllbuild/include/llbuild/buildsystem.h
- products/llbuildSwift/BuildSystemBindings.swift
> Fix a few comment typos in the codebase

- examples/c-api/buildsystem/main.c
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/llbuildSwift/BuildSystemBindings.swift
- unittests/CAPI/BuildSystem-C-API.cpp
Previously, these were kept alive in large arrays tied to the lifetime of the BuildSystem object. Instead, tie their lifetime to the CAPITools and CAPIExternalCommands which delegate to them. This makes ownership significantly easier to reason about and allows clients to tear them down more eagerly in context where the build system is reused for multiple build operations.
> Tie lifetimes of Swift wrappers to c++ command and tool objects

- include/llbuild/BuildSystem/BuildSystem.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- include/llbuild/BuildSystem/Command.h
- include/llbuild/BuildSystem/ExternalCommand.h
- include/llbuild/Core/BuildEngine.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/BuildSystem/ExternalCommand.cpp
- lib/Commands/BuildEngineCommand.cpp
- lib/Commands/BuildSystemCommand.cpp
- lib/Commands/NinjaBuildCommand.cpp
- lib/Core/BuildEngine.cpp
- lib/Evo/EvoEngine.cpp
- perftests/Xcode/PerfTests/CorePerfTests.mm
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/Core-C-API.cpp
- unittests/BuildSystem/MockBuildSystemDelegate.h
- unittests/Core/BuildEngineCancellationTest.cpp
- unittests/Core/BuildEngineTest.cpp
- unittests/Core/DepsBuildEngineTest.cpp
Thread the input key through provide value so that we can diagnose exactly which dynamically requested input was missing.
> rdar://124230544 (Improve fidelity of missing input errors for dynamically requested inputs)

- utils/Xcode/create-lit-site-cfg.sh
This prevents the script from failing when any of these paths contain an = character.
> Escape = characters in interpolated variables in sed expressions since = is used as the delimiter character

- lib/BuildSystem/BuildFile.cpp
We have started to see errors in one of our third party tools that is raising this specific error (`error: error: invalid tool type in 'tools' map`). However, there is no information to go on regarding what tool was unfound and since the issue is not consistent we are having a tough time tracking down what the issue might be. This change simply includes the tool name that could not be found which will hopefully help us narrow down the issue.
> Include the name of the unfound tool in the error.

- products/llbuildSwift/BuildDBBindings.swift
- products/llbuildSwift/BuildKey.swift
- products/llbuildSwift/BuildSystemBindings.swift
- products/llbuildSwift/BuildValue.swift
- products/llbuildSwift/Internals.swift
This was recently added in swiftlang/swift#72161 and swiftlang/swift#72634. I've been building it with this patch on my daily Android CI since then, finagolfin/swift-android-sdk#151, and all the same tests pass as before when I build natively on Android too.
@owenv, should be an easy review.
> Import new Android overlay

- products/llbuildSwift/BuildDBBindings.swift
- products/llbuildSwift/BuildKey.swift
- products/llbuildSwift/BuildSystemBindings.swift
- products/llbuildSwift/BuildValue.swift
- products/llbuildSwift/Internals.swift
__Explanation:__ Now that this new module and overlay were merged into the 6.0 compiler too in swiftlang/swift#74758, this adds the overlay to the five files that currently `import Glibc`.
__Scope:__ Add imports on Android only
__Issue:__ None
__Original PR:__ #919 and #921
__Risk:__ None
__Testing:__ Passed all CI on trunk, plus on my daily Android CI, finagolfin/swift-android-sdk#151
__Reviewer:__ @owenv
@ddunbar, let me know what you think.
> [6.0] Import new Bionic module from Android overlay

- include/llbuild/BuildSystem/BuildFile.h
- include/llbuild/BuildSystem/BuildSystem.h
- lib/BuildSystem/BuildFile.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/Commands/BuildSystemCommand.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/llbuild-defines.h
- products/llbuildSwift/BuildSystemBindings.swift
This ensures the build system can correctly track when dynamic task outputs are deleted, and rebuild them
> Support configuring output nodes of dynamic tasks

- llbuild.xcodeproj/project.pbxproj
- products/llbuildSwift/BuildSystemBindings.swift
These paths are expected to be absolute, but that should be handled by the `fs` object.
> Remove invalid path check

- examples/c-api/buildsystem/main.c
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/libllbuild/include/llbuild/llbuild-defines.h
- products/llbuildSwift/BuildSystemBindings.swift
- products/llbuildSwift/BuildValue.swift
- unittests/CAPI/BuildSystem-C-API.cpp
External commands wishing to implement their own `isResultValid()` check are not given enough resources to check the output files and other things `ExternalCommand::isResultValid()` does by default. This makes it impossible to just add some extra checks on top of the default implementation.
This PR adds new C API and extends the `ProducesCustomBuildValue` protocol that allow clients to fall back to the default implementation.
> Provide more powerful `isResultValid` API

- examples/c-api/buildsystem/main.c
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/libllbuild/include/llbuild/llbuild-defines.h
- products/llbuildSwift/BuildSystemBindings.swift
- products/llbuildSwift/BuildValue.swift
- unittests/CAPI/BuildSystem-C-API.cpp
Reverts swiftlang/swift-llbuild#926
Caused downstream failures that need to be investigated.
> Revert "Provide more powerful `isResultValid` API"

- Package.swift
- unittests/Swift/BuildDBBindingsTests.swift
- unittests/Swift/BuildSystemBindingsTests.swift
- unittests/Swift/BuildSystemEngineTests.swift
This adds a dependency on the new swift-toolchain-sqlite package, which allows llbuild to build using `swift build` on Windows (including tests) without any additional flags or preinstalled dependencies.
rdar://133338086
> Add support for building on Windows using SwiftPM

- examples/c-api/buildsystem/main.c
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/libllbuild/include/llbuild/llbuild-defines.h
- products/llbuildSwift/BuildSystemBindings.swift
- products/llbuildSwift/BuildValue.swift
- unittests/CAPI/BuildSystem-C-API.cpp
This reverts commit a3ef0f7909ffd023a390dc1f677cf2cbdffbb166 (https://github.com/swiftlang/swift-llbuild/pull/928) and essentially reapplies 437dac184b64dff1a2ca49ff9c6fd09417473bda (https://github.com/swiftlang/swift-llbuild/pull/926). The downstream failure was not related to this change.
Note that compared to the original commit, this one also initializes the newly introduced function pointer to nil in BuildSystemBindings.swift.
> Reapply "Provide more powerful `isResultValid` API"

- lib/Basic/PlatformUtility.cpp
This fixes a regression introduced by #597, where the following line 3900ed4#diff-bd65cf12ed29b52c530ff04d2c678eb66883eddfcb44d5dbb8fe499f25865e93R219 presumably meant to use std::max instead of std::min.
The impact of this is that estimateTaskLimits falls back to a default case of returning only a single lane, regardless of the number of requested lanes, and consequently all builds are serialized.
Now, we simply return the value of _getmaxstdio directly. The documentation does not indicate that this function can fail or return a negative or zero value, and attempting to set the value with _setmaxstdio will terminate the process if given any value less than _IOB_ENTRIES (3).
Closes: #936
> Improve build performance by a factor of $CORE_COUNT

- README.tritium.md
- Fixup image link
- Disambiguate system unification from graph unification
> Tritium README tweaks

- Package.swift
- products/llbuildSwift/BuildSystemBindings.swift
The package manifest was recently updated, and the trunk 6.1 compiler recently started complaining that this larger Android overlay is needed instead.
> Link SQLite3 on Android and switch one import back to the Android overlay

- Package.swift
- include/llvm/Config/config.h
- unittests/TestSupport/XCTestCase+Extensions.swift
This will allow building llbuild with a Swift Static SDK using Musl libc, using SwiftPM.
> Add some feature flags to control use of optional features in the build

- products/llbuild3/SwiftAdaptors.hpp
- src/llbuild3/core/Engine.swift
Exposed the existing `makeExtCASDatabase` function to Swift via SwiftAdaptors.hpp. Added a `casDB` parameter to `TEngine`'s main initializer, and used `makeExtCASDatabase` to make the necessary `CASDatabaseRef` when `casDB` is not nil.
This matches the behavior of the `TActionCache?` parameter to `TEngine`'s main initializer.
This commit resolves #959.
> [llbuild3] Add support for passing a TCASDatabase to TEngine.

- lib/Basic/CMakeLists.txt
- lib/BuildSystem/CMakeLists.txt
- lib/Core/CMakeLists.txt
- lib/Ninja/CMakeLists.txt
- lib/llvm/Demangle/CMakeLists.txt
- lib/llvm/Support/CMakeLists.txt
- products/libllbuild/CMakeLists.txt
When building with llbuild using statically linked libraries, we need to export additional targets to ensure that the full closure is available to consumers. This is meant to support building swift-driver against a statically linked library form of llbuild to allow using the early swift-driver on Windows.
> build: add additional target exports for static linking

- lib/llvm/Demangle/CMakeLists.txt
- lib/llvm/Support/CMakeLists.txt
- tests/Examples/buildsystem-capi.llbuild
- utils/import-llvm/cmake/demangleCMakeLists.txt
- utils/import-llvm/cmake/supportCMakeLists.txt
This mirrors the change to `LLVMSupport`. While this is not a robust change, it does make the build more uniform. We should instead be adding inline namespaces and renaming the library as we do in the Swift runtime.
> build: rename `LLVMDemangle` to `llvmDemangle`

- CMakeLists.txt
- tests/CMakeLists.txt
The llbuild project was emitting a few warnings from the CMake build. This was because it was relying on deprecated modules and behaviors. These patches fix both.
The `PythonInterp` module is deprecated in favor of `Python`, `Python2`, or `Python3`. Given that `llvm-lit` no longer works with Python versions at least below 3.7, I've gone ahead and updated this to look for Python 3.7 or newer when testing is enabled.
The project was also using the CMP0037 `OLD` behavior to silence the warning about the `test` target name being reserved. As of CMake 3.11 (llbuild requires 3.19 or newer), it is only reserved when using the CMake testing infrastructure, which `llbuild` does not. Now, setting this version to `OLD` results in a warning about the old behavior being deprecated. It isn't needed, so …
> Fix CMake warnings in llbuild

- lib/llvm/Support/CMakeLists.txt
> OpenBSD gets `backtrace` from libexecinfo.

- products/llbuildSwift/BuildSystemBindings.swift
This change is required by [this PR](https://github.com/swiftlang/swift-build/pull/173#issuecomment-2662357184) for swift-build repo
Please let me know if we need to introduce a soft deprecation as well.
Thanks
> fix: typo in the word `dependency`

- lib/Basic/Subprocess.cpp
We shouldn't name our polyfill the same as the POSIX function; this would infinite loop on Solaris or NetBSD for example.
> Rename posix_spawn_file_actions_addchdir polyfill

- lib/Basic/Subprocess.cpp
We shouldn't name our polyfill the same as the POSIX function; this would infinite loop on Solaris or NetBSD for example.
(cherry picked from commit 9087bdf8c7d4c95402d6d811745ca5ff3e149741)
> [6.2] Rename posix_spawn_file_actions_addchdir polyfill

- include/llvm/Config/config.h
Despite being declared in the header unistd.h, the function `sbrk` is not available on FreeBSD when using the aarch64 architecture because FreeBSD made the decision to drop support for this deprecated function when porting the system to ARM.
The configuration script incorrectly hard-codes the support for this function as being always available, which is not correct. We need to ensure that it is not used on FreeBSD aarch64.
> [FreeBSD] Fix target conditionals for FreeBSD aarch64 builds

- CMakeLists.txt
This allows building llbuild without having the dependencies checked out or passed to the building. This functionality will allow building an early swift-driver statically on Windows.
> build: add support to vendor SQLite3

- lib/Basic/Subprocess.cpp
_6.2 cherry-pick_ https://github.com/swiftlang/swift-llbuild/pull/985
Explanation: Fix posix_spawn_file_actions_addchdir on Android
Scope: Build
Issue: https://github.com/swiftlang/swift-llbuild/pull/985
Risk: Low, limited mostly to Android
Testing: Builds
Reviewer: @jakepetroules
> [6.2] Return ENOSYS for posix_spawn_file_actions_addchdir on older Android versions

- products/llbuildSwift/BuildSystemBindings.swift
Bring this back to 6.2 as well so swift-build can adopt the corrected naming sooner rather than later.
> [6.2] fix: typo in the word `dependency`

- cmake/modules/LLBuildConfig.cmake.in
- products/libllbuild/include/llbuild/llbuild.h
LLBuild depends on `Threads` and `SQLite3`. Add the module dependencies into the module configuration so that the consumer does not need to provide them *before* the import of the configuration.
> build: ensure that dependencies are found for consumers

- products/libllbuild/CMakeLists.txt
- products/llbuild/CMakeLists.txt
- products/llbuildSwift/CMakeLists.txt
- tests/CMakeLists.txt
- unittests/CAPI/CMakeLists.txt
Because `llbuild` is the executable, we cannot have another target with the name `llbuild` which is the library target. As such, the library is named `libllbuild`. This changes the output name of the library to `liblibllbuild`. This was being overridden which caused some trouble for builds which attempted to skirt the dependencies. Rename the output to the proper name.
> build: rename `libllbuild` to the proper `liblibllbuild`

- products/libllbuild/CMakeLists.txt
- products/llbuild/CMakeLists.txt
These were originally added 6 years ago in #475 to "Disable incremental linking so llbuild.ilk's don't conflict" because at the time the command line tool and library targets were given the same OUTPUT_NAME, which conflicted. In #1005 these targets were given distinct names, so the workaround should no longer be necessary.
This helps unblock swiftlang/swift-build#757 because this flag is currently added without regard for the specific compiler driver in use, so the flag might not work based on whether clang-cl.exe or cl.exe vs clang.exe (where it would require a -Xlinker prefix), is used.
> Remove /INCREMENTAL:NO flag for llbuild-tool and libllbuild targets on Windows
