- lib/Commands/NinjaBuildCommand.cpp
The -t option to Ninja is used to run subtools. One subtool, "targets",
was already implemented, but this support was not in the help. Also, to
determine which tools are available, the "-t list" option is useful;
especially so while only a subset of the Ninja subtools are implemented.
> [Ninja] Document -t, --tool option and add the "list" tool.

- lib/Commands/NinjaBuildCommand.cpp
The -l and -d options are supported by Ninja and used by scripts that
call into Ninja, but are not yet supported by llbuild's ninja driver.
For now, document them as being not implemented, parse them, warn that
they are not being used, then ignore them. This allows using scripts
that expect all Ninja options to be available immediately with llbuild.
> [Ninja] Parse, warn, and ignore -l and -d options.

- products/swift-bindings/llbuild.swift
This makes the binding swift 3 compatible. Tested using following example:
```swift
import swiftllbuild
typealias Compute = [Int] -> Int
class SimpleTask: Task {
let inputs: [Key]
var values: [Int]
let compute: Compute
init(_ inputs: [Key], compute: Compute) {
self.inputs = inputs
values = [Int](repeating: 0, count: inputs.count)
self.compute = compute
}
func start(_ engine: TaskBuildEngine) {
for (idx, input) in inputs.enumerated() {
engine.taskNeedsInput(input, inputID: idx)
}
}
func provideValue(_ engine: TaskBuildEngine, inputID: Int, value: Value) {
values[inputID] = Int(value.toString())!
}
func inputsAvailable(_ engine: TaskBuildEngine) {
let result = compute(values)
engine.taskIsComplete(Value("\(result)"), forceChange: false)
}
}
class SimpleBuildEngineDelegate: …
```
> [swift-binding] Update bindings to swift 3

- include/llbuild/Basic/ShellUtility.h
- lib/Basic/CMakeLists.txt
- lib/Basic/ShellUtility.cpp
- lib/BuildSystem/BuildSystem.cpp
- tests/BuildSystem/Build/basic.llbuild
- unittests/Basic/CMakeLists.txt
- unittests/Basic/ShellUtilityTest.cpp
Fixes https://bugs.swift.org/browse/SR-1174
> [Basic] Add utility method to create a shell quoted strings

- products/swift-bindings/llbuild.swift
Update for SE-0107 RawPointer.
This was a straightforward search/replace that I forgot to pull in with the corresponding change on swift master.
> UnsafePointer<Void> -> UnsafeRawPointer

- docs/development.rst
This adds documentation for building via ninja on OSX and Linux pending FileCheck instructions
> Add build from source notes

- cmake/modules/FindFileCheck.cmake
This is the version that is installable on Ubuntu 14.04
> Add path for llvm-3.6-tools

- products/libllbuild/CMakeLists.txt
- products/llbuild/CMakeLists.txt
- products/swift-build-tool/CMakeLists.txt
- unittests/Basic/CMakeLists.txt
- unittests/BuildSystem/CMakeLists.txt
- unittests/Core/CMakeLists.txt
- unittests/Ninja/CMakeLists.txt
This is not available on Windows. Anyway, we don't even need this, since it is unix specific
> Don't attempt to link curses.lib on Windows

- products/ui/README.md
- products/ui/llbuildui/__init__.py
- products/ui/llbuildui/app.py
- products/ui/llbuildui/database.py
- products/ui/llbuildui/model.py
- products/ui/llbuildui/views.py
- products/ui/setup.py
This PR adds a basic web app for visualizing llbuild database files.
> Add database visualization web app.

- include/llbuild/Basic/PlatformUtility.h
- lib/Basic/CMakeLists.txt
- lib/Basic/LeanWindows.h
- lib/Basic/PlatformUtility.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/Commands/NinjaBuildCommand.cpp
- lib/Commands/NinjaCommand.cpp
`chdir(1)` doesn't exist on Windows - use the `SetCurrentDirectory` Win32 API instead.
> Use change directory instead of chdir on Windows

- CMakeLists.txt
We need this for various llvmSupport build fixes
> [CMake] Add necessary definitions for Windows SDK

- include/llbuild/Basic/PlatformUtility.h
- lib/Basic/PlatformUtility.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/Core/SQLiteBuildDB.cpp
- unittests/Core/CMakeLists.txt
Avoids #ifdefs and unavoidable unistd.h imports on windows
> Introduce and use PlatformUtility.unlink

- include/llbuild/Basic/PlatformUtility.h
- lib/Basic/PlatformUtility.cpp
- lib/BuildSystem/SwiftTools.cpp
Also clang-format PlatformUtility.h
> Add and use platform abstractions for popen and pclose

- include/llbuild/Basic/PlatformUtility.h
- lib/Basic/PlatformUtility.cpp
- lib/Commands/BuildSystemCommand.cpp
- lib/Commands/NinjaBuildCommand.cpp
Also run clang-format on PlatformUtility.cpp
> Add write(3) to PlatformUtility

- include/llbuild/BuildSystem/BuildSystem.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- llbuild.xcodeproj/project.pbxproj
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
- unittests/BuildSystem/LaneBasedExecutionQueueTest.cpp
- unittests/BuildSystem/TempDir.cpp
- unittests/BuildSystem/TempDir.h
- A couple cleanups as part of making it easier to unit test the BuildSystem component.
> Build system testing

- include/llbuild/BuildSystem/BuildExecutionQueue.h
- include/llbuild/BuildSystem/ExternalCommand.h
- lib/BuildSystem/BuildExecutionQueue.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/ExternalCommand.cpp
- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- lib/BuildSystem/SwiftTools.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- unittests/BuildSystem/BuildSystemTaskTests.cpp
- unittests/BuildSystem/MockBuildSystemDelegate.h
> Do not process dependencies of cancelled commands

- lib/BuildSystem/BuildSystem.cpp
- Computing shell command signatures can be expensive; this speeds up null
builds in cases where the build description is being held in memory.
> [BuildSystem] Cache the ShellCommand signature.

- docs/buildsystem-internals.md
- docs/buildsystem.rst
- tests/BuildSystem/Build/directory-tree-client-edges.llbuild
- Also, add a doc note on this behavior.
> [tests] Add explicit test for synthetic edges on directory tree nodes.

- lib/BuildSystem/BuildSystem.cpp
- tests/BuildSystem/Build/changed-link-target.llbuild
- <rdar://problem/31522690> Missing rebuild of symlink node if target changes
> [BuildSystem] Fix a missing signature check for symlink commands.

- lib/BuildSystem/BuildSystem.cpp
- Found by a newer version of ASAN!
- <rdar://problem/31561038> Bot Issue for llbuild-asan (test assertion in -[LitTests testllbuild____BuildSystem_Build_archive_llbuild])
> [BuildSystem] Fix use after free.

- lib/BuildSystem/BuildSystemFrontend.cpp
This fixes a race which occurs when delegate is being initialized and
clients call cancel().
This also adds asserts that clients call build() before cancel().
-- <rdar://problem/31951869>
> [BuildSystem] Fix a race between build() and cancel()

- lib/Core/SQLiteBuildDB.cpp
- This adds an additional covering index for the rule dependency query, which
is important for the null build case where our work largely amounts to
populating and scanning the results.
- This fixes a regression introduced in
bcc3d1011eff6450d74f9b0bec913d17bf48efa2 -- the table primary key index was
previously covering, but now is not because of the required ordinal
parameter.
- This change is unfortunate as there is a lot of redundancy in the tables, and
this increases database size by 25% in one example, but it is also good for a
~10% win in null build time on a large graph.
- <rdar://problem/32127527> Investigate optimizing rule dependency w/ ordinal lookup
> Optimize the rule dependency search query.

- include/llbuild/BuildSystem/BuildSystem.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
<rdar://problem/32126388> Race in BuildSystemImpl
> [BuildSystem] Fix yet another cancellation race

- include/llbuild/Core/BuildDB.h
- include/llbuild/Core/BuildEngine.h
- lib/Core/BuildEngine.cpp
- lib/Core/SQLiteBuildDB.cpp
- unittests/Core/BuildEngineTest.cpp
Reverts apple/swift-llbuild#155
Keeping the PR ready in case we do need to revert.
> Revert "Change DB API to find constant key IDs."

- unittests/BuildSystem/BuildSystemTaskTests.cpp
Otherwise, we might run into concurrent access on the build database.
> [BuildSystemTaskTests] Make sure first build system is closed before building with the second one

- lib/Core/SQLiteBuildDB.cpp
- Now that the rule dependencies are stored directly by key ID, we can
denormalize the `rule_result` table to directly include the results (as a
binary blob). This results in a substantially more compact database and
efficient access to the rule result (given that we always rewrite rules
wholesale).
- This also enables future optimizations to avoid the result re-insert.
- <rdar://problem/32180158> Denormalize rule_result table to include dependencies
> [Core/DB] Denormalize rule dependencies.

- lib/Core/SQLiteBuildDB.cpp
- This adds the version bump which should have accompanied fe255aa1.
> [Core] Bump DB schema version.

- examples/c-api/buildsystem/main.c
- include/llbuild/BuildSystem/BuildSystem.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- include/llbuild/BuildSystem/CommandResult.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/BuildSystem/ExternalCommand.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/public-api/llbuild/buildsystem.h
- products/libllbuild/public-api/llbuild/llbuild.h
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
- unittests/BuildSystem/BuildSystemTaskTests.cpp
- unittests/BuildSystem/MockBuildSystemDelegate.h
-- <rdar://problem/32288402> Pass CommandResult in BuildSystemFrontendDelegate.commandFinished delegate
This is cherry pick of the following 3 commits in master. These are
completely related commits so are amended into one.
(cherry picked from commit 2cc02a111ed5d1d1c52be41a727819b7d8622613)
(cherry picked from commit 3a621dda909b6d2b1ec985f781c40bc04b107aa8)
(cherry picked from commit fc3d9db5dcce5c5b5ceb7538efeb294445235b54)
> [BuildSystem] Add CommandResult in commandFinished delegate

- llbuild.xcodeproj/project.pbxproj
- <rdar://problem/35299761> 2 errors in raw_os_ostream.h:33
> [Xcode] Add GTEST_NO_LLVM_RAW_OSTREAM declarations for Xcode project.

- include/llbuild/BuildSystem/BuildSystemFrontend.h
- lib/BuildSystem/BuildSystemFrontend.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/libllbuild/include/llbuild/llbuild.h
Merging #211 into the `swift-4.1` branch.
> [Swift 4.1] Expose ability to build a node through the API.

- lib/BuildSystem/BuildSystemFrontend.cpp
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
<rdar://problem/36587411> Better error-handling for single node builds
> Improve error handling for single node builds

- lib/BuildSystem/BuildSystemFrontend.cpp
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
Merging #213 into the swift-4.1 branch.
> [Swift 4.1] Single node build error handling

- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- lib/Commands/NinjaBuildCommand.cpp
Instead we should get possible errors from the return value.
> `posix_spawn` does not set `errno`

- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- lib/Commands/NinjaBuildCommand.cpp
Merging #220 into the swift-4.1 branch.
> [Swift 4.1] `posix_spawn` does not set `errno`

- lib/Core/MakefileDepsParser.cpp
- unittests/Core/MakefileDepsParserTest.cpp
Merging #222 into the swift-4.1 branch.
> [Swift 4.1] Fix parsing of some special characters in .d files

- llbuild.xcodeproj/project.pbxproj
> Allow Generate-version.h to work with paths that contain spaces

- Xcode/Configs/Version.xcconfig
- examples/c-api/buildsystem/main.c
- include/llbuild/BuildSystem/BuildExecutionQueue.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- include/llbuild/BuildSystem/CommandResult.h
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- llbuild.xcodeproj/project.pbxproj
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/libllbuild/include/llbuild/llbuild.h
- products/llbuildSwift/BuildSystemBindings.swift
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
- unittests/BuildSystem/LaneBasedExecutionQueueTest.cpp
- unittests/BuildSystem/MockBuildSystemDelegate.h
This reverts commit e57c536296049da8daac062871dad9d382703076.
> Revert "Report extended results in commandProcessFinished"

- Package.swift
- llbuild.xcodeproj/project.pbxproj
- products/libllbuild/CMakeLists.txt
- products/libllbuild/include/llbuild/llbuild.h
- products/libllbuild/include/llbuild/version.h
- products/llbuildSwift/CMakeLists.txt
- tests/Examples/buildsystem-capi.llbuild
- utils/generate-version-h.sh
Simplifies usage of generated header with SwiftPM
> Generate version.h in place

- include/llbuild/Basic/Tracing.h
Because these are simple RAII structs intended to be used directly, they
can't be expected to be subclassed, and users would end up having to
redefine their implementation in a modified version of this header.
> Add some macros to easily allow users to hook into the tracing system

- Xcode/Configs/Version.xcconfig
- examples/c-api/buildsystem/main.c
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/libllbuild/include/llbuild/llbuild.h
- products/libllbuild/include/llbuild/version.h
> Upgrade to C API version 5

- lib/Core/BuildEngine.cpp
- This puts a cache in front of the database lookups for key IDs. This change
hasn't yet gone through complete performance testing, but this may help
reduce contention when running on large projects or with high core counts.
- <rdar://problem/38038460> pthread_mutex lock contention under ShellCommand::processMakefileDiscoveredDependencies()
> [Core] Add a cache for key -> ID lookups.

- include/llbuild/Basic/Tracing.h
- lib/Basic/CMakeLists.txt
- lib/Basic/Tracing.cpp
- llbuild.xcodeproj/project.pbxproj
- products/libllbuild/Core-C-API.cpp
- products/libllbuild/include/llbuild/core.h
- Exposes tracing point toggle via the C API
> Allow tracing points to be conditionally enabled and disabled

- lib/Core/SQLiteBuildDB.cpp
- Cache engine KeyID to DBKeyID mapping
- When ID mapping is known, skip table join in lookupRuleResult
- Cache ID mapping when reading out previously unknown rules
Yields a ~17% improvement in the testPseudoLLVMNullBuild test
> Add fast path lookupRuleResult query

- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- tests/BuildSystem/Build/phony.llbuild
- Orders tasks based on Command name
rdar://problem/39801843
> Change LaneBasedExecutionQueue scheduling algorithm to be a priority queue

- llbuild.xcodeproj/project.pbxproj
For those of us who like to use Xcode, this makes it much more convenient
to search and edit.
> Add all of the source files in the project directory to the Xcode project

- products/libllbuild/BuildSystem-C-API.cpp
> Fix unintended switch fallthrough in llb_set_scheduler_algorithm()

- llbuild.xcodeproj/project.pbxproj
- products/llbuildSwift/BuildSystemBindings.swift
- products/llbuildSwift/CoreBindings.swift
Depends on https://github.com/apple/swift-llbuild/pull/247
> [Xcode] Build swift bindings as part of llbuild.framework

- Xcode/Configs/Common.xcconfig
- llbuild.xcodeproj/project.pbxproj
We want to opt individual targets into installation, and of the
libraries, we want to install llbuild.framework, not llbuild.dylib.
> De-confuse SKIP_INSTALL settings

- include/llbuild/BuildSystem/BuildKey.h
- include/llbuild/BuildSystem/BuildValue.h
- lib/llvm/Support/Mutex.cpp
- lib/llvm/Support/SmallPtrSet.cpp
- unittests/BuildSystem/BuildSystemTaskTests.cpp
rdar://problem/40484309&40484331&40484338
> Address multiple static analysis warnings

- lib/BuildSystem/LaneBasedExecutionQueue.cpp
TSAN tests show a potential data race in cancellation. Add a guard
around the killAfterTimeoutThread variable to protect against it.
rdar://problem/40707314
> [BuildSystem] Guard killAfterTimeoutThread in LaneBasedExecutionQueue

- include/llbuild/BuildSystem/BuildKey.h
- include/llbuild/BuildSystem/BuildNode.h
- lib/BuildSystem/BuildNode.cpp
- lib/BuildSystem/BuildSystem.cpp
- tests/BuildSystem/Build/directory-contents-filtered-produced.llbuild
- tests/BuildSystem/Build/directory-contents-filtered.llbuild
- tests/BuildSystem/Build/directory-contents.llbuild
A bad git push on my part looks to have lost the changes I made
addressing review commentary on #320. Namely, changing
'directory-filters' to 'content-exclusion-patterns', and fixing
is valid calculation for directory contents.
rdar://problem/41153592
> [BuildSystem] Recapitulate review comment changes for #320

- include/llbuild/BuildSystem/BuildSystem.h
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/BuildSystem/LaneBasedExecutionQueue.cpp
- llbuild.xcodeproj/xcshareddata/xcschemes/llbuild.xcscheme
- products/libllbuild/BuildSystem-C-API.cpp
- utils/Xcode/create-lit-site-cfg.sh
> [BuildSystem] Fix casing of QoS/Scheduler algorithm enums

- tests/BuildSystem/Build/directory-contents.llbuild
> Add a sleep to work around coarse time resolution in CI systems

- unittests/Core/CMakeLists.txt
> [Core] Add SQLiteBuildDBTest.cpp to CMakeLists.txt

- CMakeLists.txt
- cmake/modules/Utility.cmake
- utils/write-swift-version
<rdar://problem/42543712> Rebuild Swift bindings when Swift compiler changes
> [CMake] Add dependency on the Swift compiler version

- lib/Core/SQLiteBuildDB.cpp
Filtered directory contents added and changed some key defintions such
that older versions are incompatible.
rdar://problem/44872576
> [Core] Bump SQLite DB schema version

- lib/Basic/Subprocess.cpp
Clients (especially bash on Linux) may receive SIGPIPE when we
close the lane release pipe immediately. Although we could require
clients to implement their own SIGPIPE traps, it is simpler to hold the
pipe open until we are sure the client is done.
rdar://problem/45196629
> [Basic] Hold lane release pipe open until process termination

- products/llbuildSwift/CoreBindings.swift
These memory leaks were found while profiling SwiftPM.
> fixed memory leaks reported by Instruments

- products/llbuildSwift/BuildSystemBindings.swift
Such conversions are only guaranteed to be valid for the duration of the call they're passed to (in this case `UnsafePointer`'s initialiser). Instead, allocate a buffer pointer which we can get the base address from.
(This is currently blocking https://github.com/apple/swift/pull/20070 from being able to build).
> Avoid escaping array-to-pointer conversions

- lib/BuildSystem/BuildSystemFrontend.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
> [CAPI] Fix DirectoryTreeSignature path call

- perftests/Xcode/PerfTests/BuildSystemPerfTests.mm
> [PerfTests] Appease compiler warning

- products/llbuildSwift/CoreBindings.swift
> [llbuildSwift] Expose error() delegate callback in Core bindings

- products/llbuildSwift/BuildSystemBindings.swift
> [Swift] Add build key types to BuildSystemBindings enum

- utils/check-all
- utils/docker/requirements.txt
Addresses GitHub security alert.  Also changes pip style to --user to
allow it to work out-of-the-box on macOS.
> [utils/docker] Update PyYAML dependency version

- lib/Basic/LaneBasedExecutionQueue.cpp
> [Basic] Export LLBUILD_BUILD_ID to subprocesses

- Package.swift
- products/libllbuild/include/module.modulemap
Reverts apple/swift-llbuild#412
> Revert "Update manifest version to 5.0"

- include/llbuild/Basic/CrossPlatformCompatibility.h
- include/llbuild/Basic/PlatformUtility.h
- lib/Basic/ExecutionQueue.cpp
- lib/Basic/PlatformUtility.cpp
- lib/Basic/Subprocess.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/Commands/NinjaBuildCommand.cpp
Use CreateProcessW to spawn processes on Windows. This enables simple swift-build files to work on Windows.
```
S:\build\Ninja-DebugAssert\llbuild-windows-amd64\tests\SwiftBuildTool\Output\basic.swift-build.tmp.build> cat .\build.swift-build                                         
client:                                                                                                                                                                   
name: swift-build                                                                                                                                                       
targets:                                                                                                                                                                  
"": …
```
> Implemented process spawning for windows

- include/llbuild/Basic/PlatformUtility.h
- lib/Basic/PlatformUtility.cpp
- lib/Commands/BuildSystemCommand.cpp
- lib/Commands/NinjaBuildCommand.cpp
- unittests/CAPI/BuildSystem-C-API.cpp
No more Windows Not Yet Implemented! Onto making the tests pass on Windows after this.
> Windows: Implemented the Remaining TODOs

- lib/Ninja/Lexer.cpp
llbuild ninja previously didn't handle CR properly, especially when
peeking characters.
This causes a large number of Ninja tests to pass on Windows. (Down to 40 failing tests remaining!)
> Make llbuild's Ninja implementation to handle CR

- lib/BuildSystem/BuildSystem.cpp
Json interprets the backslashes in `C:\path\to\file` as escape
sequences. Properly escape the string so that the output-file-map
works properly on Windows.
> Escape strings for JSON when writing output-file-map.json

- lib/Basic/LaneBasedExecutionQueue.cpp
- This is just for experimentation purposes.
> [Lane Release] Add an environment override for the background task cap.

- include/llbuild/BuildSystem/BuildSystem.h
- include/llbuild/Core/BuildDB.h
- lib/BuildSystem/BuildSystem.cpp
- lib/Commands/BuildSystemCommand.cpp
- lib/Core/SQLiteBuildDB.cpp
- unittests/Core/BuildEngineTest.cpp
- Supports simple build db interrogation, currently limited to querying
build keys
> Add 'db' buildsystem command

- docs/buildsystem-extensions.md
- docs/contents.rst
- include/llbuild/BuildSystem/BuildSystemCommandInterface.h
- include/llbuild/BuildSystem/BuildSystemExtensions.h
- include/llbuild/BuildSystem/BuildSystemHandlers.h
- include/llbuild/BuildSystem/ExternalCommand.h
- include/llbuild/BuildSystem/ShellCommand.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemExtensionManager.cpp
- lib/BuildSystem/CMakeLists.txt
- lib/BuildSystem/ShellCommand.cpp
- llbuild.xcodeproj/project.pbxproj
* This is completely experimental at this time, see docs/ for more info.
> [plugins] Add initial sketch of an llbuild extensions API.

- tests/BuildSystem/Build/now-produced-rule.llbuild
"This time for sure!"
rdar://problem/48946422
> [tests] Fix now-produced-rule.llbuild on HFS+

- products/llbuildSwift/BuildSystemBindings.swift
This will allow testing SwiftPM's `BuildDelegate`.
> Allow Command to be initialized with values

- include/llbuild/Basic/PlatformUtility.h
- lib/Basic/PlatformUtility.cpp
- lib/BuildSystem/BuildSystemExtensionManager.cpp
Update the build system to build for Windows.  This allows llbuild to
build on Windows.
> BuildSystem: port plugin system to Win32

- lib/Commands/CommandUtil.cpp
> Close open files, even when exiting early due to an error.

- lib/BuildSystem/BuildSystem.cpp
> [BuildSystem] Properly hold lock when releasing executionQueue

- CMakeLists.txt
- LICENSE.txt
- cmake/modules/FindSQLite3.cmake
- cmake/modules/Utility.cmake
- lib/Basic/CMakeLists.txt
- lib/BuildSystem/CMakeLists.txt
- lib/Commands/CMakeLists.txt
- lib/Core/CMakeLists.txt
- lib/Ninja/CMakeLists.txt
- lib/llvm/Support/CMakeLists.txt
- perftests/Xcode/PerfTests/CMakeLists.txt
- products/libllbuild/CMakeLists.txt
- products/llbuild/CMakeLists.txt
- products/swift-build-tool/CMakeLists.txt
- tests/CMakeLists.txt
- unittests/Basic/CMakeLists.txt
- unittests/BuildSystem/CMakeLists.txt
- unittests/CAPI/CMakeLists.txt
- unittests/Core/CMakeLists.txt
- unittests/Ninja/CMakeLists.txt
- utils/import-llvm/cmake/supportCMakeLists.txt
- utils/unittest/UnitTestMain/CMakeLists.txt
This is a collection of various improvements to use more modern CMake constructs.  This makes the build less reliant on the specifics of the compiler that you are using and just simplifies build rules.
> CMake improvements

- include/llbuild/Ninja/Manifest.h
- lib/Commands/NinjaCommand.cpp
- lib/Ninja/ManifestLoader.cpp
- Post Ninja 1.6, a scope can contain more than just variable bindings.
- NIFC.
> [Ninja] Rename BindingSet to Scope.

- include/llbuild/Ninja/Manifest.h
- lib/Commands/NinjaBuildCommand.cpp
- lib/Commands/NinjaCommand.cpp
- lib/Ninja/Manifest.cpp
- lib/Ninja/ManifestLoader.cpp
- tests/Ninja/Loader/Inputs/subninja-rule-scoping-1.ninja
- tests/Ninja/Loader/Inputs/subninja-rule-scoping-2.ninja
- tests/Ninja/Loader/subninja-rule-scoping.ninja
- https://bugs.swift.org/browse/SR-2858
- <rdar://problem/28616636> [SR-2858] llbuild Ninja support doesn't handle rules in subninja scope
> [Ninja] Add support for Ninja 1.6 style rule scoping.

- include/llbuild/Basic/Defer.h
- lib/Core/BuildEngine.cpp
- llbuild.xcodeproj/project.pbxproj
- unittests/Basic/CMakeLists.txt
- unittests/Basic/Defer.cpp
- unittests/Core/BuildEngineTest.cpp
Suspected as potential cause of rdar://problem/53261527
> [BuildEngine] Guard against concurrent engine use

- lib/Basic/Subprocess.cpp
> [Basic] Report executable in spawn process error

- lib/Commands/NinjaBuildCommand.cpp
> [Ninja] Properly clean up BuildContext sig thread

- Package.resolved
- Package.swift
- llbuild.xcodeproj/project.pbxproj
- products/llbuild-analyze/Tool.swift
- products/llbuild-analyze/main.swift
- products/llbuild/main.cpp
This infrastructure does only contain a dummy command which prints out hello world but will contain more in following work.
rdar://54550630
There's no reference in the Xcode project to this tool since it can't specify the dependency on swift-tools-support-core. So building the tool is only supported via SwiftPM.
> Create a basic tooling infrastructure for build analysis tools.

- products/llbuild/main.cpp
StringRef doesn't deallocate it's char pointer so that needs to be done after the external command has been run.
Also return the actual exit status of the external command.
rdar://55195607
> Fix memory leak when copying strings

- lib/Core/SQLiteBuildDB.cpp
> Close database and assert afterwards on the result.

- lib/Commands/NinjaBuildCommand.cpp
The `NINJA_STATUS` specifies the prefix for the status line:
https://ninja-build.org/manual.html#_environment_variables
rdar://55968598
> Honor the NINJA_STATUS environment

- lib/Commands/CommandLineStatusOutput.cpp
- lib/Commands/CommandLineStatusOutput.h
- lib/Commands/NinjaBuildCommand.cpp
- tests/Ninja/Build/strip-colors.ninja
> Strip ANSI colors unless CLICOLOR_FORCE is in effect

- tests/Ninja/Build/modify-retaining-timestamp.ninja
- tests/Ninja/Build/order-only-skip.ninja
Temporarily modify the test until a proper fix is applied.
rdar://56045388
> Modify test so it updates the timestamp on FSs with 1-second resolution

- include/llbuild/Ninja/Manifest.h
- lib/Commands/NinjaBuildCommand.cpp
- lib/Ninja/Manifest.cpp
- tests/Ninja/Build/normalize-path.ninja
- unittests/Ninja/CMakeLists.txt
- unittests/Ninja/ManifestTest.cpp
> Syntactically normalize path names

- llbuild.xcodeproj/project.pbxproj
- rdar://56270635 (DerivedData/Build/Products/Debug/adjust-times: No such file or directory)
> [Xcode] Add a missing dependency on `adjust-times`.

- utils/Xcode/LitXCTestAdaptor/LitTests.py
See https://reviews.llvm.org/D69002
> Update to a newer lit API

- lib/Basic/Subprocess.cpp
- tests/Ninja/Build/Inputs/close-control-fd
- tests/Ninja/Build/console-pool-input.ninja
- tests/Ninja/Build/console-pool-no-control-fd.ninja
- tests/Ninja/Build/console-pool.ninja
> Avoid releasing console-pool bound jobs too early

- lib/Commands/NinjaBuildCommand.cpp
> -d list not to proceed with the build

- products/llbuildSwift/BuildSystemBindings.swift
> Clean up swift binding handling of scheduler(Algorithm/Lanes)

- include/llbuild/Basic/FileSystem.h
- lib/Basic/FileSystem.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- llbuild.xcodeproj/project.pbxproj
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/llbuildSwift/BuildSystemBindings.swift
- unittests/BuildSystem/BuildSystemTaskTests.cpp
> [Basic] Fail when existing mkdir() target is not a directory

- docs/buildsystem-internals.md
- This adds some documentation on known issues that we are aware of with the
current design of the BuildSystem library, as well as some early ideas on how
we might go about tackling them.
> {WIP} [docs] Start work on BuildSystem known issues.

- lib/BuildSystem/ExternalCommand.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/llbuildSwift/BuildSystemBindings.swift
- unittests/Swift/BuildSystemEngineTests.swift
Also includes a couple commits to work around assumptions that are no longer true for dynamic ExternalCommand subclasses
> Adds Swift support for discovered dependencies

- products/llbuildSwift/BuildSystemBindings.swift
- products/llbuildSwift/Internals.swift
> [Swift] Fix warning in swift bindings

- Package.swift
Thanks to @aciidb0mb3r for the patch.
> <rdar://58458757> llbuild's gtest currently fails to build with SwiftPM

- perftests/Xcode/PerfTests/CorePerfTests.mm
> Fix NaryTree perf test

- lib/Commands/NinjaBuildCommand.cpp
- unittests/Basic/LaneBasedExecutionQueueTest.cpp
> Fix TSan errors found via test execution

- lib/Commands/NinjaCommand.cpp
- tests/Ninja/Loader/json-dumping.ninja
> Ninja add support for dumping to json

- lib/Core/BuildEngine.cpp
Under early cancellation and other early exit conditions, build() may
leave the db transaction open or rule scan records allocated. Move those
cleanup actions into scope defers for all exits.
rdar://problem/60856571
> [Engine] Ensure build() cleans under early exit

- llbuild.xcodeproj/project.pbxproj
> Make BuildKey-C-API-Private.h project not private

- lib/BuildSystem/ExternalCommand.cpp
> Handle new case in ProcessStatus switch

- include/llbuild/CAS/DataID.h
- unittests/CAS/CMakeLists.txt
- unittests/CAS/DataIDTests.cpp
- unittests/CMakeLists.txt
> [CAS] Add DenseMapInfo support for DataID.

- lib/BuildSystem/BuildSystemFrontend.cpp
> Catch and report client misuse of failed frontend objects

- tests/Ninja/Build/max-commands-progress.ninja
> [Ninja Tests] Attempt to fix flaky max-commands-progress test

- utils/Xcode/install-user-lit.sh
- utils/Xcode/install-user-sphinx.sh
> Change Xcode util scripts to be dash compatible

- perftests/Xcode/PerfTests/BuildSystemPerfTests.mm
> Fix perf test ProcessAttributes initializer

- Package.swift
SwiftPM 5.3 and earlier will crash when an unknown platform is used in a conditional. To avoid the crash, condtionalize the flags for now. The SwiftPM bug has been fixed and once it is available in a released version, we can removed this workaround.
> Conditionalize Windows flags to mitigate SwiftPM crash

- tests/Ninja/Build/multiple-outputs.ninja
> Disable ninja multiple-outputs test temporarily

- include/llbuild/BuildSystem/BuildSystemFrontend.h
> Remove doc comment for non-existent function param

- llbuild.xcodeproj/project.pbxproj
> Explicitly link to XCTest in test helper target

- tests/CMakeLists.txt
> [build] use Python3 to run lit

- tests/Ninja/Build/max-commands-progress.ninja
> [build-wrangler] Disable broken test

- examples/c-api/buildsystem/main.c
- include/llbuild/BuildSystem/BuildSystem.h
- include/llbuild/BuildSystem/BuildSystemFrontend.h
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- lib/BuildSystem/ShellCommand.cpp
- products/libllbuild/BuildSystem-C-API.cpp
- products/libllbuild/include/llbuild/buildsystem.h
- products/llbuildSwift/BuildSystemBindings.swift
- unittests/BuildSystem/MockBuildSystemDelegate.h
- unittests/CAPI/BuildSystem-C-API.cpp
- unittests/Swift/BuildSystemEngineTests.swift
> Notify the delegate when the engine has become aware of a task's discovered dependencies

- tests/Ninja/Build/incremental.ninja
> Try to fix non-deterministic output in test

- lib/Core/BuildEngine.cpp
Clients who cache and re-use a BuildSystem instance to serve multiple subsequent build operations are unable to get a trace file for multiple builds.
This is because the trace file pointer is scoped to and kept open for the lifetime of the BuildSystem instance, rather than being scoped to the build operation.
This change scopes the trace file writing to the build operation. This means that multiple build operations by the same BuildSystem will no longer be able to "append" to the same trace file (e.g. having multiple build-started/build-ended pairs), but this responsibility can be shifted to clients who can preserve the file between builds if desired.
rdar://47133775
> Scope build debugging trace file to the build operation

- utils/ptreetime/libptreetime/ptreetime.dtrace
> Update ptreetime dtrace file

- include/llbuild/Basic/ExecutionQueue.h
- include/llbuild/Core/BuildEngine.h
- lib/Basic/LaneBasedExecutionQueue.cpp
- lib/Basic/SerialQueue.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/Core/BuildEngine.cpp
> Add high priority support for job queue

- lib/BuildSystem/BuildSystem.cpp
- products/libllbuild/include/llbuild/llbuild-defines.h
> Implement update status for rules representing custom tasks

- lib/llvm/Support/Unix/Program.inc
> Fix analyzer issues

- products/llbuildSwift/BuildSystemBindings.swift
- unittests/Swift/BuildSystemEngineTests.swift
> Forward JobContext for ProducesCustomBuildValue callback

- lib/llvm/Support/Unix/Program.inc
> Fix an unused static function warning

- Xcode/Configs/Common.xcconfig
> Respect DEVELOPER_INSTALL_DIR

- lib/Commands/BuildEngineCommand.cpp
- lib/Core/BuildEngineTrace.cpp
- perftests/Xcode/PerfTests/CorePerfTests.mm
- unittests/Core/BuildEngineTest.cpp
> Replace calls to sprintf with snprintf for safety

- tests/Ninja/Build/Inputs/check-open-fds
- tests/Ninja/Build/Inputs/get-file-size
- tests/Ninja/Build/Inputs/run-releasing-control-fd
- tests/Ninja/Build/Inputs/split-numbers
- tests/Ninja/Build/Inputs/ulimited
- tests/Ninja/Build/inherited-file-descriptors.ninja
- tests/SwiftBuildTool/Inputs/pseudo-swiftc
> Adopt python3 in tests for Ubuntu 22.04 support

- products/libllbuild/BuildSystem-C-API.cpp
> Delete forwarding delegate after use

- lib/Core/BuildEngine.cpp
> Guard against deletion of an in-use build engine

- include/llbuild/BuildSystem/BuildKey.h
- lib/BuildSystem/BuildKey.cpp
- lib/BuildSystem/BuildSystem.cpp
- lib/BuildSystem/BuildSystemFrontend.cpp
- products/libllbuild/BuildKey-C-API.cpp
- products/libllbuild/include/llbuild/buildkey.h
- products/llbuildSwift/BuildKey.swift
- tests/BuildSystem/Build/directory-tree-structure-signatures-filtered.llbuild
- unittests/BuildSystem/BuildSystemFrontendTest.cpp
- unittests/BuildSystem/BuildSystemTaskTests.cpp
> Add support for filtering directory structure nodes

- unittests/Swift/BuildKeyTests.swift
> Swift testDirectoryTreeStructureSignature is failing

- lib/Core/SQLiteBuildDB.cpp
> Bump db schema version for filtered directory structure nodes

- tests/Ninja/Build/Inputs/check-open-fds
- tests/Ninja/Build/Inputs/get-file-size
- tests/Ninja/Build/Inputs/run-releasing-control-fd
- tests/Ninja/Build/Inputs/split-numbers
- tests/Ninja/Build/Inputs/ulimited
- tests/Ninja/Build/inherited-file-descriptors.ninja
- tests/SwiftBuildTool/Inputs/pseudo-swiftc
rdar://93101972
(cherry picked from commit e409e0a4cc22b7da76c540e49f7d30d9d16c6cba)
> [5.7] Adopt python3 in tests for Ubuntu 22.04 support

- tests/BuildSystem/Build/Inputs/get-file-permissions
(cherry picked from commit 8773783c650c02dc8e4cf50b4b522df6054dbdb8)
> [5.7] Update to python3 from python

- lib/BuildSystem/BuildSystem.cpp
Under some circumstances, directory iterators encountering errors will not advance, leading to infinite looping. This change adds a check in the loop condition for getContents() and getFilteredContents() usages and propagates the error_code out to the caller.
Current callers/system behavior expect those errors to be silently ignored. Added a comment making that explicitly documented.
rdar://101717159
> Check error code when processing directories

- lib/Basic/Subprocess.cpp
We are currently making calls to `poll` which could get interrupted or the resource could be temporarily not available. We should handle these cases.
Wrap the calls to `poll` in a `wile` loop and try again if we get either `EINTR` or `EAGAIN`.
We are now handling signals while we are polling correctly.
> Handle EINTR and EAGAIN when we `poll`

- lib/Basic/Subprocess.cpp
This cherry picks #855 over to the 5.8 release branch.
> Cherry pick poll fix

- lib/BuildSystem/BuildSystem.cpp
Fixes a downstream test failure that was due to `ProducedDirectoryNode` not propagating special cases similar to `ProducedNode`
> rdar://105755236 (Make ProducedDirectoryNode propagate special cases similar to ProducedNode)

- llbuild.xcodeproj/project.pbxproj
> Enable target parallelism for llbuild

- Xcode/Configs/Common.xcconfig
- llbuild.xcodeproj/project.pbxproj
Going to handle this via a different mechanism.
rdar://121717582
> Remove copy CLT content build phase

- llbuild.xcodeproj/project.pbxproj
Most of these don't declare inputs/outputs and it would be nontrivial to do so at this time.
> Mark relevant script phases inputs/outputs or as always out of date

- lib/BuildSystem/BuildSystem.cpp
This could cause us to get stuck in an infinite loop when scanning such a symlink as part of a directory tree
> When computing a directory tree signature, don't follow symlinks to parent directories

- products/llbuildSwift/BuildDBBindings.swift
- products/llbuildSwift/BuildKey.swift
- products/llbuildSwift/BuildSystemBindings.swift
- products/llbuildSwift/BuildValue.swift
- products/llbuildSwift/Internals.swift
This is simply an update to #919 based on feedback given in the similar swiftlang/swift-package-manager#7752.
> Import new Bionic module from Android overlay instead

- README.md
update with contributing information and remove redundant license information
> Update README.md with contributing and license info

- lib/Basic/PlatformUtility.cpp
Cherry pick of #937 to the 6.0 branch
> [6.0] Fix windows concurrency

- lib/Basic/PlatformUtility.cpp
Cherry pick of #937 to the 6.0.0 branch
> [6.0.0] Fix windows concurrency

- lib/Basic/PlatformUtility.cpp
Cherry pick of #937 to the 6.0.1 branch
> [6.0.1] Fix windows concurrency

- Package.swift
- lib/llvm/Support/CMakeLists.txt
- unittests/Swift/BuildSystemEngineTests.swift
- utils/adjust-times/adjust-times.cpp
Add various linker settings to enable building on FreeBSD
> Fix building on FreeBSD

- lib/Basic/Subprocess.cpp
This just syncs up the implementation with swift-corelibs-foundation which supports additional platforms. This will allow the working-directory attribute of llbuild build tasks to function correctly.
> Add support for posix_spawn_file_actions_addchdir{_np} on FreeBSD, NetBSD, Android, QNX, and Musl

- products/llbuild3/SwiftAdaptors.hpp
- src/llbuild3/Engine.cpp
- src/llbuild3/Engine.h
- src/llbuild3/Engine.swift
- src/llbuild3/Label.swift
- src/llbuild3/SwiftAdaptors.cpp
- unittests/llbuild3CoreTests/EngineTests.swift
Also adds some basic perf counters to the engine
> [llbuild3] Add Ackermann test

- Package.swift
- unittests/Swift/BuildSystemEngineTests.swift
Some of this ends up being in common with the FreeBSD stanza, so lightly refactor.
> Update OpenBSD support for swiftpm.

- lib/Basic/PlatformUtility.cpp
- lib/llvm/Support/Windows/Path.inc
- src/llbuild3/LocalExecutor.cpp
- unittests/Basic/FileSystemTest.cpp
… ops to support long filenames
> use widePath and _w variants on Windows for the file APIs
